mutation approveLoan($input: FixedTermLoanApproveInput!) {
  fixedTermLoanApprove(input: $input) {
    loan {
      loanId
      balance {
        collateral {
          btcBalance
        }
        principal {
          usdBalance
        }
        totalInterestIncurred {
          usdBalance
        }
        unpaidInterestIncurred {
          usdBalance
        }
      }
    }
  }
}
