query fixedTermLoan($id: UUID!) {
  fixedTermLoan(id: $id) {
    loanId
    balance {
      collateral {
        btcBalance
      }
      outstanding {
        usdBalance
      }
      interestIncurred {
        usdBalance
      }
    }
  }
}
