mutation fixedTermLoanCreate($input: FixedTermLoanCreateInput!) {
  fixedTermLoanCreate(input: $input) {
    loan {
      loanId
      balance {
        collateral {
          btcBalance
        }
        principal {
          usdBalance
        }
        totalInterestIncurred {
          usdBalance
        }
        unpaidInterestIncurred {
          usdBalance
        }
      }
    }
  }
}
