mutation UserInitiateWithdrawalViaUsdtOnTron(
  $input: UserInitiateWithdrawalViaUsdtOnTronInput!
) {
  userInitiateWithdrawalViaUsdtOnTron(input: $input) {
    withdraw {
      id
      userId
    }
  }
}
