mutation UserInitiateWithdrawalViaUsdtOnTron(
  $input: UserInitiateWithdrawalViaUsdtOnTronInput!
) {
  userInitiateWithdrawalViaUsdtOnTron(input: $input) {
    user {
      userId
      balance {
        unallocatedCollateral {
          settled {
            btcBalance
          }
        }
        checking {
          settled {
            usdBalance
          }
          encumbrance {
            usdBalance
          }
        }
      }
    }
  }
}
