query me {
  me {
    userId
    btcDepositAddress
    ustDepositAddress
    email
    balance {
      unallocatedCollateral {
        settled {
          btcBalance
        }
      }
      checking {
        settled {
          usdBalance
        }
      }
    }
  }
}
