query me {
  me {
    customerId 
    applicantId
    status
    btcDepositAddress
    ustDepositAddress
    email
    level
    balance {
      unallocatedCollateral {
        settled {
          btcBalance
        }
      }
      checking {
        settled {
          usdBalance
        }
      }
    }
  }
}
