mutation makeLoanPayment($input: FixedTermLoanRecordPaymentInput!) {
  fixedTermLoanRecordPayment(input: $input) {
    loan {
      loanId
      balance {
        collateral {
          btcBalance
        }
        outstanding {
          usdBalance
        }
        interestIncurred {
          usdBalance
        }
      }
    }
  }
}
