mutation UserTopupCollateral($input: UserTopupCollateralInput!) {
  userTopupCollateral(input: $input) {
    user {
      userId
      balance {
        unallocatedCollateral {
          settled {
            btcBalance
          }
        }
      }
    }
  }
}
