mutation userCreate($input: UserCreateInput!) {
  userCreate(input: $input) {
    user {
      userId
      bitfinexUsername
      btcDepositAddress
      ustDepositAddress
      balance {
        unallocatedCollateral {
          settled {
            btcBalance
          }
        }
        checking {
          settled {
            usdBalance
          }
        }
      }
    }
  }
}
