mutation UserWithdrawViaTether($input: UserWithdrawViaTetherInput!) {
  userWithdrawViaTether(input: $input) {
    user {
      userId
      balance {
        unallocatedCollateral {
          btcBalance
        }
        checking {
          usdBalance
        }
      }
    }
  }
}
