mutation UserWithdrawViaAch($input: UserWithdrawViaAchInput!) {
  userWithdrawViaAch(input: $input) {
    user {
      userId
      balance {
        unallocatedCollateral {
          btcBalance
        }
        checking {
          usdBalance
        }
      }
    }
  }
}
