mutation UserWithdrawViaUsdt($input: UserWithdrawViaUsdtInput!) {
  userWithdrawViaUsdt(input: $input) {
    user {
      userId
      balance {
        unallocatedCollateral {
          btcBalance
        }
        checking {
          usdBalance
        }
      }
    }
  }
}
