query CreditFacilityBalance(
  $journalId: UUID!
  $collateralId: UUID!
  $facilityId: UUID!
  $disbursedReceivableId: UUID!
  $interestReceivableId: UUID!
) {
  collateral: balance(
    journalId: $journalId
    accountId: $collateralId
    currency: "BTC"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  facility: balance(
    journalId: $journalId
    accountId: $facilityId
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  totalDisbursed: balance(
    journalId: $journalId
    accountId: $disbursedReceivableId
    currency: "USD"
  ) {
    settled {
      drBalance {
        units
        currency
      }
    }
  }
  disbursedReceivable: balance(
    journalId: $journalId
    accountId: $disbursedReceivableId
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  totalInterest: balance(
    journalId: $journalId
    accountId: $interestReceivableId
    currency: "USD"
  ) {
    settled {
      drBalance {
        units
        currency
      }
    }
  }
  interestReceivable: balance(
    journalId: $journalId
    accountId: $interestReceivableId
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
    pending {
      normalBalance {
        units
        currency
      }
    }
  }
}
