mutation CreateCustomerAccounts(
  $onBalanceSheetAccountId: UUID!
  $onBalanceSheetAccountCode: String!
  $onBalanceSheetAccountName: String!
  $customerCheckingControlAccountSetId: UUID!
) {
  onBalanceSheet: accountCreate(
    input: {
      accountId: $onBalanceSheetAccountId
      code: $onBalanceSheetAccountCode
      name: $onBalanceSheetAccountName
      accountSetIds: [$customerCheckingControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
}
