query LoanBalance(
  $journalId: UUID!
  $collateralId: UUID!
  $loanPrincipalReceivableId: UUID!
  $loanInterestReceivableId: UUID!
  $interestIncomeId: UUID!
) {
  collateral: balance(
    journalId: $journalId
    accountId: $collateralId
    currency: "BTC"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  loanPrincipalReceivable: balance(
    journalId: $journalId
    accountId: $loanPrincipalReceivableId
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  loanInterestReceivable: balance(
    journalId: $journalId
    accountId: $loanInterestReceivableId
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  interestIncome: balance(
    journalId: $journalId
    accountId: $interestIncomeId
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
}
