query ProfitAndLossStatement(
  $accountSetId: UUID!
  $journalId: UUID!
  $from: Timestamp!
  $until: Timestamp
) {
  accountSet(id: $accountSetId) {
    ...accountSetDetailsAndBalances
    categories: members(first: 10) {
      ...categoriesWithBalances
    }
  }
}

# 'categories' and 'accounts'

fragment categoriesWithBalances on AccountSetMemberConnection {
  edges {
    node {
      __typename
      ... on AccountSet {
        ...categoryAccountSetWithBalances
      }
      ... on Account {
        ...accountDetailsAndBalances
      }
    }
  }
}

fragment categoryAccountSetWithBalances on AccountSet {
  ...accountSetDetailsAndBalances
  accounts: members(first: 25, after: null) {
    ...accountsWithBalances
  }
}

fragment accountsWithBalances on AccountSetMemberConnection {
  pageInfo {
    startCursor
    endCursor
    hasNextPage
  }
  edges {
    cursor
    node {
      __typename
      ... on AccountSet {
        ...accountSetDetailsAndBalances
      }
      ... on Account {
        ...accountDetailsAndBalances
      }
    }
  }
}

# 'details' and 'balances'

fragment accountSetDetailsAndBalances on AccountSet {
  ...accountSetDetails
  ...accountSetBalances
}

fragment accountDetailsAndBalances on Account {
  ...accountDetails
  ...accountBalances
}

# 'balances'

fragment accountBalances on Account {
  btcBalances: balanceInRange(
    currency: "BTC"
    journalId: $journalId
    from: $from
    until: $until
  ) {
    ...rangedBalance
  }
  usdBalances: balanceInRange(
    currency: "USD"
    journalId: $journalId
    from: $from
    until: $until
  ) {
    ...rangedBalance
  }
}

fragment accountSetBalances on AccountSet {
  btcBalances: balanceInRange(
    currency: "BTC"
    journalId: $journalId
    from: $from
    until: $until
  ) {
    ...rangedBalance
  }
  usdBalances: balanceInRange(
    currency: "USD"
    journalId: $journalId
    from: $from
    until: $until
  ) {
    ...rangedBalance
  }
}

fragment rangedBalance on RangedBalance {
  start {
    ...balancesByLayer
  }
  end {
    ...balancesByLayer
  }
  diff {
    ...balancesByLayer
  }
}

fragment balancesByLayer on Balance {
  settled {
    ...balances
  }
  pending {
    ...balances
  }
  encumbrance {
    ...balances
  }
  allLayersAvailable: available(layer: ENCUMBRANCE) {
    ...balances
  }
}

fragment balances on BalanceAmount {
  normalBalance {
    units
    currency
  }
  drBalance {
    units
    currency
  }
  crBalance {
    units
    currency
  }
}

# account/account-set details

fragment accountSetDetails on AccountSet {
  accountSetId
  name
  normalBalanceType
  members(first: 1) {
    pageInfo {
      startCursor
    }
  }
}

fragment accountDetails on Account {
  accountId
  code
  name
  normalBalanceType
}
