mutation ApproveLoanTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "APPROVE_LOAN"
      description: "Payout principal."
      params: [
        {
          name: "loanPrincipalReceivableAccount"
          type: UUID
          description: "Loan amount-outstanding account ID."
        }
        {
          name: "checkingAccount"
          type: UUID
          description: "User Checking account ID."
        }
        {
          name: "principalAmount"
          type: DECIMAL
          description: "Amount of USD being issued for the loan."
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: "params.loanPrincipalReceivableAccount"
          units: "params.principalAmount"
          currency: "'USD'"
          entryType: "'APPROVE_LOAN_PRINCIPAL_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.checkingAccount"
          units: "params.principalAmount"
          currency: "'USD'"
          entryType: "'APPROVE_LOAN_PRINCIPAL_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostApproveLoanTransaction(
  $transactionId: UUID!
  $loanPrincipalReceivableAccount: UUID!
  $checkingAccount: UUID!
  $principalAmount: Decimal!
  $externalId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "APPROVE_LOAN"
      params: {
        loanPrincipalReceivableAccount: $loanPrincipalReceivableAccount
        checkingAccount: $checkingAccount
        principalAmount: $principalAmount
        externalId: $externalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
      createdAt
    }
  }
}
