mutation ApproveLoanTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "APPROVE_LOAN"
      description: "Move money from unallocated collateral to loan account."
      params: [
        {
          name: "unallocatedCollateralAccount"
          type: UUID
          description: "User Unallocated Collateral account ID."
        }
        {
          name: "loanCollateralAccount"
          type: UUID
          description: "Loan Collateral account ID."
        }
        {
          name: "loanOutstandingAccount"
          type: UUID
          description: "Loan amount-outstanding account ID."
        }
        {
          name: "checkingAccount"
          type: UUID
          description: "User Checking account ID."
        }
        {
          name: "collateralAmount"
          type: DECIMAL
          description: "Amount of BTC being put into the loan."
        }
        {
          name: "principalAmount"
          type: DECIMAL
          description: "Amount of USD being issued for the loan."
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: "params.unallocatedCollateralAccount"
          units: "params.collateralAmount"
          currency: "'BTC'"
          entryType: "'APPROVE_LOAN_COLLATERAL_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.loanCollateralAccount"
          units: "params.collateralAmount"
          currency: "'BTC'"
          entryType: "'APPROVE_LOAN_COLLATERAL_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.loanOutstandingAccount"
          units: "params.principalAmount"
          currency: "'USDT'"
          entryType: "'APPROVE_LOAN_PRINCIPAL_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.checkingAccount"
          units: "params.principalAmount"
          currency: "'USDT'"
          entryType: "'APPROVE_LOAN_PRINCIPAL_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostApproveLoanTransaction(
  $transactionId: UUID!
  $unallocatedCollateralAccount: UUID!
  $loanCollateralAccount: UUID!
  $loanOutstandingAccount: UUID!
  $checkingAccount: UUID!
  $collateralAmount: Decimal!
  $principalAmount: Decimal!
  $externalId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "APPROVE_LOAN"
      params: {
        unallocatedCollateralAccount: $unallocatedCollateralAccount
        loanCollateralAccount: $loanCollateralAccount
        loanOutstandingAccount: $loanOutstandingAccount
        checkingAccount: $checkingAccount
        collateralAmount: $collateralAmount
        principalAmount: $principalAmount
        externalId: $externalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
    }
  }
}
