mutation CancelWithdrawTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
  $bankUsdAccountId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "CANCEL_WITHDRAW"
      description: "Cancel a USD withdraw from the customer's checking account."
      params: [
        {
          name: "account"
          type: UUID
          description: "Customer's checking account ID."
        }
        {
          name: "amount"
          type: DECIMAL
          description: "Amount of USD being cancelled."
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "correlationId"
          type: STRING
          description: "Correlation ID for the transaction"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
        correlationId: "params.correlationId"
      }
      entries: [
        {
          accountId: $bankUsdAccountId
          units: "params.amount"
          currency: "'USD'"
          entryType: "'CANCEL_WITHDRAW_PENDING_DR'"
          direction: "CREDIT"
          layer: "PENDING"
        }
        {
          accountId: "params.account"
          units: "params.amount"
          currency: "'USD'"
          entryType: "'CANCEL_WITHDRAW_PENDING_CR'"
          direction: "DEBIT"
          layer: "PENDING"
        }
        {
          accountId: $bankUsdAccountId
          units: "params.amount"
          currency: "'USD'"
          entryType: "'CANCEL_WITHDRAW_SETTLED_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.account"
          units: "params.amount"
          currency: "'USD'"
          entryType: "'CANCEL_WITHDRAW_SETTLED_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostCancelWithdrawTransaction(
  $transactionId: UUID!
  $accountId: UUID!
  $amount: Decimal!
  $externalId: String!
  $correlationId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "CANCEL_WITHDRAW"
      params: {
        account: $accountId
        amount: $amount
        externalId: $externalId
        correlationId: $correlationId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
    }
  }
}
