mutation PostCompleteLoanTransaction(
  $paymentTransactionId: UUID!
  $collateralTransactionId: UUID!
  $checkingAccount: UUID!
  $loanPrincipalReceivableAccount: UUID!
  $loanInterestReceivableAccount: UUID!
  $loanCollateralAccount: UUID!
  $principalPaymentAmount: Decimal!
  $interestPaymentAmount: Decimal!
  $collateralAmount: Decimal!
  $paymentExternalId: String!
  $collateralExternalId: String!
) {
  recordPayment: transactionPost(
    input: {
      transactionId: $paymentTransactionId
      txTemplateCode: "RECORD_PAYMENT"
      params: {
        checkingAccount: $checkingAccount
        loanPrincipalReceivableAccount: $loanPrincipalReceivableAccount
        loanInterestReceivableAccount: $loanInterestReceivableAccount
        principalPaymentAmount: $principalPaymentAmount
        interestPaymentAmount: $interestPaymentAmount
        externalId: $paymentExternalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
      createdAt
    }
  }

  returnCollateral: transactionPost(
    input: {
      transactionId: $collateralTransactionId
      txTemplateCode: "REMOVE_COLLATERAL"
      params: {
        collateralAccount: $loanCollateralAccount
        collateralAmount: $collateralAmount
        externalId: $collateralExternalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
      createdAt
    }
  }
}
