mutation CompleteLoanTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "COMPLETE_LOAN"
      description: "Make final payment for loan and release collateral."
      params: [
        {
          name: "checkingAccount"
          type: UUID
          description: "User Checking account ID."
        }
        {
          name: "loanOutstandingAccount"
          type: UUID
          description: "Loan amount-outstanding account ID."
        }
        {
          name: "loanCollateralAccount"
          type: UUID
          description: "Loan Collateral account ID."
        }
        {
          name: "unallocatedCollateralAccount"
          type: UUID
          description: "User Unallocated Collateral account ID."
        }
        {
          name: "paymentAmount"
          type: DECIMAL
          description: "Amount of USD being paid against outstanding amount."
        }
        {
          name: "collateralAmount"
          type: DECIMAL
          description: "Amount of BTC being put into the loan."
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
      ]
      txInput: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: "params.checkingAccount"
          units: "params.paymentAmount"
          currency: "'USDT'"
          entryType: "'COMPLETE_LOAN_PAYMENT_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.loanOutstandingAccount"
          units: "params.paymentAmount"
          currency: "'USDT'"
          entryType: "'COMPLETE_LOAN_PAYMENT_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.loanCollateralAccount"
          units: "params.collateralAmount"
          currency: "'BTC'"
          entryType: "'COMPLETE_LOAN_COLLATERAL_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.unallocatedCollateralAccount"
          units: "params.collateralAmount"
          currency: "'BTC'"
          entryType: "'COMPLETE_LOAN_COLLATERAL_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostCompleteLoanTransaction(
  $transactionId: UUID!
  $checkingAccount: UUID!
  $loanOutstandingAccount: UUID!
  $unallocatedCollateralAccount: UUID!
  $loanCollateralAccount: UUID!
  $paymentAmount: Decimal!
  $collateralAmount: Decimal!
  $externalId: String!
) {
  postTransaction(
    input: {
      transactionId: $transactionId
      txTemplateCode: "COMPLETE_LOAN"
      params: {
        checkingAccount: $checkingAccount
        loanOutstandingAccount: $loanOutstandingAccount
        unallocatedCollateralAccount: $unallocatedCollateralAccount
        loanCollateralAccount: $loanCollateralAccount
        paymentAmount: $paymentAmount
        collateralAmount: $collateralAmount
        externalId: $externalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
    }
  }
}
