mutation ConfirmWithdrawTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
  $bankUsdAccountId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "CONFIRM_WITHDRAW"
      description: "Confirm a USD withdraw from the customers checking account."
      params: [
        {
          name: "account"
          type: UUID
          description: "Customers checking account ID."
        }
        {
          name: "amount"
          type: DECIMAL
          description: "Amount of USD being deposited."
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "correlationId"
          type: STRING
          description: "Correlation ID for the transaction"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
        correlationId: "params.correlationId"
      }
      entries: [
        {
          accountId: $bankUsdAccountId
          units: "params.amount"
          currency: "'USD'"
          entryType: "'CONFIRM_WITHDRAW_PENDING_DR'"
          direction: "CREDIT"
          layer: "PENDING"
        }
        {
          accountId: "params.account"
          units: "params.amount"
          currency: "'USD'"
          entryType: "'CONFIRM_WITHDRAW_PENDING_CR'"
          direction: "DEBIT"
          layer: "PENDING"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostConfirmWithdrawTransaction(
  $transactionId: UUID!
  $accountId: UUID!
  $amount: Decimal!
  $externalId: String!
  $correlationId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "CONFIRM_WITHDRAW"
      params: { account: $accountId, amount: $amount, externalId: $externalId, correlationId: $correlationId }
    }
  ) {
    transaction {
      transactionId
      correlationId
    }
  }
}
