mutation PledgeUnallocatedCollateralTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
  $assetAccountId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "PLEDGE_UNALLOCATED_COLLATERAL"
      description: "A transfer of BTC being pledged as collateral into the users unallocated collateral account."
      params: [
        {
          name: "account"
          type: UUID
          description: "Unallocated Collateral account ID."
        }
        {
          name: "amount"
          type: DECIMAL
          description: "Amount of BTC being pledged."
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
      ]
      txInput: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: $assetAccountId
          units: "params.amount"
          currency: "'BTC'"
          entryType: "'PLEDGE_UNALLOCATED_COLLATERAL_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.account"
          units: "params.amount"
          currency: "'BTC'"
          entryType: "'PLEDGE_UNALLOCATED_COLLATERAL_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostPledgeUnallocatedCollateralTransaction(
  $transactionId: UUID!
  $accountId: UUID!
  $amount: Decimal!
  $externalId: String!
) {
  postTransaction(
    input: {
      transactionId: $transactionId
      txTemplateCode: "PLEDGE_UNALLOCATED_COLLATERAL"
      params: { account: $accountId, amount: $amount, externalId: $externalId }
    }
  ) {
    transaction {
      transactionId
      correlationId
    }
  }
}
