mutation TopupUnallocatedCollateralTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
  $assetAccountId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "TOPUP_UNALLOCATED_COLLATERAL"
      description: "A transfer of BTC being pledged as collateral into the users unallocated collateral account."
      params: [
        { name: "account",
          type: UUID,
          description: "Unallocated Collateral account ID."
        }
        {
          name: "amount"
          type: DECIMAL
          description: "Amount of BTC being pledged."
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
      ]
      txInput: { journalId: $journalId, effective: "params.effective" }
      entries: [
        {
          accountId: $assetAccountId
          units: "params.amount"
          currency: "'BTC'"
          entryType: "'TOPUP_UNALLOCATED_COLLATERAL_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.account"
          units: "params.amount"
          currency: "'BTC'"
          entryType: "'TOPUP_UNALLOCATED_COLLATERAL_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}
