config {
  type: "operations",
  hasOutput: true,
  description: "Ready for export Regulatory Report persona.xml of norm NPB4-17"
}

CREATE OR REPLACE TABLE FUNCTION ${self()} (asof TIMESTAMP) AS (

SELECT
    LEFT(`nit_persona`, 14) AS `nit_persona`
  , LEFT(`dui`, 9) AS `dui`
  , LEFT(`primer_apellido`, 25) AS `primer_apellido`
  , LEFT(`segundo_apellido`, 25) AS `segundo_apellido`
  , LEFT(`apellido_casada`, 25) AS `apellido_casada`
  , LEFT(`primer_nombre`, 25) AS `primer_nombre`
  , LEFT(`segundo_nombre`, 25) AS `segundo_nombre`
  , LEFT(`nombre_sociedad`, 100) AS `nombre_sociedad`
  , LEFT(`tipo_persona`, 1) AS `tipo_persona`
  , LEFT(`tipo_relacion`, 1) AS `tipo_relacion`
  , LEFT(`tipo_identificador`, 1) AS `tipo_identificador`
  , LEFT(`nit_desactualizado`, 14) AS `nit_desactualizado`
  , LEFT(`residente`, 1) AS `residente`
  , LEFT(`giro_persona`, 6) AS `giro_persona`
  , LEFT(`tamano_empresa`, 2) AS `tamano_empresa`
  , LEFT(`tipo_empresa`, 1) AS `tipo_empresa`
  , FORMAT('%.2f', ROUND(`reserva`, 2)) AS `reserva`
  , LEFT(`categoria_riesgo`, 2) AS `categoria_riesgo`
  , LEFT(`numero_cliente`, 17) AS `numero_cliente`
  , LEFT(`id_alterno`, 20) AS `id_alterno`
  , LEFT(`tipo_id_alterno`, 2) AS `tipo_id_alterno`
  , FORMAT_DATE('%Y-%m-%d', CAST(`fecha_nacimiento` AS DATE)) AS `fecha_nacimiento`
  , CAST(`pais_residencia` AS STRING) AS `pais_residencia`
  , FORMAT('%.2f', ROUND(`riesgo_consolidado`, 2)) AS `riesgo_consolidado`
  , LEFT(`sexo_persona`, 1) AS `sexo_persona`
  , LEFT(`ocupación`, 3) AS `ocupación`
  , LEFT(`id_pais_origen`, 20) AS `id_pais_origen`
  , CAST(`nacionalidad` AS STRING) AS `nacionalidad`
  , LEFT(`nit_anterior`, 14) AS `nit_anterior`
  , LEFT(`tipo_ident_anterior`, 1) AS `tipo_ident_anterior`
  , LEFT(`municipio_residencia`, 4) AS `municipio_residencia`
  , CURRENT_TIMESTAMP() AS created_at
FROM
  ${ref("int_npb4_17_01_persona_xml_raw")}(asof)

);

CREATE OR REPLACE TABLE ${self()} AS (
	SELECT *
	FROM ${self()} (TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), DAY))
);
