config {
	type: "operations",
	hasOutput: true,
	description: "Ready for export Regulatory Report saldo_cuenta.xml of norm NPB4-16",
	tags : ["regulatory-report"],
}

CREATE OR REPLACE TABLE FUNCTION ${self()} (asof TIMESTAMP) AS (

	SELECT
		RIGHT(id_codigo_cuenta, 10) AS id_codigo_cuenta,
		LEFT(nom_cuenta, 80) AS nom_cuenta,
		FORMAT('%.2f', ROUND(valor, 2)) AS valor,

	FROM ${ref("int_npb4_16_01_saldo_cuenta_xml_raw")}(asof)

);

CREATE OR REPLACE TABLE ${self()} AS (
	SELECT *
	FROM ${self()} (TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), DAY))
);
