mutation RowInsert($tableName: String!, $insertId: String!, $rowData: JSON!) {
  bigQuery {
    rowInsert(input: {
      integrationId: "00000000-0000-0000-0000-000000000001"
      tableName: $tableName
      insertId: $insertId
      rowData: $rowData
    }) {
      integration {
        integrationId
      }
    }
  }
}
