FROM alpine:latest as load

RUN apk add github-cli
ARG GH_TOKEN
ENV GH_TOKEN ${GH_TOKEN}

ARG VERSION
ENV VERSION ${VERSION}
RUN mkdir lana-home && mkdir lana && cd lana \
  && gh release download --repo GaloyMoney/lana-bank ${VERSION}\
  && mv lana-cli-x86_64-unknown-linux-musl-${VERSION}.tar.gz lana-cli.tar.gz \
  && tar --strip-components=1 -xf lana-cli.tar.gz \
  && mv lana-cli /usr/local/bin && cd ../ && rm -rf ./lana

FROM gcr.io/distroless/static
  COPY --from=load /usr/local/bin/lana-cli /bin/lana-cli
  COPY --from=load --chown=1000:0 --chmod=755 /lana-home /lana
  USER 1000
  ARG VERSION
  ARG BUILDTIME
  ARG COMMITHASH
  ENV VERSION ${VERSION}
  ENV BUILDTIME ${BUILDTIME}
  ENV COMMITHASH ${COMMITHASH}
  ENV LANA_HOME /lana
  CMD ["lana-cli"]
