FROM alpine:latest as load

RUN apk add github-cli
ARG GH_TOKEN
ENV GH_TOKEN ${GH_TOKEN}

ARG VERSION
ENV VERSION ${VERSION}
RUN mkdir lava-home && mkdir lava && cd lava \
  && gh release download --repo GaloyMoney/lava-bank ${VERSION}\
  && mv lava-cli-x86_64-unknown-linux-musl-${VERSION}.tar.gz lava-core.tar.gz \
  && tar --strip-components=1 -xf lava-cli.tar.gz \
  && mv lava-cli /usr/local/bin && cd ../ && rm -rf ./lava

FROM gcr.io/distroless/static
  COPY --from=load /usr/local/bin/lava-cli /bin/lava-app
  COPY --from=load --chown=1000:0 --chmod=755 /lava-home /lava
  USER 1000
  ARG VERSION
  ARG BUILDTIME
  ARG COMMITHASH
  ENV VERSION ${VERSION}
  ENV BUILDTIME ${BUILDTIME}
  ENV COMMITHASH ${COMMITHASH}
  ENV LAVA_HOME /lava
  CMD ["lava-cli"]
