use crate::authorization::{PERMISSION_SET_APP_VIEWER, PERMISSION_SET_APP_WRITER};
use core_access::{PERMISSION_SET_ACCESS_VIEWER, PERMISSION_SET_ACCESS_WRITER};
use core_accounting::{PERMISSION_SET_ACCOUNTING_VIEWER, PERMISSION_SET_ACCOUNTING_WRITER};
use core_credit::{PERMISSION_SET_CREDIT_VIEWER, PERMISSION_SET_CREDIT_WRITER};
use core_customer::{PERMISSION_SET_CUSTOMER_VIEWER, PERMISSION_SET_CUSTOMER_WRITER};
use core_deposit::{PERMISSION_SET_DEPOSIT_VIEWER, PERMISSION_SET_DEPOSIT_WRITER};
use dashboard::PERMISSION_SET_DASHBOARD_VIEWER;
use governance::{PERMISSION_SET_GOVERNANCE_VIEWER, PERMISSION_SET_GOVERNANCE_WRITER};
use rbac_types::{ROLE_NAME_ACCOUNTANT, ROLE_NAME_ADMIN, ROLE_NAME_BANK_MANAGER};

const ADMIN_PERMISSION_SETS: &[&str] = &[
    PERMISSION_SET_ACCOUNTING_VIEWER,
    PERMISSION_SET_ACCOUNTING_WRITER,
    PERMISSION_SET_APP_VIEWER,
    PERMISSION_SET_APP_WRITER,
    PERMISSION_SET_CREDIT_VIEWER,
    PERMISSION_SET_CREDIT_WRITER,
    PERMISSION_SET_CUSTOMER_VIEWER,
    PERMISSION_SET_CUSTOMER_WRITER,
    PERMISSION_SET_DASHBOARD_VIEWER,
    PERMISSION_SET_DEPOSIT_VIEWER,
    PERMISSION_SET_DEPOSIT_WRITER,
    PERMISSION_SET_GOVERNANCE_VIEWER,
    PERMISSION_SET_GOVERNANCE_WRITER,
    PERMISSION_SET_ACCESS_VIEWER,
    PERMISSION_SET_ACCESS_WRITER,
];

const BANK_MANAGER_PERMISSION_SETS: &[&str] = &[
    PERMISSION_SET_ACCOUNTING_VIEWER,
    PERMISSION_SET_ACCOUNTING_WRITER,
    PERMISSION_SET_APP_VIEWER,
    PERMISSION_SET_APP_WRITER,
    PERMISSION_SET_CREDIT_VIEWER,
    PERMISSION_SET_CREDIT_WRITER,
    PERMISSION_SET_CUSTOMER_VIEWER,
    PERMISSION_SET_CUSTOMER_WRITER,
    PERMISSION_SET_DASHBOARD_VIEWER,
    PERMISSION_SET_DEPOSIT_VIEWER,
    PERMISSION_SET_DEPOSIT_WRITER,
    PERMISSION_SET_GOVERNANCE_VIEWER,
    PERMISSION_SET_GOVERNANCE_WRITER,
    PERMISSION_SET_ACCESS_VIEWER,
];

const ACCOUNTANT_PERMISSION_SETS: &[&str] = &[
    PERMISSION_SET_ACCOUNTING_VIEWER,
    PERMISSION_SET_ACCOUNTING_WRITER,
    PERMISSION_SET_APP_VIEWER,
    PERMISSION_SET_CREDIT_VIEWER,
    PERMISSION_SET_CUSTOMER_VIEWER,
    PERMISSION_SET_DASHBOARD_VIEWER,
    PERMISSION_SET_DEPOSIT_VIEWER,
    PERMISSION_SET_GOVERNANCE_VIEWER,
    PERMISSION_SET_ACCESS_VIEWER,
];

pub const PREDEFINED_ROLES: &[(&str, &[&str])] = &[
    (ROLE_NAME_ADMIN, ADMIN_PERMISSION_SETS),
    (ROLE_NAME_BANK_MANAGER, BANK_MANAGER_PERMISSION_SETS),
    (ROLE_NAME_ACCOUNTANT, ACCOUNTANT_PERMISSION_SETS),
];
