config {
	type: "table",
}

WITH actividades_economicas AS (

-- Sector agropecuario
-- Agricultura
    SELECT '10101' AS code, 'Cultivo de granos básicos' AS description UNION ALL
    SELECT '10102', 'Cultivo de verduras y legumbres' UNION ALL
    SELECT '10103', 'Cultivo de frutas y plantas cuyas hojas o frutos se utilizan para preparar bebidas (no incluye el cultivo de café)' UNION ALL
    SELECT '10104', 'Cultivo de café' UNION ALL
    SELECT '10105', 'Cultivo de caña de azúcar' UNION ALL
    SELECT '10106', 'Cultivo de algodón' UNION ALL
    SELECT '10107', 'Cultivo de plantas que dan materiales textiles' UNION ALL
    SELECT '10108', 'Cultivo de plantas y flores ornamentales' UNION ALL
    SELECT '10199', 'Otros cultivos agrícolas no clasificados previamente' UNION ALL
-- Ganadería
    SELECT '10201', 'Cría de ganado bovino y producción de leche y sus derivados' UNION ALL
    SELECT '10202', 'Porquerizas' UNION ALL
    SELECT '10203', 'Cría de ganado caballar, caprino y ovino' UNION ALL
-- Otras actividades agropecuarias
    SELECT '10301', 'Avicultura' UNION ALL
    SELECT '10302', 'Apicultura' UNION ALL
    SELECT '10303', 'Cría de otros animales (incluye la cunicultura); no incluye la avicultura ni la apicultura' UNION ALL
    SELECT '10304', 'Servicios de agricultura y ganaderos' UNION ALL
    SELECT '10305', 'Caza ordinaria y mediante trampas, repoblación de animales de caza (incluye servicios conexos)' UNION ALL
    SELECT '10306', 'Silvicultura, extracción de madera y servicios conexos' UNION ALL
    SELECT '10307', 'Pesca de altura, costera e interior' UNION ALL
    SELECT '10308', 'Explotación de criaderos de peces y granjas piscícolas (incluye servicios conexos)' UNION ALL
    SELECT '10309', 'Servicios a la pesca y a la piscicultura' UNION ALL
-- Explotación de minas y canteras
-- Extracción de minerales no metálicos y metálicos
    SELECT '20101', 'Extracción de sal' UNION ALL
    SELECT '20102', 'Extracción de piedra, arena y arcilla' UNION ALL
    SELECT '20103', 'Extracción de oro y plata' UNION ALL
    SELECT '20104', 'Explotación de otras minas y canteras no clasificadas previamente' UNION ALL
    SELECT '20105', 'Servicios directos del sector minero' UNION ALL
-- Industrias manufactureras
-- Productos alimenticios (excepto bebidas)
    SELECT '30101', 'Elaboración y conservación de carnes (incluye mataderos)' UNION ALL
    SELECT '30102', 'Elaboración y conservación de pescado, crustáceos y otros productos marinos' UNION ALL
    SELECT '30103', 'Elaboración y conservación de frutas, verduras y legumbres' UNION ALL
    SELECT '30104', 'Fabricación de aceites y grasas vegetales y animales' UNION ALL
    SELECT '30105', 'Elaboración de productos lácteos y similares' UNION ALL
    SELECT '30106', 'Elaboración de productos de molinería' UNION ALL
    SELECT '30107', 'Beneficiado de café' UNION ALL
    SELECT '30108', 'Elaboración de productos de café (incluye el tostado)' UNION ALL
    SELECT '30109', 'Elaboración de almidones' UNION ALL
    SELECT '30110', 'Elaboración de productos de panadería' UNION ALL
    SELECT '30111', 'Elaboración de pastas alimenticias' UNION ALL
    SELECT '30112', 'Fabricación y refinado de azúcar' UNION ALL
    SELECT '30113', 'Elaboración de cacao, chocolate y productos de confitería' UNION ALL
    SELECT '30114', 'Elaboración de alimentos preparados para animales' UNION ALL
    SELECT '30199', 'Elaboración de otros productos alimenticios no clasificados previamente' UNION ALL
-- Bebidas y tabaco
    SELECT '30201', 'Destilación, rectificación y mezcla de bebidas alcohólicas' UNION ALL
    SELECT '30202', 'Elaboración de vinos' UNION ALL
    SELECT '30203', 'Elaboración de bebidas malteadas y de malta' UNION ALL
    SELECT '30204', 'Elaboración de bebidas no alcohólicas' UNION ALL
    SELECT '30205', 'Elaboración de productos de tabaco' UNION ALL
-- Textiles, prendas de vestir y cuero
    SELECT '30301', 'Hilados, tejido y acabado de materiales textiles' UNION ALL
    SELECT '30302', 'Acabado de materiales textiles no producidos en la misma empresa' UNION ALL
    SELECT '30303', 'Confección de materiales textiles no producidos en la misma fábrica (excepto prendas de vestir)' UNION ALL
    SELECT '30304', 'Fabricación de tapices y alfombras' UNION ALL
    SELECT '30305', 'Fabricación de cuerdas, cordeles, bramantes y redes' UNION ALL
    SELECT '30306', 'Fabricación de tejidos y artículos de punto y ganchillo' UNION ALL
    SELECT '30307', 'Fabricación de prendas de vestir (excepto prendas de piel)' UNION ALL
    SELECT '30308', 'Fabricación de otros productos textiles no clasificados previamente' UNION ALL
    SELECT '30309', 'Preparación, adobo y teñido de pieles; fabricación de artículos de piel (excepto calzado)' UNION ALL
    SELECT '30310', 'Curtido, adobo o preparación del cuero' UNION ALL
    SELECT '30311', 'Fabricación de artículos de cuero y sucedáneos del cuero (excepto el calzado y prendas de vestir)' UNION ALL
    SELECT '30312', 'Fabricación de calzado y sus partes' UNION ALL
-- Industrias de madera, corcho y papel
    SELECT '30401', 'Producción de madera' UNION ALL
    SELECT '30402', 'Fabricación de productos de madera y corcho (excepto muebles)' UNION ALL
    SELECT '30403', 'Fabricación de artículos de paja y materiales trenzables' UNION ALL
    SELECT '30404', 'Fabricación de pasta de madera, papel y cartón' UNION ALL
    SELECT '30405', 'Fabricación de productos diversos de papel y cartón' UNION ALL
    SELECT '30406', 'Edición de libros, periódicos, revistas y otras publicaciones' UNION ALL
    SELECT '30407', 'Actividades de impresión' UNION ALL
    SELECT '30408', 'Actividades de servicios relacionados con la impresión' UNION ALL
    SELECT '30409', 'Reproducción de grabaciones' UNION ALL
-- Fabricación de sustancias químicas
    SELECT '30501', 'Fabricación de sustancias químicas básicas (excepto abonos y compuestos de nitrógeno)' UNION ALL
    SELECT '30502', 'Fabricación de abonos y compuestos de nitrógeno' UNION ALL
    SELECT '30503', 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario' UNION ALL
    SELECT '30504', 'Fabricación de productos de la refinación del petróleo' UNION ALL
    SELECT '30505', 'Fabricación de plástico en formas primarias y de caucho sintético' UNION ALL
    SELECT '30506', 'Fabricación de productos de plástico y caucho' UNION ALL
    SELECT '30507', 'Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masillas' UNION ALL
    SELECT '30508', 'Fabricación de productos farmacéuticos y medicamentos' UNION ALL
    SELECT '30509', 'Fabricación de jabones y detergentes preparados para limpiar y pulir, perfumes, cosméticos y otros productos de tocador' UNION ALL
    SELECT '30510', 'Fabricación de productos pirotécnicos' UNION ALL
    SELECT '30511', 'Fabricación de otros productos químicos no clasificados previamente' UNION ALL
-- Fabricación de productos minerales no metálicos
    SELECT '30601', 'Fabricación de vidrio y productos de vidrio' UNION ALL
    SELECT '30602', 'Fabricación de productos de cerámica para uso no estructural' UNION ALL
    SELECT '30603', 'Fabricación de productos de cerámica para la construcción y metalurgia' UNION ALL
    SELECT '30604', 'Fabricación de cemento, cal y yeso' UNION ALL
    SELECT '30605', 'Fabricación de artículos de hormigón, crisotilo, cemento y yeso' UNION ALL
    SELECT '30606', 'Corte, tallado y acabado de la piedra, incluye mármol y piedra para la construcción' UNION ALL
    SELECT '30699', 'Fabricación de otros productos minerales no metálicos no clasificados previamente' UNION ALL
-- Fabricación de productos minerales metálicos
    SELECT '30701', 'Industrias básicas de hierro y acero' UNION ALL
    SELECT '30702', 'Fabricación de productos primarios de metales preciosos y metales no ferrosos' UNION ALL
    SELECT '30703', 'Fabricación de productos metálicos para uso estructural' UNION ALL
    SELECT '30704', 'Tratamiento y revestimiento de metales' UNION ALL
    SELECT '30705', 'Fabricación de artículos de cuchillería, herramientas manuales y otros artículos de ferretería' UNION ALL
    SELECT '30799', 'Fabricación de otros productos elaborados de metal, no clasificados previamente' UNION ALL
-- Fabricación de maquinaria, aparatos, accesorios y suministros
    SELECT '30801', 'Fabricación de motores y turbinas (excepto motores para aeronaves), vehículos automotores y motocicletas' UNION ALL
    SELECT '30802', 'Fabricación de bombas, compresores, grifos y válvulas' UNION ALL
    SELECT '30803', 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión' UNION ALL
    SELECT '30804', 'Fabricación de hornos, hogares y quemadores' UNION ALL
    SELECT '30805', 'Fabricación de equipo de elevación y manipulación' UNION ALL
    SELECT '30806', 'Fabricación de otros tipos de maquinaria de uso general no clasificados previamente' UNION ALL
    SELECT '30807', 'Fabricación de maquinaria de uso especial' UNION ALL
    SELECT '30808', 'Fabricación de aparatos de uso doméstico' UNION ALL
    SELECT '30809', 'Fabricación de receptores de radio y televisión, aparatos de grabación y reproducción de sonido y video y productos conexos' UNION ALL
    SELECT '30810', 'Fabricación de equipos y aparatos de radio, televisión y comunicaciones no clasificados previamente' UNION ALL
    SELECT '30811', 'Fabricación de maquinaria de oficina, contabilidad e informática' UNION ALL
    SELECT '30812', 'Fabricación de acumuladores de pilas y baterías primarias' UNION ALL
    SELECT '30813', 'Fabricación de lámparas eléctricas y equipo de iluminación' UNION ALL
    SELECT '30814', 'Fabricación de otros tipos de equipo eléctrico no clasificados previamente' UNION ALL
-- Fabricación de equipos de transporte
    SELECT '30901', 'Fabricación y/o ensamble de vehículos automotores' UNION ALL
    SELECT '30902', 'Fabricación de carrocerías para vehículos automotores, fabricación de remolques y semirremolques' UNION ALL
    SELECT '30903', 'Fabricación de partes, piezas y accesorios para vehículos automotores y sus motores' UNION ALL
    SELECT '30904', 'Construcción y reparación de embarcaciones' UNION ALL
    SELECT '30905', 'Fabricación de locomotoras y de material rodante para ferrocarriles y tranvías' UNION ALL
    SELECT '30906', 'Fabricación de aeronaves' UNION ALL
    SELECT '30907', 'Fabricación de motocicletas' UNION ALL
    SELECT '30908', 'Fabricación de bicicletas' UNION ALL
    SELECT '30999', 'Fabricación de otros equipos de transporte no clasificados previamente' UNION ALL
-- Otras manufacturas
    SELECT '39901', 'Fabricación de muebles de todo tipo de material' UNION ALL
    SELECT '39902', 'Fabricación de joyas y artículos conexos' UNION ALL
    SELECT '39903', 'Fabricación aparatos e instrumentos médicos quirúrgicos y ortopédicos y aparatos para medir, verificar, ensayar, navegar y otros fines (excepto instrumentos de óptica)' UNION ALL
    SELECT '39904', 'Fabricación de instrumentos de óptica y equipo fotográfico' UNION ALL
    SELECT '39905', 'Fabricación de relojes' UNION ALL
    SELECT '39906', 'Fabricación de instrumentos de música' UNION ALL
    SELECT '39907', 'Fabricación de artículos y equipo para deporte (excluye prenda de vestir)' UNION ALL
    SELECT '39908', 'Fabricación de juegos y juguetes' UNION ALL
    SELECT '39999', 'Otras industrias manufactureras no clasificadas previamente' UNION ALL
-- Electricidad, gas y agua
-- Luz y fuerza eléctrica
    SELECT '40101', 'Generación y distribución de energía eléctrica' UNION ALL
-- Producción de gas
    SELECT '40201', 'Fabricación de gas; distribución de combustibles gaseosos por tuberías' UNION ALL
-- Suministros de agua
    SELECT '40301', 'Captación, depuración y distribución de agua' UNION ALL
-- Construcción
    SELECT '50101', 'Preparación de terrenos' UNION ALL
    SELECT '50102', 'Construcción de casas y edificios' UNION ALL
    SELECT '50103', 'Construcción de obras de ingeniería civil' UNION ALL
    SELECT '50104', 'Acondicionamiento y acabado de edificaciones' UNION ALL
    SELECT '50105', 'Alquiler de equipo de construcción y demolición dotado de operarios' UNION ALL
-- Comercio
-- Comercio al por mayor y al por menor
    SELECT '60101', 'Venta de granos básicos y azúcar' UNION ALL
    SELECT '60102', 'Venta de frutas y verduras' UNION ALL
    SELECT '60103', 'Venta de flores y plantas ornamentales' UNION ALL
    SELECT '60104', 'Venta de café oro y uva' UNION ALL
    SELECT '60105', 'Venta de algodón oro o en pacas' UNION ALL
    SELECT '60106', 'Venta de productos agrícolas' UNION ALL
    SELECT '60107', 'Venta de ganado' UNION ALL
    SELECT '60108', 'Venta de otras especies vivas del reino animal' UNION ALL
    SELECT '60109', 'Venta de leña y carbón' UNION ALL
    SELECT '60110', 'Venta de carnes y productos cárnicos' UNION ALL
    SELECT '60111', 'Venta de productos lácteos' UNION ALL
    SELECT '60112', 'Venta de huevos' UNION ALL
    SELECT '60113', 'Venta de productos farináceos y de panadería' UNION ALL
    SELECT '60114', 'Venta de otros productos alimenticios no clasificados previamente (no incluye bebidas)' UNION ALL
    SELECT '60115', 'Venta de bebidas no alcohólicas, para su consumo fuera del establecimiento' UNION ALL
    SELECT '60116', 'Ventas de bebidas alcohólicas, para su consumo fuera del establecimiento' UNION ALL
    SELECT '60117', 'Venta de productos textiles y prendas de vestir' UNION ALL
    SELECT '60118', 'Venta de calzado' UNION ALL
    SELECT '60119', 'Venta de productos de peletería, marroquinería, talabartería y guarnicionería' UNION ALL
    SELECT '60120', 'Venta de madera y sus productos' UNION ALL
    SELECT '60121', 'Venta de papel, cartón, libros, revistas y útiles escolares y de escritorio' UNION ALL
    SELECT '60122', 'Venta de productos para uso agropecuario' UNION ALL
    SELECT '60123', 'Venta de combustibles y lubricantes' UNION ALL
    SELECT '60124', 'Venta de productos farmacéuticos y medicinales' UNION ALL
    SELECT '60125', 'Venta de productos de uso personal, perfumería, cosméticos, artículos de tocador, adornos y productos para limpieza' UNION ALL
    SELECT '60126', 'Venta de productos pirotécnicos' UNION ALL
    SELECT '60127', 'Venta de artículos de ferretería, de materiales y accesorios para la construcción (incluye pinturas y productos conexos)' UNION ALL
    SELECT '60128', 'Venta de enseres domésticos como cubiertos, vajillas, cristalería, objetos de porcelana y cerámica (incluye artículos de iluminación)' UNION ALL
    SELECT '60129', 'Venta al por mayor de instrumentos de óptica' UNION ALL
    SELECT '60130', 'Venta de equipo fotográfico y productos fotoquímicos.' UNION ALL
    SELECT '60131', 'Venta de relojería, relojes y joyería,' UNION ALL
    SELECT '60132', 'Venta de juegos, juguetes, artículos deportivos y otros productos de entretenimiento y esparcimiento' UNION ALL
    SELECT '60133', 'Venta a cuenta de terceros' UNION ALL
    SELECT '60134', 'Venta de desperdicios y desechos' UNION ALL
    SELECT '60135', 'Venta de artículos usados' UNION ALL
    SELECT '60136', 'Venta de instrumentos musicales y de equipos y aparatos conexos' UNION ALL
    SELECT '60137', 'Venta de productos diversos por correo' UNION ALL
    SELECT '60138', 'Venta de billetes de lotería, rifas, espectáculos y similares' UNION ALL
    SELECT '60139', 'Venta de vehículos automotores y motocicletas' UNION ALL
    SELECT '60140', 'Venta de partes, piezas y accesorios de vehículos automotores y motocicletas' UNION ALL
    SELECT '60141', 'Venta de maquinaria y equipo de uso general y especial; materiales conexos y sus repuestos' UNION ALL
    SELECT '60142', 'Venta de maquinaria y equipo de oficina, computadores y sus componentes (incluye software)' UNION ALL
    SELECT '60143', 'Venta de equipos e instrumentos de uso profesional y científico, y de aparatos de medida y control' UNION ALL
    SELECT '60144', 'Venta de muebles, electrodomésticos y otros enseres eléctricos y de comunicación' UNION ALL
    SELECT '60145', 'Venta de bicicletas y sus accesorios' UNION ALL
    SELECT '60146', 'Venta de establecimientos no especializados, con surtido compuesto principalmente de alimentos bebidas y tabaco (incluye supermercados)' UNION ALL
    SELECT '60147', 'Venta de otros productos en establecimientos no especializados' UNION ALL
    SELECT '60199', 'Venta de otros productos no clasificados previamente' UNION ALL
-- Hoteles, restaurantes y similares
-- Hoteles y similares
    SELECT '70101', 'Hoteles' UNION ALL
    SELECT '70102', 'Moteles y hospedajes' UNION ALL
    SELECT '70103', 'Centros vacacionales' UNION ALL
    SELECT '70199', 'Otros servicios de hospedaje, no clasificados previamente' UNION ALL
-- Restaurantes y similares
    SELECT '70201', 'Restaurantes' UNION ALL
    SELECT '70202', 'Comedores' UNION ALL
    SELECT '70203', 'Suministro de banquetes' UNION ALL
    SELECT '70204', 'Cafeterías y fruterías' UNION ALL
    SELECT '70205', 'Merenderos ambulantes' UNION ALL
    SELECT '70206', 'Suministro de bebidas alcohólicas para su consumo dentro del establecimiento' UNION ALL
    SELECT '70299', 'Otros establecimientos de comidas y bebidas no clasificados previamente' UNION ALL
-- Transporte, almacenamiento y comunicaciones
-- Transporte y servicios conexos
    SELECT '80101', 'Transporte colectivo de pasajeros a través de autobuses' UNION ALL
    SELECT '80102', 'Transporte colectivo de pasajeros a través de microbuses' UNION ALL
    SELECT '80103', 'Transporte colectivo de pasajeros a través de pick-ups' UNION ALL
    SELECT '80104', 'Transporte de personal' UNION ALL
    SELECT '80105', 'Alquiler de vehículos comerciales con conductor (incluye taxis)' UNION ALL
    SELECT '80106', 'Transporte de carga' UNION ALL
    SELECT '80107', 'Transporte ferroviario' UNION ALL
    SELECT '80108', 'Transporte por vía acuática' UNION ALL
    SELECT '80109', 'Transporte aéreo' UNION ALL
    SELECT '80110', 'Alquiler de aeronaves con tripulación' UNION ALL
    SELECT '80111', 'Terminales de transporte' UNION ALL
    SELECT '80112', 'Estacionamiento de automóviles' UNION ALL
    SELECT '80113', 'Servicios de carga y descarga' UNION ALL
    SELECT '80114', 'Actividades de agencias de viajes' UNION ALL
    SELECT '80115', 'Otras actividades relacionadas con el transporte (incluyendo tramitaciones de aduana)' UNION ALL
-- Almacenaje
    SELECT '80201', 'Almacenamiento y depósito (excluye almacenes generales de depósito)' UNION ALL
-- Comunicaciones
    SELECT '80301', 'Servicios de correo, envíos y otros similares' UNION ALL
    SELECT '80302', 'Servicios de telefonía y telegrafía' UNION ALL
    SELECT '80303', 'Servicios de televisión (incluye televisión por cable)' UNION ALL
    SELECT '80304', 'Servicios de radiodifusión' UNION ALL
    SELECT '80305', 'Servicios de transmisión de datos' UNION ALL
    SELECT '80399', 'Otros servicios de telecomunicaciones' UNION ALL
-- Establecimientos financieros, seguros y bienes raíces
-- Actividades financieras y servicios auxiliares de la intermediación financiera
    SELECT '90101', 'Bancos' UNION ALL
    SELECT '90102', 'Instituciones de ahorro y crédito' UNION ALL
    SELECT '90103', 'Cooperativas de ahorro y crédito' UNION ALL
    SELECT '90104', 'Entidades financieras dedicadas a la transferencia de fondos y al servicio de tarjetas de crédito y débito' UNION ALL
    SELECT '90105', 'Compra de cartera e inversión financiera' UNION ALL
    SELECT '90106', 'Casas de cambio' UNION ALL
    SELECT '90107', 'Bolsas, comisionistas de bolsas y corredores de valores' UNION ALL
    SELECT '90108', 'Fondos mutuos y fondos mutuos de inversión' UNION ALL
    SELECT '90109', 'Almacenes generales de depósito' UNION ALL
    SELECT '90110', 'Fiduciarias' UNION ALL
    SELECT '90111', 'Sociedades de capitalización' UNION ALL
    SELECT '90199', 'Otros tipos de intermediación financiera o de actividades auxiliares no clasificadas previamente' UNION ALL
-- Seguros
    SELECT '90201', 'Seguros en general' UNION ALL
    SELECT '90202', 'Agentes corredores de seguros' UNION ALL
    SELECT '90203', 'Peritos, tasadores, actuarios y liquidadores de siniestros' UNION ALL
    SELECT '90204', 'Administradores de fondos de pensiones' UNION ALL
    SELECT '90299', 'Otras actividades de seguros no clasificadas previamente' UNION ALL
-- Bienes y raíces
    SELECT '90301', 'Actividades inmobiliarias realizadas con bienes propios o arrendados' UNION ALL
    SELECT '90302', 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrato' UNION ALL
-- Servicios
-- Servicios enfocados principalmente hacia empresas
    SELECT '100101', 'Alquiler de equipo de transporte sin operario' UNION ALL
    SELECT '100102', 'Alquiler de otros tipos de maquinaria y equipo sin operario' UNION ALL
    SELECT '100103', 'Consultores de equipo y programas de informática' UNION ALL
    SELECT '100104', 'Procesamiento de datos y actividades relacionadas con base de datos' UNION ALL
    SELECT '100105', 'Investigaciones científicas' UNION ALL
    SELECT '100106', 'Actividades jurídicas y notariales' UNION ALL
    SELECT '100107', 'Actividades de contabilidad, teneduría de libros y auditoría, asesoramiento en materia de impuestos' UNION ALL
    SELECT '100108', 'Investigación de mercados y realización de encuestas de opinión pública' UNION ALL
    SELECT '100109', 'Actividades de asesoramiento empresarial y en materia de gestión (incluye la obtención y dotación de personal)' UNION ALL
    SELECT '100110', 'Actividades de arquitectura e ingeniería y actividades conexas de asesoramiento técnico' UNION ALL
    SELECT '100111', 'Ensayos y análisis técnicos' UNION ALL
    SELECT '100112', 'Publicidad' UNION ALL
    SELECT '100113', 'Actividades de investigación y seguridad' UNION ALL
    SELECT '100114', 'Actividades de limpieza de edificaciones (incluye la desinfección)' UNION ALL
    SELECT '100115', 'Actividades de fotografía' UNION ALL
    SELECT '100116', 'Actividades de envase y empaque' UNION ALL
    SELECT '100117', 'Actividades de fotocopias y de servicios eventuales' UNION ALL
    SELECT '100199', 'Otros servicios a empresas no clasificadas previamente' UNION ALL
-- Otros servicios
    SELECT '100201', 'Alquiler de efectos personales y enseres domésticos de todo tipo (incluye alquiler al público de videocintas) y otros no clasificados previamente' UNION ALL
    SELECT '100202', 'Enseñanza formal' UNION ALL
    SELECT '100203', 'Enseñanza no formal' UNION ALL
    SELECT '100204', 'Servicios hospitalarios' UNION ALL
    SELECT '100205', 'Servicios médicos' UNION ALL
    SELECT '100206', 'Servicios odontológicos' UNION ALL
    SELECT '100207', 'Laboratorios clínicos, radiología y asimilados' UNION ALL
    SELECT '100208', 'Otros servicios relacionados con la salud humana no clasificados previamente' UNION ALL
    SELECT '100209', 'Servicios veterinarios' UNION ALL
    SELECT '100210', 'Producción, distribución y exhibición de filmes y videocintas' UNION ALL
    SELECT '100211', 'Actividades de radio y televisión' UNION ALL
    SELECT '100212', 'Actividades de grabación y reproducción de discos' UNION ALL
    SELECT '100213', 'Actividades de discotecas, salas de bailes, parques de diversión y centros similares' UNION ALL
    SELECT '100214', 'Juegos electrónicos' UNION ALL
    SELECT '100215', 'Actividades teatrales, musicales y otras actividades artísticas' UNION ALL
    SELECT '100216', 'Empresarios y representantes de artistas nacionales y extranjeros' UNION ALL
    SELECT '100217', 'Actividades deportivas profesionales' UNION ALL
    SELECT '100218', 'Gimnasios' UNION ALL
    SELECT '100219', 'Actividades de agencias de noticias' UNION ALL
    SELECT '100220', 'Actividades de bibliotecas, archivos, museos y otras actividades culturales' UNION ALL
    SELECT '100221', 'Otras actividades de entretenimiento y esparcimiento no clasificadas previamente' UNION ALL
    SELECT '100222', 'Lavado y limpieza de telas, prendas de tela y piel (incluso la limpieza en seco), lavado de alfombras y tapices' UNION ALL
    SELECT '100223', 'Lavado de automóviles' UNION ALL
    SELECT '100224', 'Mantenimiento y reparación automotriz' UNION ALL
    SELECT '100225', 'Reconstrucción y reparación de piezas automotrices' UNION ALL
    SELECT '100226', 'Enderezado y pintura de vehículos y servicios conexos' UNION ALL
    SELECT '100227', 'Reparación eléctrica de vehículos' UNION ALL
    SELECT '100228', 'Reparación de radiadores y escapes' UNION ALL
    SELECT '100229', 'Reparación de llantas para vehículos' UNION ALL
    SELECT '100230', 'Remolque de automóviles' UNION ALL
    SELECT '100231', 'Mantenimiento y reparación de maquinaria de oficina, contabilidad e informática' UNION ALL
    SELECT '100232', 'Otros servicios de reparación no clasificados previamente' UNION ALL
    SELECT '100233', 'Peluquería y otros tratamientos de belleza' UNION ALL
    SELECT '100234', 'Saunas, baños turcos, masajes y similares' UNION ALL
    SELECT '100235', 'Pompas fúnebres y actividades conexas' UNION ALL
    SELECT '100299', 'Otras actividades de servicios no clasificados previamente' UNION ALL
-- Actividades no bien especificadas, administración pública, organismos no gubernamentales e instituciones foráneas
-- Administración pública
    SELECT '110101', 'Gobierno central' UNION ALL
    SELECT '110102', 'Administración de justicia y legislación' UNION ALL
    SELECT '110103', 'Instituciones de la seguridad social' UNION ALL
    SELECT '110104', 'Otras instituciones públicas' UNION ALL
    SELECT '110105', 'Alcaldías municipales' UNION ALL
-- Organismos no gubernamentales
    SELECT '110201', 'Organizaciones de asistencia social' UNION ALL
    SELECT '110202', 'Organizaciones de promoción del desarrollo económico' UNION ALL
    SELECT '110203', 'Organizaciones gremiales' UNION ALL
    SELECT '110204', 'Organizaciones sindicales' UNION ALL
    SELECT '110205', 'Organizaciones académicas, culturales y de opinión pública' UNION ALL
    SELECT '110206', 'Organizaciones religiosas' UNION ALL
    SELECT '110207', 'Organizaciones políticas' UNION ALL
    SELECT '110299', 'Otros tipos de organizaciones no clasificadas previamente' UNION ALL
-- Instituciones foráneas
    SELECT '110301', 'Representaciones diplomáticas y consulares' UNION ALL
    SELECT '110302', 'Organismos internacionales.' UNION ALL
-- Empleados y otras personas naturales
-- Empleados públicos y privados
    SELECT '120101', 'Empleados del sector público' UNION ALL
    SELECT '120102', 'Empleados del sector privado' UNION ALL
-- Otras personas naturales
    SELECT '120201', 'Otros trabajadores dependientes' UNION ALL
    SELECT '120202', 'Otras personas naturales'

)


SELECT
    code,
    description
FROM actividades_economicas
