config {
	type: "operations",
	hasOutput: true,
	description: "Este archivo almacena la información general de las garantías de depósitos pignorados, que respaldan una o más referencias crediticias.",
	dependencies: ["report_03_npb4_17_referencia_garantia_xml"],
}

CREATE OR REPLACE TABLE FUNCTION ${self()} (asof TIMESTAMP) AS (

	SELECT
		loan_id AS `identificacion_garantia`
		, customer_id AS `nit_depositante`
		, DATE(most_recent_collateral_deposit) AS `fecha_deposito`
		, CAST(NULL AS DATE) AS `fecha_vencimiento`
		, (total_collateral * (
			SELECT ANY_VALUE(usd_cents_per_btc HAVING MAX uploaded_at)
			FROM ${ref({
				name: "price_cents_btc",
				schema: envs.currentImportSchema
			})}
		) / 100) AS `valor_deposito`

	FROM ${ref("stg_approved_loans")}(asof)

)
