config {
	type: "table",
}

WITH sector_de_destino AS (

-- Agropecuario
-- Agricultura
    SELECT '010101' AS code, 'Cultivo del cafeto' AS description UNION ALL
    SELECT '010102', 'Cultivo de algodón' UNION ALL
    SELECT '010103', 'Cultivo de caña de azúcar' UNION ALL
    SELECT '010104', 'Cultivo de maíz para consumo' UNION ALL
    SELECT '010105', 'Cultivo de frijol bajo riego y secano' UNION ALL
    SELECT '010106', 'Cultivo de arroz bajo riego y secano' UNION ALL
    SELECT '010107', 'Cultivo de tabaco' UNION ALL
    SELECT '010108', 'Cultivo de fruta' UNION ALL
    SELECT '010109', 'Cultivo de maicillo' UNION ALL
    SELECT '010110', 'Cultivo de ajonjolí' UNION ALL
    SELECT '010111', 'Cultivo de henequén' UNION ALL
    SELECT '010112', 'Cultivo de kenaf' UNION ALL
    SELECT '010113', 'Cultivo de cacao' UNION ALL
    SELECT '010114', 'Cultivo de melón' UNION ALL
    SELECT '010115', 'Cultivo de brócoli' UNION ALL
    SELECT '010116', 'Cultivo de tomate' UNION ALL
    SELECT '010117', 'Cultivo de papa' UNION ALL
    SELECT '010118', 'Cultivo de pepino' UNION ALL
    SELECT '010119', 'Cultivo de chile dulce' UNION ALL
    SELECT '010120', 'Cultivo de cebolla' UNION ALL
    SELECT '010121', 'Cultivo de repollo' UNION ALL
    SELECT '010122', 'Cultivo de yuca' UNION ALL
    SELECT '010123', 'Cultivo de sandía' UNION ALL
    SELECT '010124', 'Cultivo de vigna' UNION ALL
    SELECT '010125', 'Cultivo de cacahuete' UNION ALL
    SELECT '010126', 'Cultivo de cardamomo' UNION ALL
    SELECT '010127', 'Cultivo de uva' UNION ALL
    SELECT '010128', 'Cultivo de soya' UNION ALL
    SELECT '010129', 'Cultivo de jojoba' UNION ALL
    SELECT '010130', 'Cultivo de sábila' UNION ALL
    SELECT '010131', 'Cultivo de okra' UNION ALL
    SELECT '010132', 'Cultivo de gandul' UNION ALL
    SELECT '010133', 'Cultivo de flores' UNION ALL
    SELECT '010134', 'Cultivo de maíz para semilla' UNION ALL
    SELECT '010135', 'Cultivo de arroz para semilla' UNION ALL
    SELECT '010136', 'Cultivo de maíz-maicillo asociados' UNION ALL
    SELECT '010137', 'Cultivo de coliflor' UNION ALL
    SELECT '010138', 'Cultivo de lechuga' UNION ALL
    SELECT '010139', 'Cultivo de remolacha' UNION ALL
    SELECT '010140', 'Cultivo de zanahoria' UNION ALL
    SELECT '010141', 'Cultivo de apio' UNION ALL
    SELECT '010142', 'Cultivo de otras verduras y legumbres' UNION ALL
    SELECT '010190', 'Cultivo de otros productos agrícolas' UNION ALL
-- Ganadería
    SELECT '010201', 'Crianza de ganado bovino' UNION ALL
    SELECT '010202', 'Crianza de ganado porcino' UNION ALL
    SELECT '010204', 'Crianza de ganado equino' UNION ALL
    SELECT '010290', 'Crianza de ganado no especificado' UNION ALL
    SELECT '010300', 'Avicultura' UNION ALL
    SELECT '010400', 'Silvicultura y extracción de madera' UNION ALL
-- Pesca y captura
    SELECT '010501', 'Pesca de altura' UNION ALL
    SELECT '010502', 'Cultivo de camarón de río' UNION ALL
    SELECT '010504', 'Pesca costera' UNION ALL
    SELECT '010505', 'Cultivo de peces' UNION ALL
    SELECT '010590', 'Pesca no especificada' UNION ALL
    SELECT '010600', 'Apicultura' UNION ALL
    SELECT '010700', 'Servicios agropecuarios' UNION ALL
    SELECT '010800', 'Cunicultura' UNION ALL
    SELECT '019501', 'Refinanciamiento al café' UNION ALL
    SELECT '019502', 'Refinanciamiento al algodón' UNION ALL
    SELECT '019503', 'Refinanciamiento a la caña de azúcar' UNION ALL
    SELECT '019504', 'Refinanciamiento cereales' UNION ALL
    SELECT '019512', 'Refinanciamiento a la ganadería' UNION ALL
    SELECT '019590', 'Otros refinanciamientos para destino agropecuario' UNION ALL
-- Sector minería y canteras
-- Minerales metálicos
    SELECT '020101', 'Oro y plata' UNION ALL
    SELECT '020190', 'Otros minerales metálicos' UNION ALL
-- Minerales no metálicos
    SELECT '020201', 'Extracción de piedra, arena y arcilla' UNION ALL
    SELECT '020202', 'Extracción de sal' UNION ALL
    SELECT '020203', 'Extracción de cal y yeso' UNION ALL
    SELECT '020290', 'Extracción de otros minerales no metálicos' UNION ALL
    SELECT '029500', 'Refinanciamiento al destino minería y canteras' UNION ALL
-- Industria manufacturera
-- Productos alimenticios
    SELECT '030101', 'Matanza de ganado, preparación y conservación de carnes' UNION ALL
    SELECT '030102', 'Elaboración de productos lácteos' UNION ALL
    SELECT '030103', 'Envase y conservación de frutas y legumbres' UNION ALL
    SELECT '030104', 'Envase y conservación de pescado y otros productos marinos' UNION ALL
    SELECT '030105', 'Manufactura de productos de molino y tostadurías de café' UNION ALL
    SELECT '030106', 'Elaboración de productos de panadería' UNION ALL
    SELECT '030107', 'Producción y refinación de azúcar' UNION ALL
    SELECT '030108', 'Fabricación de chocolates y confiterías' UNION ALL
    SELECT '030109', 'Fabricación de aceites y mantecas vegetales comestibles' UNION ALL
    SELECT '030110', 'Beneficiado de café' UNION ALL
    SELECT '030111', 'Fabricación de alimentos para animales' UNION ALL
    SELECT '030190', 'Industrias de productos alimenticios diversos' UNION ALL
-- Bebidas
    SELECT '030201', 'Destilación, rectificación y mezcla de bebidas espirituosas' UNION ALL
    SELECT '030202', 'Elaboración de vinos' UNION ALL
    SELECT '030203', 'Elaboración de cerveza y malta' UNION ALL
    SELECT '030204', 'Elaboración de bebidas no alcohólicas y gaseosas' UNION ALL
    SELECT '030300', 'Industria del tabaco' UNION ALL
-- Fabricación de productos textiles
    SELECT '030401', 'Fabricación de hilados, tejidos y acabados de textiles' UNION ALL
    SELECT '030402', 'Fabricación de tejidos de punto' UNION ALL
    SELECT '030403', 'Fabricación de sacos, cordel y jarcia' UNION ALL
    SELECT '030490', 'Fabricación de otros productos textiles' UNION ALL
-- Fabricación de calzado, vestuario y otros artículos confeccionados con textiles
    SELECT '030501', 'Fabricación de calzado' UNION ALL
    SELECT '030502', 'Fabricación de prendas de vestir' UNION ALL
    SELECT '030590', 'Otros artículos confeccionados de materiales textiles (excepto prendas de vestir)' UNION ALL
    SELECT '030600', 'Industria maderera' UNION ALL
    SELECT '030700', 'Fabricación de muebles y accesorios' UNION ALL
-- Fabricación de papel, cartón y productos de papel y cartón
    SELECT '030801', 'Fabricación de papel y cartón' UNION ALL
    SELECT '030802', 'Fabricación de productos de papel y cartón' UNION ALL
    SELECT '030900', 'Imprentas, editoriales e industrias conexas' UNION ALL
-- Industrias del cuero y productos de cuero
    SELECT '031001', 'Curtiembres y talleres de acabado' UNION ALL
    SELECT '031002', 'Fabricación de artículos de cuero' UNION ALL
-- Productos de caucho
    SELECT '031101', 'Fabricación de llantas y cámaras' UNION ALL
    SELECT '031102', 'Fabricación de otros productos de caucho' UNION ALL
-- Fabricación de productos químicos
    SELECT '031201', 'Fabricación de productos químicos industriales y abonos' UNION ALL
    SELECT '031202', 'Fabricación de aceites y grasas vegetales y animales' UNION ALL
    SELECT '031203', 'Fabricación de pinturas, barnices y lacas' UNION ALL
    SELECT '031290', 'Fabricación de productos químicos diversos' UNION ALL
    SELECT '031300', 'Fabricación de productos derivados del petróleo' UNION ALL
-- Fabricación de productos minerales no metálicos
    SELECT '031401', 'Fabricación de productos no metálicos para construcción' UNION ALL
    SELECT '031402', 'Fabricación de vidrio y productos de vidrio' UNION ALL
    SELECT '031403', 'Fabricación de objetos de barro, loza y porcelana' UNION ALL
    SELECT '031404', 'Fabricación de cemento' UNION ALL
    SELECT '031490', 'Fabricación de otros productos no metálicos' UNION ALL
    SELECT '031500', 'Fabricación de industrias metálicas básicas' UNION ALL
-- Fabricación de productos metálicos (excepto maquinaria y equipo de transporte)
    SELECT '031601', 'Fabricación de muebles y accesorios metálicos' UNION ALL
    SELECT '031602', 'Fabricación de productos metálicos estructurales' UNION ALL
    SELECT '031690', 'Fabricación de otros productos metálicos' UNION ALL
    SELECT '031700', 'Fabricación y ensamble de maquinaria excepto eléctrica' UNION ALL
    SELECT '031800', 'Fabricación y ensamble de maquinaria, aparatos, accesorios y artículos eléctricos' UNION ALL
    SELECT '031900', 'Fabricación de material de transporte' UNION ALL
-- Fabricación de productos plásticos
    SELECT '032001', 'Fabricación de productos de material plástico' UNION ALL
    SELECT '032002', 'Fabricación de juguetes de material plástico' UNION ALL
    SELECT '032003', 'Fabricación de carteras y bolsos de material plástico' UNION ALL
    SELECT '032090', 'Fabricación de otros productos de material plástico' UNION ALL
-- Fabricación de instrumentos de óptica
    SELECT '032101', 'Fabricación de lentes ópticos' UNION ALL
    SELECT '032190', 'Fabricación de otros instrumentos de óptica' UNION ALL
-- Industria de la maquila
    SELECT '032201', 'Maquila textil' UNION ALL
    SELECT '032202', 'Maquila electrónica' UNION ALL
-- Industrias manufactureras diversas
    SELECT '039001', 'Fabricación de productos pirotécnicos' UNION ALL
    SELECT '039002', 'Fabricación de artesanías' UNION ALL
    SELECT '039090', 'Manufacturas diversas' UNION ALL
    SELECT '039500', 'Refinanciamiento para destino industria manufacturera' UNION ALL
-- Construcción
-- Construcción de viviendas
    SELECT '040101', 'Construcción de viviendas y condominios habitacionales con financiamiento hasta ¢80,000.00' UNION ALL
    SELECT '040102', 'Construcción de viviendas y condominios habitacionales con financiamiento mayor de ¢80,000.00 hasta ¢150,000.00' UNION ALL
    SELECT '040103', 'Construcción de viviendas y condominios habitacionales con financiamiento mayor de ¢150,000.00 hasta ¢300,000.00' UNION ALL
    SELECT '040104', 'Construcción de viviendas y condominios habitacionales con financiamiento mayor de ¢300,000.00 hasta ¢600,000.00' UNION ALL
    SELECT '040105', 'Construcción de viviendas y condominios habitacionales con financiamiento mayor de ¢600,000.00 hasta ¢1,000,000.00' UNION ALL
    SELECT '040106', 'Construcción de viviendas y condominios habitacionales con financiamiento mayor de ¢1,000,000.00' UNION ALL
    SELECT '040200', 'Construcciones agropecuarias' UNION ALL
    SELECT '040300', 'Construcciones industriales' UNION ALL
    SELECT '040400', 'Construcción de edificios comerciales y de servicios' UNION ALL
    SELECT '040500', 'Construcción de hoteles y similares' UNION ALL
    SELECT '040600', 'Urbanización de terrenos' UNION ALL
    SELECT '040700', 'Ampliación y reparación de vivienda' UNION ALL
    SELECT '049000', 'Otras construcciones' UNION ALL
    SELECT '049500', 'Refinanciamiento destinado a la construcción' UNION ALL
-- Electricidad, gas, agua y servicios sanitarios
    SELECT '050100', 'Producción, transmisión y distribución de energía eléctrica' UNION ALL
    SELECT '050200', 'Producción y distribución de gas natural' UNION ALL
    SELECT '050300', 'Abastecimiento de agua' UNION ALL
    SELECT '050400', 'Servicios sanitarios' UNION ALL
    SELECT '059500', 'Refinanciamiento destinado para electricidad, gas, agua y servicios sanitarios' UNION ALL
-- Comercio
-- Importaciones para el destino comercio
    SELECT '060101', 'Financiamiento a la importación de maquinaria y equipo' UNION ALL
    SELECT '060102', 'Financiamiento a la importación de equipo de transporte para actividades productivas' UNION ALL
    SELECT '060103', 'Financiamiento a la importación de vehículos' UNION ALL
    SELECT '060104', 'Financiamiento a la importación de materias primas, productos semi-elaborados y otros insumos para la agricultura e industria' UNION ALL
    SELECT '060105', 'Financiamiento a la importación de productos alimenticios y medicinales' UNION ALL
    SELECT '060106', 'Financiamiento a la importación de productos textiles y prendas de vestir' UNION ALL
    SELECT '060107', 'Financiamiento a la importación de bebidas, tabaco, perfumes y cosméticos' UNION ALL
    SELECT '060108', 'Financiamiento a la importación de manufacturas de metal' UNION ALL
    SELECT '060109', 'Financiamiento a la importación de maquinaria, aparatos y utensilios eléctricos' UNION ALL
    SELECT '060110', 'Importaciones para destino agropecuario (para su comercialización)' UNION ALL
    SELECT '060120', 'Importaciones para destino minería y canteras (para su comercialización)' UNION ALL
    SELECT '060130', 'Importaciones para destino de la industria manufacturera (para su comercialización)' UNION ALL
    SELECT '060140', 'Importaciones para destino de la construcción (para su comercialización)' UNION ALL
    SELECT '060150', 'Importaciones para destino electricidad, gas natural, agua y servicios sanitarios (para su comercialización)' UNION ALL
    SELECT '060160', 'Importaciones para destino transporte, almacenaje y comunicaciones (para su comercialización)' UNION ALL
    SELECT '060170', 'Importaciones para destino servicios (para su comercialización)' UNION ALL
    SELECT '060190', 'Financiamiento a otras importaciones del comercio' UNION ALL
-- Comercio de exportación
    SELECT '060201', 'Financiamiento a la exportación de café' UNION ALL
    SELECT '060202', 'Financiamiento a la exportación de azúcar' UNION ALL
    SELECT '060203', 'Financiamiento a la exportación de pescado y marisco' UNION ALL
    SELECT '060204', 'Financiamiento a la exportación de otros productos alimenticios' UNION ALL
    SELECT '060205', 'Financiamiento a la exportación de algodón' UNION ALL
    SELECT '060206', 'Financiamiento a la exportación de hilazas y tejidos de algodón' UNION ALL
    SELECT '060207', 'Financiamiento a la exportación de artículos de vestuario' UNION ALL
    SELECT '060208', 'Financiamiento a la exportación de productos derivados del petróleo' UNION ALL
    SELECT '060209', 'Financiamiento a la exportación de productos químicos' UNION ALL
    SELECT '060210', 'Financiamiento a la exportación de productos metálicos (excepto maquinaria y equipo de transporte)' UNION ALL
    SELECT '060211', 'Financiamiento a la exportación de material de transporte' UNION ALL
    SELECT '060212', 'Financiamiento a la exportación de productos minerales no metálicos' UNION ALL
    SELECT '060213', 'Financiamiento a la exportación de productos de madera' UNION ALL
    SELECT '060214', 'Financiamiento a la exportación de bebidas' UNION ALL
    SELECT '060215', 'Financiamiento a la exportación de productos de cuero y caucho' UNION ALL
    SELECT '060216', 'Financiamiento a la exportación de papel y cartón y productos de papel y cartón' UNION ALL
    SELECT '060217', 'Financiamiento a la exportación de ganado' UNION ALL
    SELECT '060218', 'Financiamiento a la exportación de servicios' UNION ALL
    SELECT '060219', 'Financiamiento a la exportación de hilos, hilazas y tejidos de fibras artificiales o sintéticas' UNION ALL
    SELECT '060220', 'Financiamiento a la exportación de fibras y tejidos de fibras burdas y otros productos de fibras burdas' UNION ALL
    SELECT '060290', 'Financiamiento a otros productos de exportación' UNION ALL
-- Comercio interno
    SELECT '060301', 'Comercialización de productos industriales' UNION ALL
    SELECT '060303', 'Comercialización de productos agropecuarios' UNION ALL
    SELECT '060304', 'Comercialización de vehículos' UNION ALL
    SELECT '060305', 'Comercialización de productos nacionales (no especificados anteriormente)' UNION ALL
    SELECT '060306', 'Comercialización de aparatos eléctricos' UNION ALL
    SELECT '060307', 'Préstamos a supermercados, carnicerías y tiendas' UNION ALL
    SELECT '060308', 'Préstamos a droguerías o farmacias' UNION ALL
    SELECT '060309', 'Financiamiento para otras actividades comerciales' UNION ALL
    SELECT '060390', 'Comercialización de productos importados no especificados anteriormente' UNION ALL
-- Otras actividades comerciales
    SELECT '060407', 'Compra venta de bienes raíces' UNION ALL
    SELECT '069500', 'Refinanciamiento destinado al comercio' UNION ALL
-- Transporte, almacenaje y comunicaciones
-- Transporte
    SELECT '070101', 'Transporte de pasajeros o carga por ferrocarril' UNION ALL
    SELECT '070102', 'Transporte de pasajeros por autobuses' UNION ALL
    SELECT '070103', 'Transporte de pasajeros por taxis' UNION ALL
    SELECT '070104', 'Transporte de carga por carretera' UNION ALL
    SELECT '070105', 'Transporte aéreo' UNION ALL
    SELECT '070106', 'Agencias de turismo' UNION ALL
    SELECT '070107', 'Transporte de pasajeros y carga por vía marítima' UNION ALL
    SELECT '070108', 'Pasajes aéreos' UNION ALL
    SELECT '070200', 'Servicios de depósitos y almacenaje de mercaderías' UNION ALL
    SELECT '070300', 'Transporte de correo y telecomunicaciones' UNION ALL
    SELECT '079501', 'Refinanciamiento para destino transporte' UNION ALL
    SELECT '079502', 'Refinanciamiento para destino almacenaje' UNION ALL
    SELECT '079503', 'Refinanciamiento para destino comunicaciones' UNION ALL
-- Servicios
-- Establecimientos de enseñanza
    SELECT '080101', 'Establecimientos de enseñanza básica' UNION ALL
    SELECT '080102', 'Establecimientos de enseñanza media' UNION ALL
    SELECT '080103', 'Establecimientos de enseñanza superior' UNION ALL
    SELECT '080104', 'Establecimientos de formación técnica' UNION ALL
    SELECT '080190', 'Otros establecimientos de enseñanza' UNION ALL
    SELECT '080200', 'Servicios médicos y sanitarios' UNION ALL
    SELECT '080300', 'Servicios técnicos' UNION ALL
    SELECT '080400', 'Servicios de esparcimiento' UNION ALL
    SELECT '080500', 'Servicios de educación' UNION ALL
    SELECT '080600', 'Alquiler y arrendamiento de maquinaria y equipo' UNION ALL
-- Servicios personales diversos
    SELECT '089001', 'Restaurantes, cafés y similares' UNION ALL
    SELECT '089002', 'Hoteles, moteles y similares' UNION ALL
    SELECT '089003', 'Lavanderías, aplanchadurías y tintorerías' UNION ALL
    SELECT '089004', 'Otros servicios personales diversos' UNION ALL
    SELECT '089005', 'Talleres de reparaciones eléctricos' UNION ALL
    SELECT '089006', 'Talleres de reparaciones de vehículos de transporte colectivo y de carga' UNION ALL
    SELECT '089007', 'Talleres de reparaciones de automóviles y motocicletas' UNION ALL
    SELECT '089100', 'Otros servicios' UNION ALL
    SELECT '089500', 'Refinanciamiento para destino servicios' UNION ALL
-- Adquisición de vivienda
    SELECT '090001', 'Financiamiento para compra de viviendas y apartamentos con valor de hasta ¢80,000.00' UNION ALL
    SELECT '090002', 'Financiamiento para compra de viviendas y apartamentos mayores de ¢80,000.00 hasta ¢150,000.00' UNION ALL
    SELECT '090003', 'Financiamiento para compra de viviendas y apartamentos mayores de ¢150,000.00 hasta ¢300,000.00' UNION ALL
    SELECT '090004', 'Financiamiento para compra de viviendas y apartamentos mayores de ¢300,000.00 hasta ¢600,000.00' UNION ALL
    SELECT '090005', 'Financiamiento para compra de viviendas y apartamentos mayores de ¢600,000.00 hasta ¢1,000,000.00' UNION ALL
    SELECT '090006', 'Financiamiento para compra de viviendas y apartamentos mayores de ¢1,000,000.00' UNION ALL
    SELECT '090007', 'Financiamiento para la adquisición de lotes de terreno' UNION ALL
    SELECT '090099', 'Adquisición de otros locales' UNION ALL
    SELECT '099500', 'Refinanciamiento al sector vivienda' UNION ALL
-- Consumo
    SELECT '100001', 'Préstamos para adquisición de vehículo' UNION ALL
    SELECT '100002', 'Préstamos para gastos de viajes turísticos' UNION ALL
    SELECT '100003', 'Préstamos para tratamientos médicos y clínicos' UNION ALL
    SELECT '100004', 'Préstamos para consolidación y cancelación de deudas originadas por consumo' UNION ALL
    SELECT '100005', 'Préstamos para la compra de electrodomésticos' UNION ALL
    SELECT '100006', 'Préstamos para la compra de muebles' UNION ALL
    SELECT '100099', 'Otros préstamos destinados a la adquisición de bienes y servicios para el consumo personal' UNION ALL
    SELECT '109500', 'Refinanciamiento para destino consumo' UNION ALL
-- Instituciones financieras
    SELECT '110001', 'Créditos a bancos comerciales' UNION ALL
    SELECT '110002', 'Créditos a financieras' UNION ALL
    SELECT '110003', 'Créditos a casas de corredores' UNION ALL
    SELECT '110004', 'Créditos a compañías de seguros' UNION ALL
    SELECT '110005', 'Créditos a administradoras de fondos para pensiones' UNION ALL
    SELECT '110006', 'Crédito a otras instituciones financieras' UNION ALL
    SELECT '119500', 'Refinanciamiento para destino financiero' UNION ALL
-- Otras actividades
-- Títulos y acciones en cartera
    SELECT '120101', 'Financiamiento para la adquisición de títulos-valores emitidos por el gobierno central' UNION ALL
    SELECT '120102', 'Financiamiento para la adquisición de títulos-valores emitidos por EPNF' UNION ALL
    SELECT '120103', 'Financiamiento para la adquisición de títulos-valores de empresas privadas' UNION ALL
    SELECT '120200', 'Créditos para el pago de impuestos' UNION ALL
    SELECT '120099', 'Otros créditos no clasificados' UNION ALL
    SELECT '129500', 'Otros refinanciamientos'

)


SELECT
    code,
    description
FROM sector_de_destino
