config {
	type: "table",
}

WITH cargos_de_junta_directiva AS (

    SELECT '01' AS code, 'Presidente' AS description UNION ALL
    SELECT '02', 'Vice-presidente' UNION ALL
    SELECT '03', 'Secretario' UNION ALL
    SELECT '04', 'Directores propietarios' UNION ALL
    SELECT '05', 'Directores suplentes' UNION ALL
    SELECT '06', 'Tesorero' UNION ALL
    SELECT '07', 'Representante legal' UNION ALL
    SELECT '08', 'Administrador único' UNION ALL
    SELECT '09', 'Apoderado legal' UNION ALL
    SELECT '10', 'Alcalde' UNION ALL
    SELECT '11', 'Síndico' UNION ALL
    SELECT '12', 'Regidor'

)


SELECT
    code,
    description
FROM cargos_de_junta_directiva
