config {
	type: "table",
}

WITH lista_de_ocupaciones AS (

    SELECT '1' AS code, 'Administrador' AS description UNION ALL
    SELECT '2', 'Agente de aduana' UNION ALL
    SELECT '3', 'Agente de ventas' UNION ALL
    SELECT '4', 'Agricultor' UNION ALL
    SELECT '5', 'Agrónomo' UNION ALL
    SELECT '6', 'Albañil' UNION ALL
    SELECT '7', 'Ama de casa' UNION ALL
    SELECT '8', 'Analista de computación' UNION ALL
    SELECT '9', 'Apicultor' UNION ALL
    SELECT '10', 'Arquitecto' UNION ALL
    SELECT '11', 'Artesano' UNION ALL
    SELECT '12', 'Ascensorista' UNION ALL
    SELECT '13', 'Asistente de abogacía' UNION ALL
    SELECT '14', 'Asistente de auditoría' UNION ALL
    SELECT '15', 'Asistente de consultorio médico' UNION ALL
    SELECT '16', 'Asesor' UNION ALL
    SELECT '17', 'Auditor' UNION ALL
    SELECT '18', 'Auxiliar de contabilidad' UNION ALL
    SELECT '19', 'Auxiliar dental' UNION ALL
    SELECT '20', 'Auxiliar de cocina' UNION ALL
    SELECT '21', 'Ayudante de mecánico general' UNION ALL
    SELECT '22', 'Ayudante operario, construcción' UNION ALL
    SELECT '23', 'Bachiller' UNION ALL
    SELECT '24', 'Barbero' UNION ALL
    SELECT '25', 'Bartender' UNION ALL
    SELECT '26', 'Bodeguero' UNION ALL
    SELECT '27', 'Bombero' UNION ALL
    SELECT '28', 'Botones' UNION ALL
    SELECT '29', 'Cajero' UNION ALL
    SELECT '30', 'Camarógrafo de prensa' UNION ALL
    SELECT '31', 'Cantante de música' UNION ALL
    SELECT '32', 'Carnicero (destazador)' UNION ALL
    SELECT '33', 'Carpintero' UNION ALL
    SELECT '34', 'Catedrático' UNION ALL
    SELECT '35', 'Cerrajero' UNION ALL
    SELECT '36', 'Chequeador de buses' UNION ALL
    SELECT '37', 'Chofer de bus' UNION ALL
    SELECT '38', 'Chofer de tráiler' UNION ALL
    SELECT '39', 'Chofer de vehículo' UNION ALL
    SELECT '40', 'Cobrador' UNION ALL
    SELECT '41', 'Cocinero' UNION ALL
    SELECT '42', 'Comerciante' UNION ALL
    SELECT '43', 'Constructor' UNION ALL
    SELECT '44', 'Consultor' UNION ALL
    SELECT '45', 'Contador' UNION ALL
    SELECT '46', 'Corredor de seguros' UNION ALL
    SELECT '47', 'Cosmetóloga' UNION ALL
    SELECT '48', 'Costurera (modista)' UNION ALL
    SELECT '49', 'Dependiente de mostrador' UNION ALL
    SELECT '50', 'Despachador agencia de aduana' UNION ALL
    SELECT '51', 'Dibujante de artes gráficas' UNION ALL
    SELECT '52', 'Dibujante ingeniería, arquitectura' UNION ALL
    SELECT '53', 'Digitador' UNION ALL
    SELECT '54', 'Diputado' UNION ALL
    SELECT '55', 'Director centro educativo' UNION ALL
    SELECT '56', 'Diseñador' UNION ALL
    SELECT '57', 'Ebanista' UNION ALL
    SELECT '58', 'Electricista' UNION ALL
    SELECT '59', 'Empacador, etiquetador' UNION ALL
    SELECT '60', 'Empleada doméstica' UNION ALL
    SELECT '61', 'Empleado de despacho' UNION ALL
    SELECT '62', 'Empleado sector público' UNION ALL
    SELECT '63', 'Empresario' UNION ALL
    SELECT '64', 'Encargado indicar acomodo parqueo' UNION ALL
    SELECT '65', 'Encargado de limpieza en general' UNION ALL
    SELECT '66', 'Encargado limpieza en piscinas' UNION ALL
    SELECT '67', 'Encargado mantenimiento correctivo cómputo' UNION ALL
    SELECT '68', 'Encargado mantenimiento preventivo cómputo' UNION ALL
    SELECT '69', 'Encargado de poner discos (discjockey)' UNION ALL
    SELECT '70', 'Encargado de fotocopiadora' UNION ALL
    SELECT '71', 'Encargado mantenimiento edificio' UNION ALL
    SELECT '72', 'Encuadernador-empastador' UNION ALL
    SELECT '73', 'Encuestador' UNION ALL
    SELECT '74', 'Enderezador automotriz' UNION ALL
    SELECT '75', 'Engrasador de autos' UNION ALL
    SELECT '76', 'Ensamblador de computadoras' UNION ALL
    SELECT '77', 'Estampador en textil (serigrafía)' UNION ALL
    SELECT '78', 'Estilista' UNION ALL
    SELECT '79', 'Florista' UNION ALL
    SELECT '80', 'Fontanero' UNION ALL
    SELECT '81', 'Fotógrafo' UNION ALL
    SELECT '82', 'Fumigador' UNION ALL
    SELECT '83', 'Fundidor' UNION ALL
    SELECT '84', 'Guía turístico' UNION ALL
    SELECT '85', 'Hojalatero' UNION ALL
    SELECT '86', 'Horneador' UNION ALL
    SELECT '87', 'Ingeniero' UNION ALL
    SELECT '88', 'Instructor de bailes' UNION ALL
    SELECT '89', 'Jardinero' UNION ALL
    SELECT '90', 'Jefe de cocina (chef)' UNION ALL
    SELECT '91', 'Joyero' UNION ALL
    SELECT '92', 'Laboratorista clínico' UNION ALL
    SELECT '93', 'Lavador de baños, pisos, etc.' UNION ALL
    SELECT '94', 'Lavador de cabellos' UNION ALL
    SELECT '95', 'Lavador de carros' UNION ALL
    SELECT '96', 'Levantador de textos (artes gráficas)' UNION ALL
    SELECT '97', 'Locutor de radioemisora' UNION ALL
    SELECT '98', 'Locutor de televisión' UNION ALL
    SELECT '99', 'Llanteros' UNION ALL
    SELECT '100', 'Maestro' UNION ALL
    SELECT '101', 'Maestro de obras' UNION ALL
    SELECT '102', 'Mecánico' UNION ALL
    SELECT '103', 'Mecánico dental' UNION ALL
    SELECT '104', 'Mensajero' UNION ALL
    SELECT '105', 'Mesero' UNION ALL
    SELECT '106', 'Oficinista' UNION ALL
    SELECT '107', 'Operador de computación' UNION ALL
    SELECT '108', 'Operador de grúa estacionaria' UNION ALL
    SELECT '109', 'Operador de máquina de lavar ropa' UNION ALL
    SELECT '110', 'Operador de máquina en general' UNION ALL
    SELECT '111', 'Operador de planta transmisora' UNION ALL
    SELECT '112', 'Operador de radio-taxi' UNION ALL
    SELECT '113', 'Operador escogedoras de café' UNION ALL
    SELECT '114', 'Operario' UNION ALL
    SELECT '115', 'Ordenanza' UNION ALL
    SELECT '116', 'Ordeñador' UNION ALL
    SELECT '117', 'Panadero' UNION ALL
    SELECT '118', 'Pastelero' UNION ALL
    SELECT '119', 'Peluquero' UNION ALL
    SELECT '120', 'Periodista' UNION ALL
    SELECT '121', 'Pintor' UNION ALL
    SELECT '122', 'Portero' UNION ALL
    SELECT '123', 'Recamarera' UNION ALL
    SELECT '124', 'Recepcionista' UNION ALL
    SELECT '125', 'Recolector de café' UNION ALL
    SELECT '126', 'Relojero' UNION ALL
    SELECT '127', 'Sastre' UNION ALL
    SELECT '128', 'Secretaria' UNION ALL
    SELECT '129', 'Soldador en general' UNION ALL
    SELECT '130', 'Tapicero' UNION ALL
    SELECT '131', 'Taxista' UNION ALL
    SELECT '132', 'Técnico en educación superior' UNION ALL
    SELECT '133', 'Técnico en aparatos ortopédicos' UNION ALL
    SELECT '134', 'Técnico en refrigeración' UNION ALL
    SELECT '135', 'Técnico máquinas coser industrial' UNION ALL
    SELECT '136', 'Técnico en salud' UNION ALL
    SELECT '137', 'Telefonista' UNION ALL
    SELECT '138', 'Tornero en madera' UNION ALL
    SELECT '139', 'Tornero en metal' UNION ALL
    SELECT '140', 'Verdulero' UNION ALL
    SELECT '141', 'Zapatero' UNION ALL
    SELECT '142', 'Otras ocupaciones' UNION ALL
    SELECT '143', 'Doctor en medicina'

)


SELECT
    code,
    description
FROM lista_de_ocupaciones
