config {
	type: "table",
}

SELECT customer_id,
	JSON_VALUE(content, "$.id") AS applicant_id,
	TIMESTAMP(JSON_VALUE(content, "$.createdAt")) AS created_at,
	JSON_VALUE(content, "$.info.firstName") AS first_name,
	DATE(JSON_VALUE(content, "$.info.dob")) AS date_of_birth,
	JSON_VALUE(content, "$.info.country") AS country,
	JSON_VALUE(content, "$.info.gender") AS gender,

FROM ${ref({
	name: "sumsub_applicants",
	schema: envs.currentImportSchema
})}

WHERE content_type = "SensitiveInfo"
