config {
	type: "table",
}

SELECT 'AGDOSA' AS code, 'Almacenes Generales de Depósito de Occidente, S.A.' AS description UNION ALL
SELECT 'ALAGISA', 'Almacenadora Agrícola e Industrial, S.A.' UNION ALL
SELECT 'ALDESA', 'Almacenes de Desarrollo, S.A.' UNION ALL
SELECT 'ALMADA', 'Almacenadora Davivienda, S.A.' UNION ALL
SELECT 'BODESA', 'Bodegas Generales de Depósito, S.A.' UNION ALL
SELECT 'ALMACONSA', 'Almacenes Consolidados de El Salvador, S.A. DE C.V. (13)' UNION ALL
SELECT 'NOAPLICA', 'No aplica según tipo de bono de prenda'
