config {
	type: "operations",
	hasOutput: true,
  description: "Errors found in Regulatory Report garantia_pignorada.xml of norm NPB4-17"
}

CREATE OR REPLACE TABLE FUNCTION ${self()} (asof TIMESTAMP) AS (

SELECT
    `identificacion_garantia`
  , (${ref('udf_nbp4_17_assert_uppercase_alphanum')}(`identificacion_garantia`)) AS `error_identificacion_garantia`
  , `nit_depositante`
  , (${ref('udf_nbp4_17_assert_niu_number')}(`nit_depositante`)) AS `error_nit_depositante`
  , `fecha_deposito`
  , (${ref('udf_nbp4_17_assert_date')}(CAST(`fecha_deposito` AS STRING))) AS `error_fecha_deposito`
  , `fecha_vencimiento`
  , (${ref('udf_nbp4_17_assert_date')}(CAST(`fecha_vencimiento` AS STRING))) AS `error_fecha_vencimiento`
  , `valor_deposito`
  , (${ref('udf_nbp4_17_assert_nullable_dollar_number')}(CAST(`valor_deposito` AS STRING), 13)) AS `error_valor_deposito`
  , `cod_banco`
  , (${ref('udf_nbp4_17_assert_in_dim_table')}(`cod_banco`, 'stg_dim_15_npb4_17_emisores_de_avales_fianzas_y_cartas')) AS `error_cod_banco`
FROM
  ${ref("stg_07_npb4_17_garantia_pignorada_xml_raw")}(asof)
WHERE (${ref('udf_nbp4_17_assert_uppercase_alphanum')}(`identificacion_garantia`))
  OR (${ref('udf_nbp4_17_assert_niu_number')}(`nit_depositante`))
  OR (${ref('udf_nbp4_17_assert_date')}(CAST(`fecha_deposito` AS STRING)))
  OR (${ref('udf_nbp4_17_assert_date')}(CAST(`fecha_vencimiento` AS STRING)))
  OR (${ref('udf_nbp4_17_assert_nullable_dollar_number')}(CAST(`valor_deposito` AS STRING), 13))
  OR (${ref('udf_nbp4_17_assert_in_dim_table')}(`cod_banco`, 'stg_dim_15_npb4_17_emisores_de_avales_fianzas_y_cartas'))

)
