config {
  type: "operations",
  hasOutput: true,
  description: "Regulatory Report referencia.xml of norm NPB4-17",
  columns: {
    "nit_deudor": "NIT del deudor",
    "cod_cartera": "Código del tipo de cartera",
    "cod_activo": "Código del tipo de activo de riesgo",
    "num_referencia": "Número de la referencia",
    "monto_referencia": "Monto de la referencia",
    "saldo_referencia": "Saldo de la referencia",
    "saldo_vigente_k": "Saldo vigente de capital",
    "saldo_vencido_k": "Saldo vencido de capital",
    "saldo_vigente_i": "Saldo vigente de intereses",
    "saldo_vencido_i": "Saldo vencido de intereses",
    "abono_deposito": "Abonos sin aplicar al préstamo/ depósito sin aplicar a carta de crédito",
    "fecha_otorgamiento": "Fecha de otorgamiento ",
    "fecha_vencimiento": "Fecha de vencimiento ",
    "fecha_castigo": "Fecha de castigo ",
    "estado_credito": "Código del estado del crédito",
    "saldo_mora_k": "Saldo en mora de capital",
    "saldo_mora_i": "Saldo en mora de intereses",
    "dias_mora_k": "Días de mora de capital",
    "dias_mora_i": "Días de mora de intereses",
    "fecha_inicio_mora_k": "Fecha de inicio de mora de capital",
    "fecha_inicio_mora_i": "Fecha de inicio de mora de intereses",
    "pago_capital": "Código de forma de pago de capital",
    "pago_interes": "Código de forma de pago de intereses",
    "periodo_gracia_k": "Periodo de gracia para el pago de capital",
    "periodo_gracia_i": "Periodo de gracia para el pago de intereses",
    "garante": "Código de garantes de créditos pignorados",
    "emisión": "Denominación de la emisión",
    "pais_destino_credito": "Código de país de destino del crédito (21)",
    "destino": "Código de destino de los préstamos por sector económico",
    "codigo_moneda": "Código de moneda",
    "tasa_interes": "Tasa de interés actual",
    "tasa_contractual": "Tasa contractual o nominal",
    "tasa_referencia": "Tasa de referencia publicada",
    "tasa_efectiva": "Tasa efectiva",
    "tipo_tasa_interes": "Tipo de tasa nominal",
    "tipo_prestamo": "Código del tipo de prestamos",
    "codigo_recurso": "Código de fuente de recursos",
    "ultima_fecha_venc": "Última fecha de vencimiento",
    "dias_prorroga": "Días de prorroga",
    "monto_desembolsado": "Monto desembolsado en el mes",
    "tipo_credito": "Tipo de crédito",
    "fecha_ultimo_pago_k": "Fecha del último pago de capital cubierto",
    "fecha_ultimo_pago_i": "Fecha del último pago de intereses cubierto",
    "dia_pago_k": "Día del pago del capital",
    "dia_pago_i": "Día del pago de intereses",
    "cuota_mora_k": "Número de cuotas en mora de capital",
    "cuota_mora_i": "Número de cuotas en mora de intereses",
    "monto_cuota": "Monto de la cuota de la referencia incluyendo capital más intereses",
    "cuenta_contable_k": "Cuenta contable de capital",
    "cuenta_contable_i": "Cuenta contable de intereses",
    "fecha_cancelacion": "Fecha de cancelación de la referencia",
    "adelanto_capital": "Pagos adelantados de capital",
    "riesgo_neto": "Riesgo neto",
    "saldo_seguro": "Saldo del seguro del crédito",
    "saldo_costas_procesales": "Saldo por costas procesales",
    "tipo_tarjeta_credito": "Tipo de tarjeta de crédito",
    "clase_tarjeta_credito": "Código de la clase de tarjeta de crédito",
    "producto_tarjeta_credito": "Producto de la tarjeta de crédito",
    "valor_garantia_cons": "Valor consolidado de la garantía",
    "municipio_otorgamiento": "Código del municipio destino del crédito",
    "reserva_referencia": "Reserva por referencia ",
    "etapa_judicial": "Código de la etapa del crédito en vía judicial",
    "fecha_demanda": "Fecha de la demanda",
    "plazo_credito": "Plazo del crédito",
    "orden_descuento": "Con o sin orden de descuento",
    "categoria_riesgo_ref": "Código de la categoría de riesgo de la referencia (20)",
    "reserva_constituir": "Reserva acumulada a constituir créditos COVID (20)",
    "porcentaje_reserva": "Porcentaje de reserva constituida de acuerdo con la gradualidad créditos COVID (20)",
    "pago_cuota": "Monto pagado de la cuota de la referencia (20) (21)",
    "fecha_pago": "Fecha en que realizó el pago de la cuota (20) (21)",
    "porcenta_reserva_descon": "Porcentaje de reserva a descontar créditos agropecuarios (20)",
    "porcenta_adiciona_descon": "Porcentaje de reserva adicional a descontar agropecuarios",
    "depto_destino_credito": "Código de departamento de destino del crédito (21)",
    "porc_reserva_referencia": "Porcentaje de reserva por referencia (21)",
    "calculo_brecha": "Cálculo de brecha de reserva de saneamiento de la referencia (21)",
    "ajuste_brecha": "Cálculo de ajuste mensual de brecha de la referencia (21)",
    "programa_asist_cafe": "Programa de asistencia suscrito créditos destino café (21)",
    "fecha_cump_cafe": "Fecha de última carta de cumplimiento del programa de asistencia créditos destino café (21)",
  },
}

CREATE OR REPLACE TABLE FUNCTION ${self()} (asof TIMESTAMP) AS (

SELECT
    CAST(NULL AS STRING) AS `nit_deudor`
  , (
	SELECT code
	FROM ${ref("stg_dim_01_npb4_17_tipos_de_cartera")}
	WHERE description = "Cartera propia Ley Acceso al Crédito (19)"
  ) AS `cod_cartera`
  , (
	SELECT code
	FROM ${ref("stg_dim_01_npb4_17_tipos_de_cartera")}
	WHERE description = "Préstamos"
  ) AS `cod_activo`
  , loan_id AS `num_referencia`
  , principal AS `monto_referencia` -- Original loan amount
  , principal + total_interest_incurred - total_interest_paid - total_principal_paid AS `saldo_referencia` -- Remaining balance
  , principal - total_principal_paid AS `saldo_vigente_k`
  , CAST(NULL AS NUMERIC) AS `saldo_vencido_k`
  , total_interest_incurred - total_principal_paid AS `saldo_vigente_i`
  , CAST(NULL AS NUMERIC) AS `saldo_vencido_i`
  , CAST(NULL AS NUMERIC) AS `abono_deposito`
  , DATE(start_timestamp) AS `fecha_otorgamiento`
  , end_date AS `fecha_vencimiento`
  , CAST(NULL AS DATE) AS `fecha_castigo`
  , CAST(NULL AS STRING) AS `estado_credito`
  , CAST(NULL AS NUMERIC) AS `saldo_mora_k`
  , CAST(NULL AS NUMERIC) AS `saldo_mora_i`
  , CAST(NULL AS NUMERIC) AS `dias_mora_k`
  , CAST(NULL AS NUMERIC) AS `dias_mora_i`
  , CAST(NULL AS DATE) AS `fecha_inicio_mora_k`
  , CAST(NULL AS DATE) AS `fecha_inicio_mora_i`
  , CASE
      WHEN payment_interval = "end_of_month"
      THEN (
	SELECT code
	FROM ${ref("stg_dim_01_npb4_17_tipos_de_cartera")}
	WHERE description = "Mensual"
      )
  END AS `pago_capital`
  , CASE
      WHEN payment_interval = "end_of_month"
      THEN (
	SELECT code
	FROM ${ref("stg_dim_01_npb4_17_tipos_de_cartera")}
	WHERE description = "Mensual"
      )
  END AS `pago_interes`
  , CAST(NULL AS NUMERIC) AS `periodo_gracia_k`
  , CAST(NULL AS NUMERIC) AS `periodo_gracia_i`
  , CAST(NULL AS STRING) AS `garante`
  , CAST(NULL AS STRING) AS `emisión`
  , CAST(NULL AS NUMERIC) AS `pais_destino_credito`
  , CAST(NULL AS STRING) AS `destino`
  , (
	SELECT code
	FROM ${ref("stg_dim_17_npb4_17_monedas")}
	WHERE description = "Dólares"
  ) AS `codigo_moneda`
  , CAST(annual_rate AS NUMERIC) AS `tasa_interes`
  , CAST(annual_rate AS NUMERIC) AS `tasa_contractual`
  , CAST(NULL AS NUMERIC) AS `tasa_referencia`
  , CAST(NULL AS NUMERIC) AS `tasa_efectiva`
  , "F" AS `tipo_tasa_interes` -- "A" for adjustable, "F" for fixed
  , (
	SELECT code
	FROM ${ref("stg_dim_18_npb4_17_tipos_de_prestamos")}
	WHERE description = "Crédito decreciente"
  ) AS `tipo_prestamo`
  , (
	SELECT code
	FROM ${ref("stg_dim_21_npb4_17_fuentes_de_recursos")}
	WHERE description = "Recursos propios de la entidad"
  ) AS `codigo_recurso`
  , CAST(NULL AS DATE) AS `ultima_fecha_venc`
  , CAST(NULL AS NUMERIC) AS `dias_prorroga`
  , CAST(NULL AS NUMERIC) AS `monto_desembolsado`
  , CAST(NULL AS STRING) AS `tipo_credito`
  , DATE(most_recent_interest_payment_timestamp) AS `fecha_ultimo_pago_k`
  , DATE(most_recent_principal_payment_timestamp) AS `fecha_ultimo_pago_i`
  , CAST(NULL AS NUMERIC) AS `dia_pago_k`
  , CAST(NULL AS NUMERIC) AS `dia_pago_i`
  , CAST(NULL AS NUMERIC) AS `cuota_mora_k`
  , CAST(NULL AS NUMERIC) AS `cuota_mora_i`
  , CAST(NULL AS NUMERIC) AS `monto_cuota`
  , CAST(NULL AS STRING) AS `cuenta_contable_k`
  , CAST(NULL AS STRING) AS `cuenta_contable_i`
  , CAST(NULL AS DATE) AS `fecha_cancelacion`
  , CAST(NULL AS NUMERIC) AS `adelanto_capital`
  , CAST(NULL AS NUMERIC) AS `riesgo_neto` -- Corresponde al saldo de la referencia (2.6. saldo_referencia) menos el valor proporcional de las garantías que cubren esa referencia (3.6. valor_garantia_proporcional).
  , CAST(NULL AS NUMERIC) AS `saldo_seguro`
  , CAST(NULL AS NUMERIC) AS `saldo_costas_procesales`
  , CAST(NULL AS STRING) AS `tipo_tarjeta_credito`
  , CAST(NULL AS STRING) AS `clase_tarjeta_credito`
  , CAST(NULL AS STRING) AS `producto_tarjeta_credito`
  , CAST(NULL AS NUMERIC) AS `valor_garantia_cons`
  , CAST(NULL AS STRING) AS `municipio_otorgamiento`
  , CAST(NULL AS NUMERIC) AS `reserva_referencia`
  , CAST(NULL AS STRING) AS `etapa_judicial`
  , CAST(NULL AS DATE) AS `fecha_demanda`
  , CAST(NULL AS NUMERIC) AS `plazo_credito`
  , CAST(NULL AS STRING) AS `orden_descuento`
  , (
	SELECT code
	FROM ${ref("stg_dim_03_npb4_17_tipos_de_categorias_de_riesgo")}
	WHERE description = "Deudores normales"
  ) AS `categoria_riesgo_ref`
  , CAST(NULL AS NUMERIC) AS `reserva_constituir`
  , CAST(NULL AS NUMERIC) AS `porcentaje_reserva`
  , CAST(NULL AS NUMERIC) AS `pago_cuota`
  , CAST(NULL AS DATE) AS `fecha_pago`
  , CAST(NULL AS NUMERIC) AS `porcenta_reserva_descon`
  , CAST(NULL AS NUMERIC) AS `porcenta_adiciona_descon`
  , CAST(NULL AS STRING) AS `depto_destino_credito`
  , CAST(NULL AS NUMERIC) AS `porc_reserva_referencia`
  , CAST(NULL AS NUMERIC) AS `calculo_brecha`
  , CAST(NULL AS NUMERIC) AS `ajuste_brecha`
  , CAST(NULL AS STRING) AS `programa_asist_cafe`
  , CAST(NULL AS DATE) AS `fecha_cump_cafe`

FROM ${ref("stg_approved_loans")}(asof)

)
