config {
	type: "table",
}

SELECT '01' AS code, 'Recursos propios de la entidad' AS description UNION ALL
SELECT '02', 'Recursos de bancos extranjeros de corto plazo' UNION ALL
SELECT '03', 'Recursos de bancos extranjeros de mediano y largo plazo' UNION ALL
SELECT '04', 'Recursos del Banco Central de Reserva de El Salvador (BCR)' UNION ALL
SELECT '05', 'Recursos del Banco de Desarrollo de la Republica de El Salvador (BANDESAL) (21)' UNION ALL
SELECT '06', 'Recursos del Banco Centroamericano de Integración Económica (BCIE)' UNION ALL
SELECT '07', 'Recursos del Banco Interamericano de Desarrollo (BID)' UNION ALL
SELECT '08', 'Recursos del Banco Mundial' UNION ALL
SELECT '09', 'Recursos del Fondo Nacional para la Vivienda Popular ( FONAVIPO)' UNION ALL
SELECT '10', 'Recursos del Fondo Social para la Vivienda (FSV)' UNION ALL
SELECT '11', 'Recursos de Certificados de Depósitos a Plazo de Vivienda (CEDEVIV)' UNION ALL
SELECT '12', 'Recursos de Certificados de Depósitos a Plazo Agropecuario (CEDEAGRO)' UNION ALL
SELECT '13', 'Recursos Préstamos BCR-BID' UNION ALL
SELECT '99', 'Recursos de otras fuentes'
