config {
  type: "operations",
  hasOutput: true,
  description: "Regulatory Report referencia.xml of norm NPB4-17",
  dependencies: ["report_01_npb4_17_persona_xml"],
}

CREATE OR REPLACE TABLE FUNCTION ${self()} (asof TIMESTAMP) AS (

SELECT
    customer_id AS `nit_deudor`
  , (
	SELECT code
	FROM ${ref("stg_dim_01_npb4_17_tipos_de_cartera")}
	WHERE description = "Cartera propia Ley Acceso al Crédito (19)"
  ) AS `cod_cartera`
  , (
	SELECT code
	FROM ${ref("stg_dim_01_npb4_17_tipos_de_cartera")}
	WHERE description = "Préstamos"
  ) AS `cod_activo`
  , loan_id AS `num_referencia`
  , principal AS `monto_referencia` -- Original loan amount
  , principal + total_interest_incurred - total_interest_paid - total_principal_paid AS `saldo_referencia` -- Remaining balance
  , principal - total_principal_paid AS `saldo_vigente_k`
  , CAST(NULL AS NUMERIC) AS `saldo_vencido_k`
  , total_interest_incurred - total_principal_paid AS `saldo_vigente_i`
  , CAST(NULL AS NUMERIC) AS `saldo_vencido_i`
  , CAST(NULL AS NUMERIC) AS `abono_deposito`
  , DATE(start_timestamp) AS `fecha_otorgamiento`
  , end_date AS `fecha_vencimiento`
  , CAST(NULL AS DATE) AS `fecha_castigo`
  , CAST(NULL AS STRING) AS `estado_credito`
  , CAST(NULL AS NUMERIC) AS `saldo_mora_k`
  , CAST(NULL AS NUMERIC) AS `saldo_mora_i`
  , CAST(NULL AS NUMERIC) AS `dias_mora_k`
  , CAST(NULL AS NUMERIC) AS `dias_mora_i`
  , CAST(NULL AS DATE) AS `fecha_inicio_mora_k`
  , CAST(NULL AS DATE) AS `fecha_inicio_mora_i`
  , CASE
      WHEN payment_interval = "end_of_month"
      THEN (
	SELECT code
	FROM ${ref("stg_dim_01_npb4_17_tipos_de_cartera")}
	WHERE description = "Mensual"
      )
  END AS `pago_capital`
  , CASE
      WHEN payment_interval = "end_of_month"
      THEN (
	SELECT code
	FROM ${ref("stg_dim_01_npb4_17_tipos_de_cartera")}
	WHERE description = "Mensual"
      )
  END AS `pago_interes`
  , CAST(NULL AS NUMERIC) AS `periodo_gracia_k`
  , CAST(NULL AS NUMERIC) AS `periodo_gracia_i`
  , CAST(NULL AS STRING) AS `garante`
  , CAST(NULL AS STRING) AS `emisión`
  , CAST(NULL AS NUMERIC) AS `pais_destino_credito`
  , CAST(NULL AS STRING) AS `destino`
  , (
	SELECT code
	FROM ${ref("stg_dim_17_npb4_17_monedas")}
	WHERE description = "Dólares"
  ) AS `codigo_moneda`
  , CAST(annual_rate AS NUMERIC) AS `tasa_interes`
  , CAST(annual_rate AS NUMERIC) AS `tasa_contractual`
  , CAST(NULL AS NUMERIC) AS `tasa_referencia`
  , CAST(NULL AS NUMERIC) AS `tasa_efectiva`
  , "F" AS `tipo_tasa_interes` -- "A" for adjustable, "F" for fixed
  , (
	SELECT code
	FROM ${ref("stg_dim_18_npb4_17_tipos_de_prestamos")}
	WHERE description = "Crédito decreciente"
  ) AS `tipo_prestamo`
  , (
	SELECT code
	FROM ${ref("stg_dim_21_npb4_17_fuentes_de_recursos")}
	WHERE description = "Recursos propios de la entidad"
  ) AS `codigo_recurso`
  , CAST(NULL AS DATE) AS `ultima_fecha_venc`
  , CAST(NULL AS NUMERIC) AS `dias_prorroga`
  , CAST(NULL AS NUMERIC) AS `monto_desembolsado`
  , CAST(NULL AS STRING) AS `tipo_credito`
  , DATE(most_recent_interest_payment_timestamp) AS `fecha_ultimo_pago_k`
  , DATE(most_recent_principal_payment_timestamp) AS `fecha_ultimo_pago_i`
  , CAST(NULL AS NUMERIC) AS `dia_pago_k`
  , CAST(NULL AS NUMERIC) AS `dia_pago_i`
  , CAST(NULL AS NUMERIC) AS `cuota_mora_k`
  , CAST(NULL AS NUMERIC) AS `cuota_mora_i`
  , CAST(NULL AS NUMERIC) AS `monto_cuota`
  , CAST(NULL AS STRING) AS `cuenta_contable_k`
  , CAST(NULL AS STRING) AS `cuenta_contable_i`
  , CAST(NULL AS DATE) AS `fecha_cancelacion`
  , CAST(NULL AS NUMERIC) AS `adelanto_capital`
  , CAST(NULL AS NUMERIC) AS `riesgo_neto` -- Corresponde al saldo de la referencia (2.6. saldo_referencia) menos el valor proporcional de las garantías que cubren esa referencia (3.6. valor_garantia_proporcional).
  , CAST(NULL AS NUMERIC) AS `saldo_seguro`
  , CAST(NULL AS NUMERIC) AS `saldo_costas_procesales`
  , CAST(NULL AS STRING) AS `tipo_tarjeta_credito`
  , CAST(NULL AS STRING) AS `clase_tarjeta_credito`
  , CAST(NULL AS STRING) AS `producto_tarjeta_credito`
  , CAST(NULL AS NUMERIC) AS `valor_garantia_cons`
  , CAST(NULL AS STRING) AS `municipio_otorgamiento`
  , CAST(NULL AS NUMERIC) AS `reserva_referencia`
  , CAST(NULL AS STRING) AS `etapa_judicial`
  , CAST(NULL AS DATE) AS `fecha_demanda`
  , CAST(NULL AS NUMERIC) AS `plazo_credito`
  , CAST(NULL AS STRING) AS `orden_descuento`
  , (
	SELECT code
	FROM ${ref("stg_dim_03_npb4_17_tipos_de_categorias_de_riesgo")}
	WHERE description = "Deudores normales"
  ) AS `categoria_riesgo_ref`
  , CAST(NULL AS NUMERIC) AS `reserva_constituir`
  , CAST(NULL AS NUMERIC) AS `porcentaje_reserva`
  , CAST(NULL AS NUMERIC) AS `pago_cuota`
  , CAST(NULL AS DATE) AS `fecha_pago`
  , CAST(NULL AS NUMERIC) AS `porcenta_reserva_descon`
  , CAST(NULL AS NUMERIC) AS `porcenta_adiciona_descon`
  , CAST(NULL AS STRING) AS `depto_destino_credito`
  , CAST(NULL AS NUMERIC) AS `porc_reserva_referencia`
  , CAST(NULL AS NUMERIC) AS `calculo_brecha`
  , CAST(NULL AS NUMERIC) AS `ajuste_brecha`
  , CAST(NULL AS STRING) AS `programa_asist_cafe`
  , CAST(NULL AS DATE) AS `fecha_cump_cafe`

FROM ${ref("stg_approved_loans")}(asof)

)
