config {
  type: "table",
  description: "Data ingestion for Regulatory Report persona.xml of norm NPB4-17"
}

WITH
customers AS (
  SELECT
      ROW_NUMBER() OVER(ORDER BY id) sequence_id
    , id as customer_id
    , email
  FROM
  ${ref("stg_customers")}
),
customers_identities AS (
  SELECT *
  FROM
  ${ref("stg_customers_identities")}
),
approved_loans AS (
  SELECT *
  FROM
  ${ref("stg_approved_loans")}
)

SELECT
    LEFT(REPLACE(customer_id, '-', ''), 14) AS `nit_persona`      -- use NIU type (`tipo_identificador` = 'N') with use 14 leftmost no-hyphen characters from backend customer_id
  , CAST(NULL AS STRING) AS `dui`                                 -- NULL for non-Salvadoran (`nacionalidad` != '9300')
  , first_name AS `primer_apellido`                               -- required
  , CAST(NULL AS STRING) AS `segundo_apellido`                    --
  , CAST(NULL AS STRING) AS `apellido_casada`                     --
  , last_name AS `primer_nombre`                                  -- required
  , CAST(NULL AS STRING) AS `segundo_nombre`                      --
  , CAST(NULL AS STRING) AS `nombre_sociedad`                     -- NULL for natural person
  , '1' AS `tipo_persona`                                         -- '1' for natural person
  , '0' AS `tipo_relacion`                                        -- '0' for natural person
  , 'N' AS `tipo_identificador`                                   -- 'N' for non-Salvadoran
  , CAST(NULL AS STRING) AS `nit_desactualizado`                  -- NULL for non-Salvadoran
  , 'N' AS `residente`                                            -- 'N' for non-Salvadoran
  , economic_activity_code AS `giro_persona`                      -- codified main economic activity of the person, i.e. the one that generates the greatest cash flow
  , CAST(NULL AS STRING) AS `tamano_empresa`                      -- NULL for natural person
  , CAST(NULL AS STRING) AS `tipo_empresa`                        -- NULL for natural person
  , 7060.0 AS `reserva`                                           -- Provision of sanitation reserves established accounted for by the entity for each debtor
  , 'TODO' AS `categoria_riesgo`                                  -- codified risk category assigned to the debtor depending of the status of the loan
  , RIGHT(REPLACE(customer_id, '-', ''), 17) AS `numero_cliente`  -- use 17 rightmost no-hyphen characters from backend customer_id
  , passport_number AS `id_alterno`                               -- passport number / social security number / driver's license number / id card number
  , 'PS' AS `tipo_id_alterno`                                     -- 'PS' for passport / 'SS' for social security / 'LI' for driver's license / 'CI' for id card
  , date_of_birth AS `fecha_nacimiento`                           -- date of birth
  , country_of_residence_code AS `pais_residencia`                -- country of residence
  , 7060.0 AS `riesgo_consolidado`                                -- Sum of the balances of the references that the person has plus the accrued interest
  , gender AS `sexo_persona`                                      -- gender 'M' / 'F'
  , occupation_code AS `ocupación`                                -- codified occupation
  , tax_id_number AS `id_pais_origen`                             -- TIN (Tax Identification Number) issued by the country of origin
  , nationality_code AS `nacionalidad`                            -- codified nationality
  , CAST(NULL AS STRING) AS `nit_anterior`                        -- NULL for natural person
  , CAST(NULL AS STRING) AS `tipo_ident_anterior`                 -- NULL for natural person
  , CAST(NULL AS STRING) AS `municipio_residencia`                -- NULL for non-Salvadoran
FROM customers
LEFT JOIN customers_identities USING (sequence_id)
