mutation AddEquityTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
  $bankReserveAccountId: Expression!
  $bankEquityAccountId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "ADD_EQUITY"
      description: "An equity injection against the bank's USD reserve account."
      params: [
        {
          name: "amount"
          type: DECIMAL
          description: "Amount of USD being deposited."
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: $bankReserveAccountId
          units: "params.amount"
          currency: "'USD'"
          entryType: "'ADD_EQUITY_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: $bankEquityAccountId
          units: "params.amount"
          currency: "'USD'"
          entryType: "'ADD_EQUITY_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostAddEquityTransaction(
  $transactionId: UUID!
  $amount: Decimal!
  $externalId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "ADD_EQUITY"
      params: { amount: $amount, externalId: $externalId }
    }
  ) {
    transaction {
      transactionId
      correlationId
    }
  }
}
