mutation ApproveCreditFacilityTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
  $omnibusCreditFacilityAccount: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "APPROVE_CREDIT_FACILITY"
      description: "Create credit facility."
      params: [
        {
          name: "creditFacilityAccount"
          type: UUID
          description: "Credit facility account ID."
        }
        {
          name: "facilityAmount"
          type: DECIMAL
          description: "Amount of USD being approved as a facility for the credit."
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: "params.creditFacilityAccount"
          units: "params.facilityAmount"
          currency: "'USD'"
          entryType: "'APPROVE_CREDIT_FACILITY_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: $omnibusCreditFacilityAccount
          units: "params.facilityAmount"
          currency: "'USD'"
          entryType: "'APPROVE_CREDIT_FACILITY_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostApproveCreditFacilityTransaction(
  $transactionId: UUID!
  $creditFacilityAccount: UUID!
  $facilityAmount: Decimal!
  $externalId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "APPROVE_CREDIT_FACILITY"
      params: {
        creditFacilityAccount: $creditFacilityAccount
        facilityAmount: $facilityAmount
        externalId: $externalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
      createdAt
    }
  }
}
