mutation IncurInterestTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "INCUR_INTEREST"
      description: "Incur interest payment owed for loan."
      params: [
        {
          name: "loanInterestReceivableAccount"
          type: UUID
          description: "Loan interest-outstanding account ID."
        }
        {
          name: "loanInterestIncomeAccount"
          type: UUID
          description: "Loan interest income earned account id."
        }
        {
          name: "interestAmount"
          type: DECIMAL
          description: "Amount of USD being paid as interest."
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: "params.loanInterestReceivableAccount"
          units: "params.interestAmount"
          currency: "'USD'"
          entryType: "'INCUR_INTEREST_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.loanInterestIncomeAccount"
          units: "params.interestAmount"
          currency: "'USD'"
          entryType: "'INCUR_INTEREST_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostIncurInterestTransaction(
  $transactionId: UUID!
  $loanInterestReceivableAccount: UUID!
  $loanInterestIncomeAccount: UUID!
  $interestAmount: Decimal!
  $externalId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "INCUR_INTEREST"
      params: {
        loanInterestReceivableAccount: $loanInterestReceivableAccount
        loanInterestIncomeAccount: $loanInterestIncomeAccount
        interestAmount: $interestAmount
        externalId: $externalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
      createdAt
    }
  }
}
