config {
	type: "table",
	description: "Each row represents a unique approved credit facility.",
	assertions: {
		uniqueKey: ["credit_facility_key"],
		nonNull: ["credit_facility_key", "initialized_at", "end_date", "annual_rate", "customer_key", "completed"],
		rowConditions: ["DATE(initialized_at) <= end_date"],
	},
}

SELECT credit_facilities.* EXCEPT (credit_facility_id, customer_id),
	customer_key,

FROM ${ref("int_approved_credit_facilities")}(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), DAY)) AS credit_facilities
JOIN ${ref("int_customers")} USING (customer_id)
