config {
    type: "table",
    description: "Each row represents a unique collateral updated event action in credit facility.",
    assertions: {
        uniqueKey: ["action_key"],
        nonNull: ["action"],
    },
}

WITH distinct_entries AS (
    SELECT DISTINCT
        JSON_VALUE(event, "$.action") AS action
    FROM ${ref({name: "credit_facility_events", schema: envs.currentImportSchema})}
    WHERE event_type = "collateral_updated"
)

SELECT
      ROW_NUMBER() OVER (ORDER BY action) AS action_key
    , action
FROM distinct_entries
