config {
	type: "table",
	description: "Each row represents a unique account.",
	assertions: {
		uniqueKey: ["set_key", "account_key"],
	},
	tags : ["regulatory-report"],
}

SELECT set_key,
	set_name,
	member_id AS account_key,

FROM ${ref("int_account_sets_expanded")}
JOIN ${ref("int_account_sets")} USING (set_id)
JOIN ${ref("int_accounts")} ON member_id = account_id

WHERE member_type = "Account"
