config {
	type: "table",
	description: "Each row represents a unique approved loan.",
	assertions: {
		uniqueKey: ["loan_key"],
		nonNull: ["loan_key", "initialized_at", "end_date", "annual_rate", "customer_key", "completed", "principal"],
		rowConditions: ["DATE(initialized_at) <= end_date"],
	},
}

SELECT loans.* EXCEPT (loan_id, customer_id),
	customer_key

FROM ${ref("int_approved_loans")}(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), DAY)) AS loans
JOIN ${ref("int_customers")} USING (customer_id)
