config {
    type: "table",
    description: "Each row represents a unique terms annual rate in credit facility.",
    assertions: {
        uniqueKey: ["terms_annual_rate_key"],
        nonNull: ["terms_annual_rate"],
    },
}

WITH distinct_entries AS (
    SELECT DISTINCT
        JSON_VALUE(event, "$.terms.annual_rate") AS terms_annual_rate
    FROM ${ref({name: "credit_facility_events", schema: envs.currentImportSchema})}
    WHERE event_type = "initialized"
)

SELECT
      ROW_NUMBER() OVER (ORDER BY terms_annual_rate) AS terms_annual_rate_key
    , terms_annual_rate
FROM distinct_entries
