config {
    type: "table",
    description: "Each row represents a unique terms duration value in credit facility.",
    assertions: {
        uniqueKey: ["terms_duration_value_key"],
        nonNull: ["terms_duration_value"],
    },
}

WITH distinct_entries AS (
    SELECT DISTINCT
        CAST(JSON_VALUE(event, "$.terms.duration.value") AS INTEGER) AS terms_duration_value
    FROM ${ref({name: "credit_facility_events", schema: envs.currentImportSchema})}
    WHERE event_type = "initialized"
)

SELECT
      ROW_NUMBER() OVER (ORDER BY terms_duration_value) AS terms_duration_value_key
    , terms_duration_value
FROM distinct_entries
