config {
    type: "table",
    description: "Each row represents the unique customer (surrogate, natural) key pair in credit facility.",
    assertions: {
        uniqueKey: ["customer_id_key"],
        nonNull: ["customer_id"],
    },
}

WITH distinct_entries AS (
    SELECT DISTINCT
        JSON_VALUE(event, "$.customer_id") AS customer_id
    FROM ${ref({name: "credit_facility_events", schema: envs.currentImportSchema})}
    WHERE event_type = "initialized"
)

SELECT
      ROW_NUMBER() OVER (ORDER BY customer_id) AS customer_id_key
    , customer_id
FROM distinct_entries
