config {
    type: "table",
    description: "Each row represents the unique (surrogate, natural) key pair in credit facility.",
    assertions: {
        uniqueKey: ["event_key"],
        nonNull: ["event_id"],
    },
}

WITH distinct_entries AS (
    SELECT DISTINCT
        id AS event_id
    FROM ${ref({name: "credit_facility_events", schema: envs.currentImportSchema})}
)

SELECT
      ROW_NUMBER() OVER (ORDER BY event_id) AS event_key
    , event_id
FROM distinct_entries
