config {
    type: "table",
    description: "Each row represents a unique terms duration type in credit facility.",
    assertions: {
        uniqueKey: ["terms_duration_type_key"],
        nonNull: ["terms_duration_type"],
    },
}

WITH distinct_entries AS (
    SELECT DISTINCT
        JSON_VALUE(event, "$.terms.duration.type") AS terms_duration_type
    FROM ${ref({name: "credit_facility_events", schema: envs.currentImportSchema})}
    WHERE event_type = "initialized"
)

SELECT
      ROW_NUMBER() OVER (ORDER BY terms_duration_type) AS terms_duration_type_key
    , terms_duration_type
FROM distinct_entries
