config {
    type: "table",
    description: "Each row represents a unique terms liquidation cvl in credit facility.",
    assertions: {
        uniqueKey: ["terms_liquidation_cvl_key"],
        nonNull: ["terms_liquidation_cvl"],
    },
}

WITH distinct_entries AS (
    SELECT DISTINCT
        CAST(JSON_VALUE(event, "$.terms.liquidation_cvl") AS NUMERIC) AS terms_liquidation_cvl
    FROM ${ref({name: "credit_facility_events", schema: envs.currentImportSchema})}
    WHERE event_type = "initialized"
)

SELECT
      ROW_NUMBER() OVER (ORDER BY terms_liquidation_cvl) AS terms_liquidation_cvl_key
    , terms_liquidation_cvl
FROM distinct_entries
