config {
    type: "table",
    description: "Each row represents a unique terms initial cvl in credit facility.",
    assertions: {
        uniqueKey: ["terms_initial_cvl_key"],
        nonNull: ["terms_initial_cvl"],
    },
}

WITH distinct_entries AS (
    SELECT DISTINCT
        CAST(JSON_VALUE(event, "$.terms.initial_cvl") AS NUMERIC) AS terms_initial_cvl
    FROM ${ref({name: "credit_facility_events", schema: envs.currentImportSchema})}
    WHERE event_type = "initialized"
)

SELECT
      ROW_NUMBER() OVER (ORDER BY terms_initial_cvl) AS terms_initial_cvl_key
    , terms_initial_cvl
FROM distinct_entries
