config {
    type: "table",
    description: "Each row represents a unique terms incurrence interval type in credit facility.",
    assertions: {
        uniqueKey: ["terms_incurrence_interval_type_key"],
        nonNull: ["terms_incurrence_interval_type"],
    },
}

WITH distinct_entries AS (
    SELECT DISTINCT
        JSON_VALUE(event, "$.terms.incurrence_interval.type") AS terms_incurrence_interval_type
    FROM ${ref({name: "credit_facility_events", schema: envs.currentImportSchema})}
    WHERE event_type = "initialized"
)

SELECT
      ROW_NUMBER() OVER (ORDER BY terms_incurrence_interval_type) AS terms_incurrence_interval_type_key
    , terms_incurrence_interval_type
FROM distinct_entries
