config {
	type: "table",
	description: "Each row represents a unique transaction entry.",
	assertions: {
		uniqueKey: ["transaction_entry_key"],
	},
	tags : ["regulatory-report"],
}

SELECT transaction_entries.* EXCEPT (transaction_entry_id, account_id, transaction_id),
	account_key,
	transaction_key,
	CASE
		WHEN direction = "debit" THEN units
		ELSE -units
	END AS debit,
	CASE
		WHEN direction = "credit" THEN units
		ELSE -units
	END AS credit,

FROM ${ref("int_transaction_entries")} AS transaction_entries
JOIN  ${ref("int_accounts")} USING (account_id)
JOIN  ${ref("int_transactions")} USING (transaction_id)
