config {
	type: "table",
}

WITH emisores_de_avales_fianzas_y_cartas AS (

-- Bancos locales
    SELECT 'BC03' AS code, 'Banco Agrícola, S.A.' AS description UNION ALL
    SELECT 'BC04', 'Banco Cuscatlán de El Salvador, S.A. (21)' UNION ALL
    SELECT 'BC07', 'Banco Davivienda Salvadoreño, S.A.' UNION ALL
    SELECT 'BC08', 'Banco Hipotecario de El Salvador, S.A.' UNION ALL
    SELECT 'BC09', 'Citibank, N.A., Sucursal El Salvador (21)' UNION ALL
    SELECT 'BC10', 'Banco de Fomento Agropecuario' UNION ALL
    SELECT 'BC18', 'Banco G&T Continental, S.A.' UNION ALL
    SELECT 'BC20', 'Banco Promérica, S.A.' UNION ALL
    SELECT 'BC23', 'Derogado. (21)' UNION ALL
    SELECT 'BC27', 'Banco de América Central, S.A.' UNION ALL
    SELECT 'BC30', 'Banco ABANK, S.A. (21)' UNION ALL
    SELECT 'BC31', 'Banco Industrial El Salvador, S.A. (13)' UNION ALL
    SELECT 'BC32', 'Banco Azul El Salvador, S.A. (21)' UNION ALL
    SELECT 'FC09', 'Banco Atlántida El Salvador, S.A. (21)' UNION ALL
-- Bancos cooperativos (13)
    SELECT 'NB01', 'Federación de Cajas de Crédito y Bancos de los Trabajadores, S.C. de R.L. de C.V.' UNION ALL
    SELECT 'NB02', 'Multi Inversiones Banco Cooperativo de los Trabajadores, S.C. de R.L. de C.V.' UNION ALL
    SELECT 'NB03', 'Banco de los Trabajadores Salvadoreños, S.C. de R.L. de C.V.' UNION ALL
    SELECT 'NB04', 'Banco Izalqueño de los Trabajadores, S.C. de R.L. de C.V.' UNION ALL
    SELECT 'NB05', 'Asociación Cooperativa de Ahorro y Crédito Vicentina de R.L.' UNION ALL
    SELECT 'NB06', 'Primer Banco de los Trabajadores, S.C. de R.L. de C.V.' UNION ALL
    SELECT 'NB07', 'Asociación Cooperativa de Ahorro y Crédito del Colegio Médico de El Salvador de R.L.' UNION ALL
-- Sociedades de ahorro y crédito (13)
    SELECT 'SA01', 'Sociedad de Ahorro y Crédito Apoyo Integral, S.A.' UNION ALL
    SELECT 'SA02', 'Sociedad de Ahorro y Crédito CREDICOMER, S.A.' UNION ALL
    SELECT 'SA03', 'Sociedad de Ahorro y Crédito Constelación, S.A. (21)'
-- Entidades financieras extranjeras de primera línea
-- De acuerdo al listado emitido por la Superintendencia en cumplimiento a las “Normas para determinar las entidades financieras extranjeras de primera línea” (NPB4-43)

)


SELECT
    code,
    description
FROM emisores_de_avales_fianzas_y_cartas
