config {
	type: "table",
}

WITH departamentos_para_ubicacion_geografica AS (

    SELECT '01' AS code, 'Ahuachapán' AS description UNION ALL
    SELECT '02', 'Santa Ana' UNION ALL
    SELECT '03', 'Sonsonate' UNION ALL
    SELECT '04', 'Chalatenango' UNION ALL
    SELECT '05', 'La Libertad' UNION ALL
    SELECT '06', 'San Salvador' UNION ALL
    SELECT '07', 'Cuscatlán' UNION ALL
    SELECT '08', 'La Paz' UNION ALL
    SELECT '09', 'Cabañas' UNION ALL
    SELECT '10', 'San Vicente' UNION ALL
    SELECT '11', 'Usulután' UNION ALL
    SELECT '12', 'San Miguel' UNION ALL
    SELECT '13', 'Morazán' UNION ALL
    SELECT '14', 'La Unión' UNION ALL
    SELECT '15', 'Derogado (21)' UNION ALL
    SELECT '16', 'Derogado (21)' UNION ALL
    SELECT '17', 'Derogado (21)' UNION ALL
    SELECT '18', 'Derogado (21)' UNION ALL
    SELECT '19', 'Derogado (21)' UNION ALL
    SELECT '20', 'Derogado (21)'

)


SELECT
    code,
    description
FROM departamentos_para_ubicacion_geografica
