config {
	type: "operations",
	hasOutput: true,
	description: "Calculates a loan Yield-to-Maturity internal rate of return."
}

CREATE OR REPLACE FUNCTION ${self()} (interest_rate FLOAT64, times ARRAY<FLOAT64>, cash_flows ARRAY<FLOAT64>)
RETURNS FLOAT64
LANGUAGE js
AS r"""
  const loan_pv = ${time_value_money_discrete.loan_pv};
  const loan_ytm = ${time_value_money_discrete.loan_ytm};
  const loan_ytm_from_price = ${time_value_money_discrete.loan_ytm_from_price};
  const loan_duration = ${time_value_money_discrete.loan_duration};
  const loan_mac_duration = ${time_value_money_discrete.loan_mac_duration};
  const loan_mod_duration = ${time_value_money_discrete.loan_mod_duration};
  const loan_convexity = ${time_value_money_discrete.loan_convexity};
  const loan_pv_delta_on_interest_rate_delta = ${time_value_money_discrete.loan_pv_delta_on_interest_rate_delta};
  const loan_pv_delta_on_interest_rate_delta_with_convex = ${time_value_money_discrete.loan_pv_delta_on_interest_rate_delta_with_convex};

  return loan_ytm_from_price(interest_rate, times, cash_flows);
"""
-- OPTIONS (library='gs://external_code/time-value-money.js')
;
