docker_compose("../docker-compose.yml", project_name="lana-bank")
docker_groups = {
    "auth": ["kratos-admin", "kratos-admin-pg", "kratos-customer", "kratos-customer-pg", "oathkeeper", "mailhog"],
    "otel": ["otel-agent"],
    "core": ["core-pg"],
    "reporting": ["meltano"],
}

for service, deps in docker_groups.items():
    for dep in deps:
        dc_resource(dep, labels=[service])

bfx_local_price = os.getenv("BFX_LOCAL_PRICE", "1")
serve_env_core = {
    "PG_CON": "postgres://user:password@localhost:5433/pg",
    "OTEL_EXPORTER_OTLP_ENDPOINT": "http://localhost:4317",
}
if bfx_local_price != None:
    serve_env_core["BFX_LOCAL_PRICE"] = bfx_local_price
local_resource(
    "core",
    labels=["core"],
    serve_cmd="cd .. && make setup-db run-server",
    serve_env=serve_env_core,
    readiness_probe=probe(
        period_secs=5,
        http_get=http_get_action(
            path="/graphql",
            port=5253,
        ),
    ),
    allow_parallel=True,
    resource_deps=[
        "core-pg",
    ],
    links = [
        link("http://localhost:4455/admin/graphql", "playground"),
    ]
)

local_resource(
    "admin-panel",
    labels=["apps"],
    serve_env={
        "NEXT_PUBLIC_BASE_PATH": "/admin",
        "NEXT_PUBLIC_CORE_ADMIN_URL": "/admin/graphql"
    },
    serve_cmd="cd ../apps/admin-panel && pnpm install && pnpm run dev",
    readiness_probe = probe(
        period_secs  = 5,
        http_get = http_get_action(
            path = "/admin",
            port = 4455,
        ),
    ),
    allow_parallel=True,
    resource_deps=[
        "mailhog",
        "core",
    ],
    links = [
        link("http://localhost:4455/admin", "admin-panel"),
    ]
)

local_resource(
    "customer-portal",
    labels=["apps"],
    serve_env={
        "NEXT_PUBLIC_BASE_PATH": "/app",
        "NEXT_PUBLIC_CORE_APP_URL": "/app/graphql"
    },
    serve_cmd="cd ../apps/customer-portal && pnpm install && pnpm run dev",
    allow_parallel=True,
    resource_deps=[
        "mailhog",
        "core",
    ],
    links = [
        link("http://localhost:4455/app", "customer-portal"),
    ]
)
