config {
	type: "operations",
	hasOutput: true,
	description: "Asserts that the value is a valid code in the static data table."
}

CREATE OR REPLACE FUNCTION ${self()} (assert_value STRING, dim_table_name STRING)
RETURNS BOOLEAN
AS (
  (
    CASE
      WHEN dim_table_name = "stg_dim_01_npb4_17_tipos_de_cartera"                         THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_01_npb4_17_tipos_de_cartera')})
      WHEN dim_table_name = "stg_dim_02_npb4_17_tipos_de_activos_de_riesgo"               THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_02_npb4_17_tipos_de_activos_de_riesgo')})
      WHEN dim_table_name = "stg_dim_03_npb4_17_tipos_de_categorias_de_riesgo"            THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_03_npb4_17_tipos_de_categorias_de_riesgo')})
      WHEN dim_table_name = "stg_dim_04_npb4_17_tipos_de_persona"                         THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_04_npb4_17_tipos_de_persona')})
      WHEN dim_table_name = "stg_dim_05_npb4_17_tipos_de_deudores_relacionados"           THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_05_npb4_17_tipos_de_deudores_relacionados')})
      WHEN dim_table_name = "stg_dim_06_npb4_17_tipos_de_identificador"                   THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_06_npb4_17_tipos_de_identificador')})
      WHEN dim_table_name = "stg_dim_07_npb4_17_estados_de_la_referencia"                 THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_07_npb4_17_estados_de_la_referencia')})
      WHEN dim_table_name = "stg_dim_08_npb4_17_formas_de_pago"                           THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_08_npb4_17_formas_de_pago')})
      WHEN dim_table_name = "stg_dim_09_npb4_17_tipos_de_garantias"                       THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_09_npb4_17_tipos_de_garantias')})
      WHEN dim_table_name = "stg_dim_10_npb4_17_garantes_de_la_cartera_pignorada"         THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_10_npb4_17_garantes_de_la_cartera_pignorada')})
      WHEN dim_table_name = "stg_dim_11_npb4_17_departamentos_para_ubicacion_geografica"  THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_11_npb4_17_departamentos_para_ubicacion_geografica')})
      WHEN dim_table_name = "stg_dim_12_npb4_17_cargos_de_junta_directiva"                THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_12_npb4_17_cargos_de_junta_directiva')})
      WHEN dim_table_name = "stg_dim_13_npb4_17_tipos_de_prenda"                          THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_13_npb4_17_tipos_de_prenda')})
      WHEN dim_table_name = "stg_dim_14_npb4_17_municipios"                               THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_14_npb4_17_municipios')})
      WHEN dim_table_name = "stg_dim_15_npb4_17_emisores_de_avales_fianzas_y_cartas"      THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_15_npb4_17_emisores_de_avales_fianzas_y_cartas')})
      WHEN dim_table_name = "stg_dim_16_npb4_17_fondos_de_garantias"                      THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_16_npb4_17_fondos_de_garantias')})
      WHEN dim_table_name = "stg_dim_17_npb4_17_monedas"                                  THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_17_npb4_17_monedas')})
      WHEN dim_table_name = "stg_dim_18_npb4_17_tipos_de_prestamos"                       THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_18_npb4_17_tipos_de_prestamos')})
      WHEN dim_table_name = "stg_dim_19_npb4_17_actividades_economicas"                   THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_19_npb4_17_actividades_economicas')})
      WHEN dim_table_name = "stg_dim_20_npb4_17_tamano_de_empresa"                        THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_20_npb4_17_tamano_de_empresa')})
      WHEN dim_table_name = "stg_dim_21_npb4_17_fuentes_de_recursos"                      THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_21_npb4_17_fuentes_de_recursos')})
      WHEN dim_table_name = "stg_dim_22_npb4_17_uso_del_financiamiento"                   THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_22_npb4_17_uso_del_financiamiento')})
      WHEN dim_table_name = "stg_dim_23_npb4_17_unidad_de_medida"                         THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_23_npb4_17_unidad_de_medida')})
      WHEN dim_table_name = "stg_dim_24_npb4_17_sector_de_destino"                        THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_24_npb4_17_sector_de_destino')})
      WHEN dim_table_name = "stg_dim_25_npb4_17_lista_de_ocupaciones"                     THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_25_npb4_17_lista_de_ocupaciones')})
      WHEN dim_table_name = "stg_dim_26_npb4_17_almacenadoras_de_deposito"                THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_26_npb4_17_almacenadoras_de_deposito')})
      WHEN dim_table_name = "stg_dim_27_npb4_17_identificador_alterno"                    THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_27_npb4_17_identificador_alterno')})
      WHEN dim_table_name = "stg_dim_28_npb4_17_clase_de_tarjeta_de_credito"              THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_28_npb4_17_clase_de_tarjeta_de_credito')})
      WHEN dim_table_name = "stg_dim_29_npb4_17_etapas_del_credito_en_via_judicial"       THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_29_npb4_17_etapas_del_credito_en_via_judicial')})
      WHEN dim_table_name = "stg_dim_30_npb4_17_tipos_de_credito"                         THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_30_npb4_17_tipos_de_credito')})
      WHEN dim_table_name = "stg_dim_31_npb4_17_codigos_de_paises_o_territorios"          THEN COALESCE(CAST(assert_value AS INT64), -1) NOT IN (SELECT `code` FROM ${ref('stg_dim_31_npb4_17_codigos_de_paises_o_territorios')})
      WHEN dim_table_name = "stg_dim_32_npb4_17_programa_de_asistencia_tecnica"           THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('stg_dim_32_npb4_17_programa_de_asistencia_tecnica')})
      ELSE FALSE
    END
  )
);
