config {
	type: "operations",
	hasOutput: true,
	description: "Asserts that the value is a valid code in the static data table."
}

CREATE OR REPLACE FUNCTION ${self()} (descrip STRING, dim_table_name STRING)
RETURNS STRING
AS (
  (
    CASE
      WHEN dim_table_name = "stg_dim_01_npb4_17_tipos_de_cartera"                         THEN (SELECT `code` FROM ${ref('stg_dim_01_npb4_17_tipos_de_cartera')}                                  WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_02_npb4_17_tipos_de_activos_de_riesgo"               THEN (SELECT `code` FROM ${ref('stg_dim_02_npb4_17_tipos_de_activos_de_riesgo')}                        WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_03_npb4_17_tipos_de_categorias_de_riesgo"            THEN (SELECT `code` FROM ${ref('stg_dim_03_npb4_17_tipos_de_categorias_de_riesgo')}                     WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_04_npb4_17_tipos_de_persona"                         THEN (SELECT `code` FROM ${ref('stg_dim_04_npb4_17_tipos_de_persona')}                                  WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_05_npb4_17_tipos_de_deudores_relacionados"           THEN (SELECT `code` FROM ${ref('stg_dim_05_npb4_17_tipos_de_deudores_relacionados')}                    WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_06_npb4_17_tipos_de_identificador"                   THEN (SELECT `code` FROM ${ref('stg_dim_06_npb4_17_tipos_de_identificador')}                            WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_07_npb4_17_estados_de_la_referencia"                 THEN (SELECT `code` FROM ${ref('stg_dim_07_npb4_17_estados_de_la_referencia')}                          WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_08_npb4_17_formas_de_pago"                           THEN (SELECT `code` FROM ${ref('stg_dim_08_npb4_17_formas_de_pago')}                                    WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_09_npb4_17_tipos_de_garantias"                       THEN (SELECT `code` FROM ${ref('stg_dim_09_npb4_17_tipos_de_garantias')}                                WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_10_npb4_17_garantes_de_la_cartera_pignorada"         THEN (SELECT `code` FROM ${ref('stg_dim_10_npb4_17_garantes_de_la_cartera_pignorada')}                  WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_11_npb4_17_departamentos_para_ubicacion_geografica"  THEN (SELECT `code` FROM ${ref('stg_dim_11_npb4_17_departamentos_para_ubicacion_geografica')}           WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_12_npb4_17_cargos_de_junta_directiva"                THEN (SELECT `code` FROM ${ref('stg_dim_12_npb4_17_cargos_de_junta_directiva')}                         WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_13_npb4_17_tipos_de_prenda"                          THEN (SELECT `code` FROM ${ref('stg_dim_13_npb4_17_tipos_de_prenda')}                                   WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_14_npb4_17_municipios"                               THEN (SELECT `code` FROM ${ref('stg_dim_14_npb4_17_municipios')}                                        WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_15_npb4_17_emisores_de_avales_fianzas_y_cartas"      THEN (SELECT `code` FROM ${ref('stg_dim_15_npb4_17_emisores_de_avales_fianzas_y_cartas')}               WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_16_npb4_17_fondos_de_garantias"                      THEN (SELECT `code` FROM ${ref('stg_dim_16_npb4_17_fondos_de_garantias')}                               WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_17_npb4_17_monedas"                                  THEN (SELECT `code` FROM ${ref('stg_dim_17_npb4_17_monedas')}                                           WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_18_npb4_17_tipos_de_prestamos"                       THEN (SELECT `code` FROM ${ref('stg_dim_18_npb4_17_tipos_de_prestamos')}                                WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_19_npb4_17_actividades_economicas"                   THEN (SELECT `code` FROM ${ref('stg_dim_19_npb4_17_actividades_economicas')}                            WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_20_npb4_17_tamano_de_empresa"                        THEN (SELECT `code` FROM ${ref('stg_dim_20_npb4_17_tamano_de_empresa')}                                 WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_21_npb4_17_fuentes_de_recursos"                      THEN (SELECT `code` FROM ${ref('stg_dim_21_npb4_17_fuentes_de_recursos')}                               WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_22_npb4_17_uso_del_financiamiento"                   THEN (SELECT `code` FROM ${ref('stg_dim_22_npb4_17_uso_del_financiamiento')}                            WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_23_npb4_17_unidad_de_medida"                         THEN (SELECT `code` FROM ${ref('stg_dim_23_npb4_17_unidad_de_medida')}                                  WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_24_npb4_17_sector_de_destino"                        THEN (SELECT `code` FROM ${ref('stg_dim_24_npb4_17_sector_de_destino')}                                 WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_25_npb4_17_lista_de_ocupaciones"                     THEN (SELECT `code` FROM ${ref('stg_dim_25_npb4_17_lista_de_ocupaciones')}                              WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_26_npb4_17_almacenadoras_de_deposito"                THEN (SELECT `code` FROM ${ref('stg_dim_26_npb4_17_almacenadoras_de_deposito')}                         WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_27_npb4_17_identificador_alterno"                    THEN (SELECT `code` FROM ${ref('stg_dim_27_npb4_17_identificador_alterno')}                             WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_28_npb4_17_clase_de_tarjeta_de_credito"              THEN (SELECT `code` FROM ${ref('stg_dim_28_npb4_17_clase_de_tarjeta_de_credito')}                       WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_29_npb4_17_etapas_del_credito_en_via_judicial"       THEN (SELECT `code` FROM ${ref('stg_dim_29_npb4_17_etapas_del_credito_en_via_judicial')}                WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_30_npb4_17_tipos_de_credito"                         THEN (SELECT `code` FROM ${ref('stg_dim_30_npb4_17_tipos_de_credito')}                                  WHERE `description` = descrip)
      WHEN dim_table_name = "stg_dim_31_npb4_17_codigos_de_paises_o_territorios"          THEN (SELECT CAST(`code` AS STRING) FROM ${ref('stg_dim_31_npb4_17_codigos_de_paises_o_territorios')}   WHERE `nationality` = descrip OR `country` = descrip)
      WHEN dim_table_name = "stg_dim_32_npb4_17_programa_de_asistencia_tecnica"           THEN (SELECT `code` FROM ${ref('stg_dim_32_npb4_17_programa_de_asistencia_tecnica')}                    WHERE `description` = descrip)
      ELSE NULL
    END
  )
);
