mutation CreditFacilityAccrueInterestTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "CREDIT_FACILITY_ACCRUE_INTEREST"
      description: "Accrue interest from accrual period for credit facility."
      params: [
        {
          name: "creditFacilityInterestReceivableAccount"
          type: UUID
          description: "Credit Facility interest receivable account ID."
        }
        {
          name: "creditFacilityInterestIncomeAccount"
          type: UUID
          description: "Credit Facility interest income earned account id."
        }
        {
          name: "interestAmount"
          type: DECIMAL
          description: "Amount of USD being incurred as interest."
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: "params.creditFacilityInterestIncomeAccount"
          units: "params.interestAmount"
          currency: "'USD'"
          entryType: "'ACCRUE_INCURRED_INTEREST_DR'"
          direction: "DEBIT"
          layer: "PENDING"
        }
        {
          accountId: "params.creditFacilityInterestReceivableAccount"
          units: "params.interestAmount"
          currency: "'USD'"
          entryType: "'ACCRUE_INCURRED_INTEREST_CR'"
          direction: "CREDIT"
          layer: "PENDING"
        }
        {
          accountId: "params.creditFacilityInterestReceivableAccount"
          units: "params.interestAmount"
          currency: "'USD'"
          entryType: "'ACCRUE_INTEREST_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.creditFacilityInterestIncomeAccount"
          units: "params.interestAmount"
          currency: "'USD'"
          entryType: "'ACCRUE_INTEREST_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostCreditFacilityAccrueInterestTransaction(
  $transactionId: UUID!
  $creditFacilityInterestReceivableAccount: UUID!
  $creditFacilityInterestIncomeAccount: UUID!
  $interestAmount: Decimal!
  $externalId: String!
  $effective: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "CREDIT_FACILITY_ACCRUE_INTEREST"
      params: {
        creditFacilityInterestReceivableAccount: $creditFacilityInterestReceivableAccount
        creditFacilityInterestIncomeAccount: $creditFacilityInterestIncomeAccount
        interestAmount: $interestAmount
        externalId: $externalId
        effective: $effective
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
      createdAt
    }
  }
}
