setup: requirements.txt
	# python -m venv venv
	# source venv/bin/activate
	pip install -r requirements.txt

run-sample-ok:
	python3 main.py samples/persona.xml samples/persona.xsd

run-sample-bad:
	python3 main.py samples/persona-bad.xml samples/persona.xsd
