config {
	type: "operations",
	hasOutput: true,
	description: "Asserts that the value is a valid code in the static data table."
}

CREATE OR REPLACE FUNCTION ${self()} (descrip STRING, dim_table_name STRING)
RETURNS STRING
AS (
  (
    CASE
      WHEN dim_table_name = "static_npb4_17_01_tipos_de_cartera"                         THEN (SELECT `code` FROM ${ref('static_npb4_17_01_tipos_de_cartera')}                                  WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_02_tipos_de_activos_de_riesgo"               THEN (SELECT `code` FROM ${ref('static_npb4_17_02_tipos_de_activos_de_riesgo')}                        WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_03_tipos_de_categorias_de_riesgo"            THEN (SELECT `code` FROM ${ref('static_npb4_17_03_tipos_de_categorias_de_riesgo')}                     WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_04_tipos_de_persona"                         THEN (SELECT `code` FROM ${ref('static_npb4_17_04_tipos_de_persona')}                                  WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_05_tipos_de_deudores_relacionados"           THEN (SELECT `code` FROM ${ref('static_npb4_17_05_tipos_de_deudores_relacionados')}                    WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_06_tipos_de_identificador"                   THEN (SELECT `code` FROM ${ref('static_npb4_17_06_tipos_de_identificador')}                            WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_07_estados_de_la_referencia"                 THEN (SELECT `code` FROM ${ref('static_npb4_17_07_estados_de_la_referencia')}                          WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_08_formas_de_pago"                           THEN (SELECT `code` FROM ${ref('static_npb4_17_08_formas_de_pago')}                                    WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_09_tipos_de_garantias"                       THEN (SELECT `code` FROM ${ref('static_npb4_17_09_tipos_de_garantias')}                                WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_10_garantes_de_la_cartera_pignorada"         THEN (SELECT `code` FROM ${ref('static_npb4_17_10_garantes_de_la_cartera_pignorada')}                  WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_11_departamentos_para_ubicacion_geografica"  THEN (SELECT `code` FROM ${ref('static_npb4_17_11_departamentos_para_ubicacion_geografica')}           WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_12_cargos_de_junta_directiva"                THEN (SELECT `code` FROM ${ref('static_npb4_17_12_cargos_de_junta_directiva')}                         WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_13_tipos_de_prenda"                          THEN (SELECT `code` FROM ${ref('static_npb4_17_13_tipos_de_prenda')}                                   WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_14_municipios"                               THEN (SELECT `code` FROM ${ref('static_npb4_17_14_municipios')}                                        WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_15_emisores_de_avales_fianzas_y_cartas"      THEN (SELECT `code` FROM ${ref('static_npb4_17_15_emisores_de_avales_fianzas_y_cartas')}               WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_16_fondos_de_garantias"                      THEN (SELECT `code` FROM ${ref('static_npb4_17_16_fondos_de_garantias')}                               WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_17_monedas"                                  THEN (SELECT `code` FROM ${ref('static_npb4_17_17_monedas')}                                           WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_18_tipos_de_prestamos"                       THEN (SELECT `code` FROM ${ref('static_npb4_17_18_tipos_de_prestamos')}                                WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_19_actividades_economicas"                   THEN (SELECT `code` FROM ${ref('static_npb4_17_19_actividades_economicas')}                            WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_20_tamano_de_empresa"                        THEN (SELECT `code` FROM ${ref('static_npb4_17_20_tamano_de_empresa')}                                 WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_21_fuentes_de_recursos"                      THEN (SELECT `code` FROM ${ref('static_npb4_17_21_fuentes_de_recursos')}                               WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_22_uso_del_financiamiento"                   THEN (SELECT `code` FROM ${ref('static_npb4_17_22_uso_del_financiamiento')}                            WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_23_unidad_de_medida"                         THEN (SELECT `code` FROM ${ref('static_npb4_17_23_unidad_de_medida')}                                  WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_24_sector_de_destino"                        THEN (SELECT `code` FROM ${ref('static_npb4_17_24_sector_de_destino')}                                 WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_25_lista_de_ocupaciones"                     THEN (SELECT `code` FROM ${ref('static_npb4_17_25_lista_de_ocupaciones')}                              WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_26_almacenadoras_de_deposito"                THEN (SELECT `code` FROM ${ref('static_npb4_17_26_almacenadoras_de_deposito')}                         WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_27_identificador_alterno"                    THEN (SELECT `code` FROM ${ref('static_npb4_17_27_identificador_alterno')}                             WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_28_clase_de_tarjeta_de_credito"              THEN (SELECT `code` FROM ${ref('static_npb4_17_28_clase_de_tarjeta_de_credito')}                       WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_29_etapas_del_credito_en_via_judicial"       THEN (SELECT `code` FROM ${ref('static_npb4_17_29_etapas_del_credito_en_via_judicial')}                WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_30_tipos_de_credito"                         THEN (SELECT `code` FROM ${ref('static_npb4_17_30_tipos_de_credito')}                                  WHERE `description` = descrip)
      WHEN dim_table_name = "static_npb4_17_31_codigos_de_paises_o_territorios"          THEN (SELECT CAST(`code` AS STRING) FROM ${ref('static_npb4_17_31_codigos_de_paises_o_territorios')}   WHERE `nationality` = descrip OR `country` = descrip)
      WHEN dim_table_name = "static_npb4_17_32_programa_de_asistencia_tecnica"           THEN (SELECT `code` FROM ${ref('static_npb4_17_32_programa_de_asistencia_tecnica')}                    WHERE `description` = descrip)
      ELSE NULL
    END
  )
);
