config {
	type: "operations",
	hasOutput: true,
	description: "Asserts that the value is a valid code in the static data table."
}

CREATE OR REPLACE FUNCTION ${self()} (assert_value STRING, dim_table_name STRING)
RETURNS BOOLEAN
AS (
  (
    CASE
      WHEN dim_table_name = "static_npb4_17_01_tipos_de_cartera"                         THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_01_tipos_de_cartera')})
      WHEN dim_table_name = "static_npb4_17_02_tipos_de_activos_de_riesgo"               THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_02_tipos_de_activos_de_riesgo')})
      WHEN dim_table_name = "static_npb4_17_03_tipos_de_categorias_de_riesgo"            THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_03_tipos_de_categorias_de_riesgo')})
      WHEN dim_table_name = "static_npb4_17_04_tipos_de_persona"                         THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_04_tipos_de_persona')})
      WHEN dim_table_name = "static_npb4_17_05_tipos_de_deudores_relacionados"           THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_05_tipos_de_deudores_relacionados')})
      WHEN dim_table_name = "static_npb4_17_06_tipos_de_identificador"                   THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_06_tipos_de_identificador')})
      WHEN dim_table_name = "static_npb4_17_07_estados_de_la_referencia"                 THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_07_estados_de_la_referencia')})
      WHEN dim_table_name = "static_npb4_17_08_formas_de_pago"                           THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_08_formas_de_pago')})
      WHEN dim_table_name = "static_npb4_17_09_tipos_de_garantias"                       THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_09_tipos_de_garantias')})
      WHEN dim_table_name = "static_npb4_17_10_garantes_de_la_cartera_pignorada"         THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_10_garantes_de_la_cartera_pignorada')})
      WHEN dim_table_name = "static_npb4_17_11_departamentos_para_ubicacion_geografica"  THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_11_departamentos_para_ubicacion_geografica')})
      WHEN dim_table_name = "static_npb4_17_12_cargos_de_junta_directiva"                THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_12_cargos_de_junta_directiva')})
      WHEN dim_table_name = "static_npb4_17_13_tipos_de_prenda"                          THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_13_tipos_de_prenda')})
      WHEN dim_table_name = "static_npb4_17_14_municipios"                               THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_14_municipios')})
      WHEN dim_table_name = "static_npb4_17_15_emisores_de_avales_fianzas_y_cartas"      THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_15_emisores_de_avales_fianzas_y_cartas')})
      WHEN dim_table_name = "static_npb4_17_16_fondos_de_garantias"                      THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_16_fondos_de_garantias')})
      WHEN dim_table_name = "static_npb4_17_17_monedas"                                  THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_17_monedas')})
      WHEN dim_table_name = "static_npb4_17_18_tipos_de_prestamos"                       THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_18_tipos_de_prestamos')})
      WHEN dim_table_name = "static_npb4_17_19_actividades_economicas"                   THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_19_actividades_economicas')})
      WHEN dim_table_name = "static_npb4_17_20_tamano_de_empresa"                        THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_20_tamano_de_empresa')})
      WHEN dim_table_name = "static_npb4_17_21_fuentes_de_recursos"                      THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_21_fuentes_de_recursos')})
      WHEN dim_table_name = "static_npb4_17_22_uso_del_financiamiento"                   THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_22_uso_del_financiamiento')})
      WHEN dim_table_name = "static_npb4_17_23_unidad_de_medida"                         THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_23_unidad_de_medida')})
      WHEN dim_table_name = "static_npb4_17_24_sector_de_destino"                        THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_24_sector_de_destino')})
      WHEN dim_table_name = "static_npb4_17_25_lista_de_ocupaciones"                     THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_25_lista_de_ocupaciones')})
      WHEN dim_table_name = "static_npb4_17_26_almacenadoras_de_deposito"                THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_26_almacenadoras_de_deposito')})
      WHEN dim_table_name = "static_npb4_17_27_identificador_alterno"                    THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_27_identificador_alterno')})
      WHEN dim_table_name = "static_npb4_17_28_clase_de_tarjeta_de_credito"              THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_28_clase_de_tarjeta_de_credito')})
      WHEN dim_table_name = "static_npb4_17_29_etapas_del_credito_en_via_judicial"       THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_29_etapas_del_credito_en_via_judicial')})
      WHEN dim_table_name = "static_npb4_17_30_tipos_de_credito"                         THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_30_tipos_de_credito')})
      WHEN dim_table_name = "static_npb4_17_31_codigos_de_paises_o_territorios"          THEN COALESCE(CAST(assert_value AS INT64), -1) NOT IN (SELECT `code` FROM ${ref('static_npb4_17_31_codigos_de_paises_o_territorios')})
      WHEN dim_table_name = "static_npb4_17_32_programa_de_asistencia_tecnica"           THEN COALESCE(assert_value, '~') NOT IN (SELECT `code` FROM ${ref('static_npb4_17_32_programa_de_asistencia_tecnica')})
      ELSE FALSE
    END
  )
);
