mutation CreateCreditFacilityAccounts(
  $facilityCollateralAccountId: UUID!
  $facilityCollateralAccountCode: String!
  $facilityCollateralAccountName: String!
  $facilitiesCollateralControlAccountSetId: UUID!
  $facilityAccountId: UUID!
  $facilityAccountCode: String!
  $facilityAccountName: String!
  $facilitiesControlAccountSetId: UUID!
  $facilityDisbursedReceivableAccountId: UUID!
  $facilityDisbursedReceivableAccountCode: String!
  $facilityDisbursedReceivableAccountName: String!
  $facilitiesDisbursedReceivableControlAccountSetId: UUID!
  $facilityInterestReceivableAccountId: UUID!
  $facilityInterestReceivableAccountCode: String!
  $facilityInterestReceivableAccountName: String!
  $facilitiesInterestReceivableControlAccountSetId: UUID!
  $interestAccountId: UUID!
  $interestAccountCode: String!
  $interestAccountName: String!
  $interestRevenueControlAccountSetId: UUID!
) {
  collateral: accountCreate(
    input: {
      accountId: $facilityCollateralAccountId
      code: $facilityCollateralAccountCode
      name: $facilityCollateralAccountName
      accountSetIds: [$facilitiesCollateralControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  facility: accountCreate(
    input: {
      accountId: $facilityAccountId
      code: $facilityAccountCode
      name: $facilityAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$facilitiesControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  disbursedReceivable: accountCreate(
    input: {
      accountId: $facilityDisbursedReceivableAccountId
      code: $facilityDisbursedReceivableAccountCode
      name: $facilityDisbursedReceivableAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$facilitiesDisbursedReceivableControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  interestReceivable: accountCreate(
    input: {
      accountId: $facilityInterestReceivableAccountId
      code: $facilityInterestReceivableAccountCode
      name: $facilityInterestReceivableAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$facilitiesInterestReceivableControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  interest: accountCreate(
    input: {
      accountId: $interestAccountId
      code: $interestAccountCode
      name: $interestAccountName
      accountSetIds: [$interestRevenueControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
}
