config {
	type: "table",
}

SELECT 'CD' AS code, 'Crédito decreciente' AS description UNION ALL
SELECT 'CR', 'Crédito rotativo' UNION ALL
SELECT 'NR', 'Decreciente no rotativo' UNION ALL
SELECT 'TC', 'Tarjeta de crédito' UNION ALL
SELECT 'CI', 'Créditos interbancarios' UNION ALL
SELECT 'DI', 'Descuento de letras o factoraje' UNION ALL
SELECT 'CT', 'Créditos de tesorería' UNION ALL
SELECT 'NA', 'Créditos Nuevo amanecer' UNION ALL
SELECT 'SA', 'Sobregiros autorizados' UNION ALL
SELECT 'SO', 'Sobregiros ocasionales' UNION ALL
SELECT 'CU', 'Créditos puente'
