config {
	type: "table",
}

SELECT '001' AS code, 'Administrador' AS description UNION ALL
SELECT '002', 'Agente de aduana' UNION ALL
SELECT '003', 'Agente de ventas' UNION ALL
SELECT '004', 'Agricultor' UNION ALL
SELECT '005', 'Agrónomo' UNION ALL
SELECT '006', 'Albañil' UNION ALL
SELECT '007', 'Ama de casa' UNION ALL
SELECT '008', 'Analista de computación' UNION ALL
SELECT '009', 'Apicultor' UNION ALL
SELECT '010', 'Arquitecto' UNION ALL
SELECT '011', 'Artesano' UNION ALL
SELECT '012', 'Ascensorista' UNION ALL
SELECT '013', 'Asistente de abogacía' UNION ALL
SELECT '014', 'Asistente de auditoría' UNION ALL
SELECT '015', 'Asistente de consultorio médico' UNION ALL
SELECT '016', 'Asesor' UNION ALL
SELECT '017', 'Auditor' UNION ALL
SELECT '018', 'Auxiliar de contabilidad' UNION ALL
SELECT '019', 'Auxiliar dental' UNION ALL
SELECT '020', 'Auxiliar de cocina' UNION ALL
SELECT '021', 'Ayudante de mecánico general' UNION ALL
SELECT '022', 'Ayudante operario, construcción' UNION ALL
SELECT '023', 'Bachiller' UNION ALL
SELECT '024', 'Barbero' UNION ALL
SELECT '025', 'Bartender' UNION ALL
SELECT '026', 'Bodeguero' UNION ALL
SELECT '027', 'Bombero' UNION ALL
SELECT '028', 'Botones' UNION ALL
SELECT '029', 'Cajero' UNION ALL
SELECT '030', 'Camarógrafo de prensa' UNION ALL
SELECT '031', 'Cantante de música' UNION ALL
SELECT '032', 'Carnicero (destazador)' UNION ALL
SELECT '033', 'Carpintero' UNION ALL
SELECT '034', 'Catedrático' UNION ALL
SELECT '035', 'Cerrajero' UNION ALL
SELECT '036', 'Chequeador de buses' UNION ALL
SELECT '037', 'Chofer de bus' UNION ALL
SELECT '038', 'Chofer de tráiler' UNION ALL
SELECT '039', 'Chofer de vehículo' UNION ALL
SELECT '040', 'Cobrador' UNION ALL
SELECT '041', 'Cocinero' UNION ALL
SELECT '042', 'Comerciante' UNION ALL
SELECT '043', 'Constructor' UNION ALL
SELECT '044', 'Consultor' UNION ALL
SELECT '045', 'Contador' UNION ALL
SELECT '046', 'Corredor de seguros' UNION ALL
SELECT '047', 'Cosmetóloga' UNION ALL
SELECT '048', 'Costurera (modista)' UNION ALL
SELECT '049', 'Dependiente de mostrador' UNION ALL
SELECT '050', 'Despachador agencia de aduana' UNION ALL
SELECT '051', 'Dibujante de artes gráficas' UNION ALL
SELECT '052', 'Dibujante ingeniería, arquitectura' UNION ALL
SELECT '053', 'Digitador' UNION ALL
SELECT '054', 'Diputado' UNION ALL
SELECT '055', 'Director centro educativo' UNION ALL
SELECT '056', 'Diseñador' UNION ALL
SELECT '057', 'Ebanista' UNION ALL
SELECT '058', 'Electricista' UNION ALL
SELECT '059', 'Empacador, etiquetador' UNION ALL
SELECT '060', 'Empleada doméstica' UNION ALL
SELECT '061', 'Empleado de despacho' UNION ALL
SELECT '062', 'Empleado sector público' UNION ALL
SELECT '063', 'Empresario' UNION ALL
SELECT '064', 'Encargado indicar acomodo parqueo' UNION ALL
SELECT '065', 'Encargado de limpieza en general' UNION ALL
SELECT '066', 'Encargado limpieza en piscinas' UNION ALL
SELECT '067', 'Encargado mantenimiento correctivo cómputo' UNION ALL
SELECT '068', 'Encargado mantenimiento preventivo cómputo' UNION ALL
SELECT '069', 'Encargado de poner discos (discjockey)' UNION ALL
SELECT '070', 'Encargado de fotocopiadora' UNION ALL
SELECT '071', 'Encargado mantenimiento edificio' UNION ALL
SELECT '072', 'Encuadernador-empastador' UNION ALL
SELECT '073', 'Encuestador' UNION ALL
SELECT '074', 'Enderezador automotriz' UNION ALL
SELECT '075', 'Engrasador de autos' UNION ALL
SELECT '076', 'Ensamblador de computadoras' UNION ALL
SELECT '077', 'Estampador en textil (serigrafía)' UNION ALL
SELECT '078', 'Estilista' UNION ALL
SELECT '079', 'Florista' UNION ALL
SELECT '080', 'Fontanero' UNION ALL
SELECT '081', 'Fotógrafo' UNION ALL
SELECT '082', 'Fumigador' UNION ALL
SELECT '083', 'Fundidor' UNION ALL
SELECT '084', 'Guía turístico' UNION ALL
SELECT '085', 'Hojalatero' UNION ALL
SELECT '086', 'Horneador' UNION ALL
SELECT '087', 'Ingeniero' UNION ALL
SELECT '088', 'Instructor de bailes' UNION ALL
SELECT '089', 'Jardinero' UNION ALL
SELECT '090', 'Jefe de cocina (chef)' UNION ALL
SELECT '091', 'Joyero' UNION ALL
SELECT '092', 'Laboratorista clínico' UNION ALL
SELECT '093', 'Lavador de baños, pisos, etc.' UNION ALL
SELECT '094', 'Lavador de cabellos' UNION ALL
SELECT '095', 'Lavador de carros' UNION ALL
SELECT '096', 'Levantador de textos (artes gráficas)' UNION ALL
SELECT '097', 'Locutor de radioemisora' UNION ALL
SELECT '098', 'Locutor de televisión' UNION ALL
SELECT '099', 'Llanteros' UNION ALL
SELECT '100', 'Maestro' UNION ALL
SELECT '101', 'Maestro de obras' UNION ALL
SELECT '102', 'Mecánico' UNION ALL
SELECT '103', 'Mecánico dental' UNION ALL
SELECT '104', 'Mensajero' UNION ALL
SELECT '105', 'Mesero' UNION ALL
SELECT '106', 'Oficinista' UNION ALL
SELECT '107', 'Operador de computación' UNION ALL
SELECT '108', 'Operador de grúa estacionaria' UNION ALL
SELECT '109', 'Operador de máquina de lavar ropa' UNION ALL
SELECT '110', 'Operador de máquina en general' UNION ALL
SELECT '111', 'Operador de planta transmisora' UNION ALL
SELECT '112', 'Operador de radio-taxi' UNION ALL
SELECT '113', 'Operador escogedoras de café' UNION ALL
SELECT '114', 'Operario' UNION ALL
SELECT '115', 'Ordenanza' UNION ALL
SELECT '116', 'Ordeñador' UNION ALL
SELECT '117', 'Panadero' UNION ALL
SELECT '118', 'Pastelero' UNION ALL
SELECT '119', 'Peluquero' UNION ALL
SELECT '120', 'Periodista' UNION ALL
SELECT '121', 'Pintor' UNION ALL
SELECT '122', 'Portero' UNION ALL
SELECT '123', 'Recamarera' UNION ALL
SELECT '124', 'Recepcionista' UNION ALL
SELECT '125', 'Recolector de café' UNION ALL
SELECT '126', 'Relojero' UNION ALL
SELECT '127', 'Sastre' UNION ALL
SELECT '128', 'Secretaria' UNION ALL
SELECT '129', 'Soldador en general' UNION ALL
SELECT '130', 'Tapicero' UNION ALL
SELECT '131', 'Taxista' UNION ALL
SELECT '132', 'Técnico en educación superior' UNION ALL
SELECT '133', 'Técnico en aparatos ortopédicos' UNION ALL
SELECT '134', 'Técnico en refrigeración' UNION ALL
SELECT '135', 'Técnico máquinas coser industrial' UNION ALL
SELECT '136', 'Técnico en salud' UNION ALL
SELECT '137', 'Telefonista' UNION ALL
SELECT '138', 'Tornero en madera' UNION ALL
SELECT '139', 'Tornero en metal' UNION ALL
SELECT '140', 'Verdulero' UNION ALL
SELECT '141', 'Zapatero' UNION ALL
SELECT '142', 'Otras ocupaciones' UNION ALL
SELECT '143', 'Doctor en medicina'
