config {
	type: "table",
}

SELECT "01" AS code,"Cartera propia" AS description UNION ALL
SELECT '02', 'Cartera propia 292 o. 263' UNION ALL
SELECT '03', 'Cartera en administración FFRAP' UNION ALL
SELECT '04', 'Cartera FOSAFFI - Venta de acciones' UNION ALL
SELECT '05', 'Cartera FOSAFFI permutada' UNION ALL
SELECT '06', 'Cartera FOSAFFI cedida' UNION ALL
SELECT '07', 'Cartera FOSAFFI permutada 292' UNION ALL
SELECT '08', 'Cartera FOSAFFI cedida 292' UNION ALL
SELECT '09', 'Cartera FOSAFFI patrimonial EX-INCAFE' UNION ALL
SELECT '10', 'Cartera FOSAFFI patrimonial EX-BANAFI' UNION ALL
SELECT '11', 'Cartera FOSAFFI transferida EX-BANCAPI' UNION ALL
SELECT '12', 'Cartera FOSAFFI transferida EX-BANCREPO' UNION ALL
SELECT '13', 'Cartera FOSAFFI transferida EX-MERCANTIL' UNION ALL
SELECT '14', 'Cartera FOSAFFI transferida Banco Hipotecario' UNION ALL
SELECT '15', 'Cartera FOSAFFI transferida BANAFI' UNION ALL
SELECT '16', 'Cartera MIPLAN' UNION ALL
SELECT '17', 'Cartera Nuevo Amanecer' UNION ALL
SELECT '18', 'Cartera FOSAFFI patrimonial EX-INCAFE 292' UNION ALL
SELECT '19', 'Cartera FOSAFFI patrimonial EX-BANAFI 292' UNION ALL
SELECT '20', 'Cartera FOSAFFI transferida EX-BANCAPI 292' UNION ALL
SELECT '21', 'Cartera FOSAFFI transferida EX-BANCREPO 292' UNION ALL
SELECT '22', 'Cartera FOSAFFI transferida EX-MERCANTIL 292' UNION ALL
SELECT '23', 'Cartera FOSAFFI transferida Banco Hipotecario 292' UNION ALL
SELECT '24', 'Cartera FOSAFFI transferida BANAFI 292' UNION ALL
SELECT '25', 'Cartera FOSAFFI transferida CREDISA' UNION ALL
SELECT '26', 'FIDEAGRO 292' UNION ALL
SELECT '27', 'FIDEAGRO' UNION ALL
SELECT '28', 'FICAFE' UNION ALL
SELECT '29', 'FEPADA' UNION ALL
SELECT '30', 'Cartera en administración BCR-BID' UNION ALL
SELECT '31', 'Derogado. (21)' UNION ALL
SELECT '32', 'Cartera fondo especial FONAVIPO' UNION ALL
SELECT '33', 'Cartera propia Ley Acceso al Crédito (19)' UNION ALL
SELECT '98', 'Otras 292' UNION ALL
SELECT '99', 'Otras'
