config {
	type: "table",
	description: "Errors found in Regulatory Report referencia.xml of norm NPB4-17"
}

WITH latest AS (
	SELECT *
	FROM ${ref("report_02_npb4_17_referencia_xml")}(CURRENT_TIMESTAMP())
)

SELECT *, "udf_nbp4_17_assert_niu_number" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_niu_number')}(`nit_deudor`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_uppercase_alphanum num_referencia" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_uppercase_alphanum')}(`num_referencia`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_dollar_number monto_referencia" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_dollar_number')}(`num_referencia`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_dollar_number saldo_referencia" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_dollar_number')}(`saldo_referencia`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_dollar_number saldo_vigente_k" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_dollar_number')}(`saldo_vigente_k`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_dollar_number saldo_vencido_k" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_dollar_number')}(`saldo_vencido_k`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_dollar_number saldo_vigente_i" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_dollar_number')}(`saldo_vigente_i`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_dollar_number saldo_vencido_i" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_dollar_number')}(`saldo_vencido_i`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_dollar_number abono_deposito" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_dollar_number')}(`abono_deposito`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_date fecha_otorgamiento" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_date')}(`fecha_otorgamiento`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_date fecha_vencimiento" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_date')}(`fecha_vencimiento`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_date fecha_castigo" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_date')}(`fecha_castigo`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number saldo_mora_k" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`saldo_mora_k`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number saldo_mora_i" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`saldo_mora_i`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_integer dias_mora_k" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_integer')}(`dias_mora_k`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_integer dias_mora_i" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_integer')}(`dias_mora_i`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_date fecha_inicio_mora_k" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_date')}(`fecha_inicio_mora_k`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_date fecha_inicio_mora_i" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_date')}(`fecha_inicio_mora_i`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_integer periodo_gracia_k" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_integer')}(`periodo_gracia_k`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_integer periodo_gracia_i" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_integer')}(`periodo_gracia_i`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_percent_number tasa_interes" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_percent_number')}(`tasa_interes`, 6)

UNION ALL

SELECT *, "udf_nbp4_17_assert_percent_number tasa_contractual" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_percent_number')}(`tasa_contractual`, 6)

UNION ALL

SELECT *, "udf_nbp4_17_assert_percent_number tasa_referencia" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_percent_number')}(`tasa_referencia`, 6)

UNION ALL

SELECT *, "udf_nbp4_17_assert_percent_number tasa_efectiva" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_percent_number')}(`tasa_efectiva`, 6)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_date ultima_fecha_venc" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_date')}(`ultima_fecha_venc`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_integer dias_prorroga" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_integer')}(`dias_prorroga`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number monto_desembolsado" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`monto_desembolsado`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_date fecha_ultimo_pago_k" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_date')}(`fecha_ultimo_pago_k`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_date fecha_ultimo_pago_i" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_date')}(`fecha_ultimo_pago_i`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_integer dia_pago_k" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_integer')}(`dia_pago_k`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_integer dia_pago_i" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_integer')}(`dia_pago_i`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_integer cuota_mora_k" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_integer')}(`cuota_mora_k`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_integer cuota_mora_i" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_integer')}(`cuota_mora_i`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number monto_cuota" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`monto_cuota`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_integer cuenta_contable_k" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_integer')}(`cuenta_contable_k`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_integer cuenta_contable_i" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_integer')}(`cuenta_contable_i`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_date fecha_cancelacion" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_date')}(`fecha_cancelacion`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number adelanto_capital" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`adelanto_capital`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number riesgo_neto" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`riesgo_neto`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number saldo_seguro" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`saldo_seguro`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number saldo_costas_procesales" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`saldo_costas_procesales`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number valor_garantia_cons" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`valor_garantia_cons`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number reserva_referencia" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`reserva_referencia`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_date fecha_demanda" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_date')}(`fecha_demanda`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_integer plazo_credito" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_integer')}(`plazo_credito`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number reserva_constituir" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`reserva_constituir`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_percent_number porcentaje_reserva" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_percent_number')}(`porcentaje_reserva`, 6)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number pago_cuota" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`pago_cuota`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_date fecha_pago" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_date')}(`fecha_pago`)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_percent_number porcenta_reserva_descon" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_percent_number')}(`porcenta_reserva_descon`, 6)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_percent_number porcenta_adiciona_descon" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_percent_number')}(`porcenta_adiciona_descon`, 6)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_percent_number porc_reserva_referencia" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_percent_number')}(`porc_reserva_referencia`, 6)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number calculo_brecha" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`calculo_brecha`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_dollar_number ajuste_brecha" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_dollar_number')}(`ajuste_brecha`, 13)

UNION ALL

SELECT *, "udf_nbp4_17_assert_nullable_date ajuste_brecha" AS error
FROM latest
WHERE ${ref('udf_nbp4_17_assert_nullable_date')}(`fecha_cump_cafe`)
