#@ load("@ytt:data", "data")

#@ load("vendor/pipeline-fragments.lib.yml",
#@   "build_edge_image",
#@   "public_docker_registry",
#@   "nodejs_task_image_config",
#@   "check_code",
#@   "docker_host_pool",
#@   "test_on_docker_host",
#@   "repo_resource",
#@   "edge_image_resource",
#@   "version_resource",
#@   "gh_release_resource",
#@   "pipeline_tasks_resource",
#@   "release_task_image_config",
#@   "rust_task_image_config",
#@   "charts_repo_resource",
#@   "charts_repo_bot_branch",
#@   "slack_resource_type",
#@   "slack_resource",
#@   "slack_failure_notification",
#@   "private_docker_registry"
#@ )

#@ load("app-template.lib.yml",
#@   "app_src_resource",
#@   "build_app_edge_image_name",
#@   "app_edge_image_resource_name",
#@   "app_latest_image_resource_name",
#@   "app_latest_image",
#@   "build_app_edge_image",
#@   "app_edge_image"
#@ )

#@ def on_nix_host(name, cmd):
#@ params = {}
#@ params["REPO_PATH"] = data.values.gh_repository
#@ params["GOOGLE_CREDENTIALS"] = "((staging-gcp-creds.creds_json))"
#@ params["SSH_PRIVATE_KEY"] = "((staging-ssh.ssh_private_key))"
#@ params["SSH_PUB_KEY"] = "((staging-ssh.ssh_public_key))"
#@ params["CMD"] = cmd
name: #@ name
serial: true
plan:
  - { put: nix-host, params: { acquire: true } }
  - in_parallel:
      - get: repo
        trigger: true
      - { get: pipeline-tasks }
  - task: #@ name
    attempts: 2
    timeout: 18m
    tags: ["galoy-staging"]
    config:
      platform: linux
      image_resource: #@ rust_task_image_config()
      inputs:
        - name: pipeline-tasks
        - name: nix-host
        - name: repo
          path: #@ data.values.gh_repository
      params: #@ params
      run:
        path: pipeline-tasks/ci/tasks/run-on-nix-host.sh
    ensure:
      put: nix-host
      params:
        release: nix-host
#@ end

groups:
  - name: lana-bank
    jobs:
      - check-code
      - integration-tests
      - bats-tests
      - build-edge-image
      - release
      - release-docker
      - set-dev-version
      - bump-image-in-chart
      -  #@ build_app_edge_image_name("admin-panel")
      -  #@ build_app_edge_image_name("customer-portal")

jobs:
  -  #@ check_code()
  -  #@ on_nix_host("integration-tests", "make test-in-ci")
  -  #@ on_nix_host("bats-tests", "make e2e-in-ci")
  -  #@ build_edge_image()

  - name: release
    serial: true
    plan:
      - in_parallel:
          - get: repo
            passed:
              - check-code
              - integration-tests
              - bats-tests
          - get: pipeline-tasks
          - get: version
          - get: #@ app_edge_image_resource_name("admin-panel")
            passed:
              -  #@ build_app_edge_image_name("admin-panel")
          - get: #@ app_edge_image_resource_name("customer-portal")
            passed:
              -  #@ build_app_edge_image_name("customer-portal")
      - task: prep-release
        config:
          platform: linux
          image_resource: #@ release_task_image_config()
          inputs:
            - name: pipeline-tasks
            - name: repo
            - name: version
          outputs:
            - name: version
            - name: artifacts
          run:
            path: pipeline-tasks/ci/vendor/tasks/prep-release-src.sh
      - task: build-static-release
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: clux/muslrust, tag: 1.78.0-stable }
          inputs:
            - name: version
            - name: pipeline-tasks
            - name: repo
          outputs:
            - name: x86_64-unknown-linux-musl
          caches:
            - path: cargo-home
            - path: cargo-target-dir
          params:
            TARGET: x86_64-unknown-linux-musl
            OUT: x86_64-unknown-linux-musl
          run:
            path: pipeline-tasks/ci/tasks/build-release.sh
      - put: repo
        params:
          tag: artifacts/gh-release-tag
          only_tag: true
          repository: repo
      - task: github-release
        config:
          image_resource: #@ rust_task_image_config()
          platform: linux
          inputs:
            - name: x86_64-unknown-linux-musl
            - name: version
            - name: pipeline-tasks
            - name: artifacts
          outputs:
            - name: artifacts
          params:
            BRANCH: #@ data.values.git_branch
          run:
            path: pipeline-tasks/ci/tasks/github-release.sh
      - put: gh-release
        params:
          name: artifacts/gh-release-name
          tag: artifacts/gh-release-tag
          body: artifacts/gh-release-notes.md
          globs: [artifacts/binaries/*]
      - put: version
        params:
          file: version/version

  - name: release-docker
    serial: true
    plan:
      - in_parallel:
          - get: repo
            passed:
              - release
          - get: version
            passed:
              - release
            trigger: true
          - get: pipeline-tasks
          - get: #@ app_edge_image_resource_name("admin-panel")
            passed:
              - release
            params:
              format: oci
          - get: #@ app_edge_image_resource_name("customer-portal")
            passed:
              - release
            params:
              format: oci
      - task: prepare-docker-build
        config:
          platform: linux
          image_resource: #@ rust_task_image_config()
          inputs:
            - name: pipeline-tasks
            - name: version
            - name: repo
          outputs:
            - name: repo
          params:
            GH_APP_ID: #@ data.values.github_app_id
            GH_APP_PRIVATE_KEY: #@ data.values.github_app_private_key
          run:
            path: pipeline-tasks/ci/tasks/prep-docker-build-env.sh
      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          inputs:
            - name: repo
          outputs:
            - name: image
          params:
            CONTEXT: repo
            BUILD_ARGS_FILE: repo/.env
            DOCKERFILE: "repo/Dockerfile.release"
          run:
            path: build
      - in_parallel:
          - put: latest-image
            params:
              image: image/image.tar
              additional_tags: version/version
          - put: #@ app_latest_image_resource_name("admin-panel")
            params:
              image: #@ app_edge_image_resource_name("admin-panel") + "/image.tar"
              additional_tags: version/version
          - put: #@ app_latest_image_resource_name("customer-portal")
            params:
              image: #@ app_edge_image_resource_name("customer-portal") + "/image.tar"
              additional_tags: version/version

  - name: set-dev-version
    plan:
      - in_parallel:
          - { get: repo, passed: [release] }
          - { get: pipeline-tasks }
          - get: version
            trigger: true
            params: { bump: patch }
            passed: [release]
      - task: set-dev-version
        config:
          image_resource: #@ rust_task_image_config()
          platform: linux
          inputs:
            - name: version
            - name: repo
            - name: pipeline-tasks
          outputs:
            - name: repo
          run:
            path: pipeline-tasks/ci/tasks/set-dev-version.sh
          params:
            BRANCH: #@ data.values.git_branch
      - put: repo
        params:
          repository: repo
          rebase: true

  - name: bump-image-in-chart
    plan:
      - in_parallel:
          - get: latest-image
            passed: [release-docker]
            params: { skip_download: true }
          - get: #@ app_latest_image_resource_name("admin-panel")
          - get: #@ app_latest_image_resource_name("customer-portal")
            passed: [release-docker]
            params: { skip_download: true }
          - get: repo
            trigger: true
            passed: [release-docker]
          - get: version
            trigger: true
            passed: [release-docker]
          - get: charts-repo
            params: { skip_download: true }
          - get: pipeline-tasks
      - task: bump-image-digest-in-values
        config:
          platform: linux
          image_resource: #@ rust_task_image_config()
          inputs:
            - name: repo
            - name: latest-image
            - name: #@ app_latest_image_resource_name("admin-panel")
            - name: #@ app_latest_image_resource_name("customer-portal")
            - name: pipeline-tasks
            - name: charts-repo
            - name: version
          outputs:
            - name: charts-repo
          params:
            BRANCH: #@ data.values.git_charts_branch
            CHARTS_SUBDIR: lana-bank
          run:
            path: pipeline-tasks/ci/tasks/bump-image-digest.sh
      - put: charts-repo-bot-branch
        params:
          repository: charts-repo
          force: true
      - task: open-charts-pr
        config:
          platform: linux
          image_resource: #@ rust_task_image_config()
          inputs:
            - name: pipeline-tasks
            - name: latest-image
            - name: charts-repo
            - name: repo
          params:
            GH_APP_ID: #@ data.values.github_app_id
            GH_APP_PRIVATE_KEY: #@ data.values.github_app_private_key
            BRANCH: #@ data.values.git_charts_branch
            BOT_BRANCH: #@ data.values.git_charts_bot_branch
            CHARTS_SUBDIR: lana-bank
          run:
            path: pipeline-tasks/ci/tasks/chart-open-charts-pr.sh

  -  #@ build_app_edge_image("admin-panel")
  -  #@ build_app_edge_image("customer-portal")

resources:
  - name: repo
    type: git
    source:
      ignore_paths:
        - "ci/*[^md]"
        - apps/**/*
      fetch_tags: true
      uri: #@ data.values.git_uri
      branch: #@ data.values.git_branch
      private_key: #@ data.values.github_private_key
    webhook_token: ((webhook.secret))

  - name: latest-image
    type: registry-image
    source:
      tag: latest
      username: #@ data.values.docker_registry_user
      password: #@ data.values.docker_registry_password
      repository: #@ private_docker_registry() + "/" + data.values.gh_repository

  - name: nix-host
    type: pool
    source:
      uri: git@github.com:GaloyMoney/galoy-concourse-locks.git
      branch: main
      pool: docker-hosts
      private_key: #@ data.values.github_private_key

  -  #@ pipeline_tasks_resource()
  -  #@ slack_resource()
  -  #@ edge_image_resource(publicRepo=False)
  -  #@ version_resource()
  -  #@ gh_release_resource()
  -  #@ charts_repo_bot_branch()
  -  #@ charts_repo_resource()
  -  #@ app_src_resource("admin-panel", "main")
  -  #@ app_edge_image("admin-panel")
  -  #@ app_latest_image("admin-panel")
  -  #@ app_src_resource("customer-portal", "main")
  -  #@ app_edge_image("customer-portal")
  -  #@ app_latest_image("customer-portal")

resource_types:
  -  #@ slack_resource_type()

