query AccountSetAndSubAccountsWithBalance(
  $journalId: UUID!
  $accountSetId: UUID!
  $first: Int!
  $after: String
) {
  accountSet(id: $accountSetId) {
    ...accountSetWithBalance
    subAccounts: members(first: $first, after: $after) {
      ...subAccount
    }
  }
}

fragment subAccount on AccountSetMemberConnection {
  pageInfo {
    startCursor
    endCursor
    hasNextPage
  }
  edges {
    cursor
    node {
      __typename
      ... on AccountSet {
        ...accountSetWithBalance
      }
      ... on Account {
        ...accountWithBalance
      }
    }
  }
}

fragment accountWithBalance on Account {
  accountId
  code
  name
  normalBalanceType
  ...accountBalances
}

fragment accountSetWithBalance on AccountSet {
  accountSetId
  name
  normalBalanceType
  ...accountSetBalances
  members(first: 1) {
    pageInfo {
      startCursor
    }
  }
}

fragment accountBalances on Account {
  btcBalances: balance(journalId: $journalId, currency: "BTC") {
    ...balancesByLayer
  }
  usdtBalances: balance(journalId: $journalId, currency: "USDT") {
    ...balancesByLayer
  }
  usdBalances: balance(journalId: $journalId, currency: "USD") {
    ...balancesByLayer
  }
}

fragment accountSetBalances on AccountSet {
  btcBalances: balance(currency: "BTC") {
    ...balancesByLayer
  }
  usdtBalances: balance(currency: "USDT") {
    ...balancesByLayer
  }
  usdBalances: balance(currency: "USD") {
    ...balancesByLayer
  }
}

fragment balancesByLayer on Balance {
  settled {
    ...balances
  }
  pending {
    ...balances
  }
  encumbrance {
    ...balances
  }
  allLayersAvailable: available(layer: ENCUMBRANCE) {
    ...balances
  }
}

fragment balances on BalanceAmount {
  normalBalance {
    units
    currency
  }
  drBalance {
    units
    currency
  }
  crBalance {
    units
    currency
  }
}
