mutation AccountSetCreate($input: AccountSetCreateInput!) {
  accountSetCreate(input: $input) {
    accountSet {
      accountSetId
    }
  }
}

mutation AddToAccountSet($input: AddToAccountSetInput!) {
  addToAccountSet(input: $input) {
    accountSet {
      accountSetId
    }
  }
}
