mutation AccountCreate($input: AccountCreateInput!) {
  accountCreate(input: $input) {
    account {
      accountId
    }
  }
}

query AccountById($id: UUID!, $journalId: UUID!) {
  account(id: $id) {
    accountId
    usdBalance: balance(journalId: $journalId, currency: "USDT") {
      settled {
        normalBalance {
          units
          currency
        }
      }
    }
    btcBalance: balance(journalId: $journalId, currency: "BTC") {
      settled {
        normalBalance {
          units
          currency
        }
      }
    }
    sets(first: 10) {
      edges {
        node {
          accountSetId
        }
      }
    }
  }
}

query AccountByExternalId($externalId: String!, $journalId: UUID!) {
  accountByExternalId(externalId: $externalId) {
    accountId
    usdBalance: balance(journalId: $journalId, currency: "USDT") {
      settled {
        normalBalance {
          units
          currency
        }
      }
    }
    btcBalance: balance(journalId: $journalId, currency: "BTC") {
      settled {
        normalBalance {
          units
          currency
        }
      }
    }
    sets(first: 10) {
      edges {
        node {
          accountSetId
        }
      }
    }
  }
}
