mutation BfxAddressBackedAccountCreate(
  $input: BfxAddressBackedAccountCreateInput!
) {
  bitfinex {
    addressBackedAccountCreate(input: $input) {
      account {
        address
        account {
          accountId
        }
      }
    }
  }
}

query BfxAddressBackedAccountById($id: UUID!) {
  bitfinex {
    addressBackedAccount(id: $id) {
      address
      account {
        accountId
      }
    }
  }
}
