query ChartOfAccounts($accountSetId: UUID!) {
  accountSet(id: $accountSetId) {
    ...accountSetDetails
    categories: members(first: 10) {
      edges {
        node {
          __typename
          ... on AccountSet {
            ...accountSetDetails
            accounts: members(first: 25, after: null) {
              ...account
            }
          }
          ... on Account {
            ...accountDetails
          }
        }
      }
    }
  }
}

fragment account on AccountSetMemberConnection {
  pageInfo {
    startCursor
    endCursor
    hasNextPage
  }
  edges {
    cursor
    node {
      __typename
      ... on AccountSet {
        ...subAccountSet
      }
      ... on Account {
        ...accountDetails
      }
    }
  }
}

fragment subAccountSet on AccountSet {
  ...accountSetDetails
  subAccounts: members(first: 1) {
    ...subAccount
  }
}

fragment subAccount on AccountSetMemberConnection {
  pageInfo {
    startCursor
    endCursor
    hasNextPage
  }
  edges {
    cursor
    node {
      __typename
      ... on AccountSet {
        ...accountSetDetails
      }
      ... on Account {
        ...accountDetails
      }
    }
  }
}

fragment accountSetDetails on AccountSet {
  accountSetId
  name
  normalBalanceType
  members(first: 1) {
    pageInfo {
      startCursor
    }
  }
}

fragment accountDetails on Account {
  accountId
  code
  name
  normalBalanceType
}
