query ChartOfAccounts($accountSetId: UUID!) {
  accountSet(id: $accountSetId) {
    ...accountSetDetails
    categories: members(first: 10) {
      edges {
        node {
          __typename
          ... on AccountSet {
            ...accountSetDetails
            categoryAccounts: members(first: 25, after: null) {
              pageInfo {
                startCursor
                endCursor
                hasNextPage
              }
              edges {
                node {
                  __typename
                  ... on AccountSet {
                    ...accountSetDetails
                    categorySubAccounts: members(first: 1) {
                      ...subAccount
                    }
                  }
                  ... on Account {
                    ...accountDetails
                  }
                }
              }
            }
          }
          ... on Account {
            ...accountDetails
          }
        }
      }
    }
  }
}

query ChartOfAccountsCategoryAccount(
  $accountSetId: UUID!
  $first: Int!
  $after: String
) {
  accountSet(id: $accountSetId) {
    ...accountSetDetails
    categorySubAccounts: members(first: $first, after: $after) {
      pageInfo {
        startCursor
        endCursor
        hasNextPage
      }
      edges {
        node {
          __typename
          ... on AccountSet {
            ...accountSetDetails
          }
          ... on Account {
            ...accountDetails
          }
        }
      }
    }
  }
}

query ChartOfAccountsCategory($accountSetId: UUID!) {
  accountSet(id: $accountSetId) {
    ...accountSetDetails
    categoryAccounts: members(first: 25) {
      pageInfo {
        startCursor
        endCursor
        hasNextPage
      }
      edges {
        node {
          __typename
          ... on AccountSet {
            ...accountSetDetails
            categorySubAccounts: members(first: 5, after: null) {
              ...subAccount
            }
          }
          ... on Account {
            ...accountDetails
          }
        }
      }
    }
  }
}

fragment accountSetDetails on AccountSet {
  accountSetId
  name
  normalBalanceType
  members(first: 1) {
    pageInfo {
      startCursor
    }
  }
}

fragment accountDetails on Account {
  accountId
  code
  name
  normalBalanceType
}

fragment subAccount on AccountSetMemberConnection {
  pageInfo {
    startCursor
    hasNextPage
  }
  edges {
    node {
      __typename
      ... on AccountSet {
        ...accountSetDetails
      }
      ... on Account {
        ...accountDetails
      }
    }
  }
}
