mutation CreateCreditFacilityAccounts(
  $facilityAccountId: UUID!
  $facilityAccountCode: String!
  $facilityAccountName: String!
  $facilitiesControlAccountSetId: UUID!
  $facilityDisbursedReceivableAccountId: UUID!
  $facilityDisbursedReceivableAccountCode: String!
  $facilityDisbursedReceivableAccountName: String!
  $facilitiesDisbursedReceivableControlAccountSetId: UUID!
) {
  facility: accountCreate(
    input: {
      accountId: $facilityAccountId
      code: $facilityAccountCode
      name: $facilityAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$facilitiesControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  disbursedReceivable: accountCreate(
    input: {
      accountId: $facilityDisbursedReceivableAccountId
      code: $facilityDisbursedReceivableAccountCode
      name: $facilityDisbursedReceivableAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$facilitiesDisbursedReceivableControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
}
