mutation CreateCreditFacilityAccounts(
  $facilityAccountId: UUID!
  $facilityAccountCode: String!
  $facilityAccountName: String!
  $facilitiesControlAccountSetId: UUID!
) {
  facility: accountCreate(
    input: {
      accountId: $facilityAccountId
      code: $facilityAccountCode
      name: $facilityAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$facilitiesControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
}
