query CustomerBalance(
  $journalId: UUID!
  $on_balance_sheet_account_id: UUID!
) {
  usd_balance: balance(
    journalId: $journalId
    accountId: $on_balance_sheet_account_id
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
    pending {
      normalBalance {
        units
        currency
      }
    }
  }
}
