query JournalById($id: UUID!) {
  journal(id: $id) {
    journalId
  }
}

mutation CoreJournalCreate($id: UUID!) {
  journalCreate(input: {
    journalId: $id
    name: "Lava Journal"
    description: "Journal for Lava"
  }) {
    journal {
      journalId
    }
  }
}
