mutation CreateLoanAccounts(
  $collateralAccountId: UUID!
  $collateralAccountCode: String!
  $outstandingAccountId: UUID!
  $outstandingAccountCode: String!
  $interestAccountId: UUID!
  $interestAccountCode: String!
  $loansAccountSetId: UUID!
  $interestRevenueAccountSetId: UUID!
) {
  collateral: accountCreate(input: {
    accountId: $collateralAccountId
    code: $collateralAccountCode
    name: "Loan Collateral"
  }) {
    account {
      accountId
    }
  }
  outstanding: accountCreate(input: {
    accountId: $outstandingAccountId
    code: $outstandingAccountCode
    name: "Loan Outstanding"
    normalBalanceType: "DEBIT"
    accountSetIds: [$loansAccountSetId]
  }) {
    account {
      accountId
    }
  }
  interest: accountCreate(input: {
    accountId: $interestAccountId
    code: $interestAccountCode
    name: "Loan Interest Revenue"
    accountSetIds: [$interestRevenueAccountSetId]
  }) {
    account {
      accountId
    }
  }
}
