mutation CreateLoanAccounts(
  $loanCollateralAccountId: UUID!
  $loanCollateralAccountCode: String!
  $loanCollateralAccountName: String!
  $loansCollateralControlAccountSetId: UUID!
  $loanPrincipalReceivableAccountId: UUID!
  $loanPrincipalReceivableAccountCode: String!
  $loanPrincipalReceivableAccountName: String!
  $loanInterestReceivableAccountId: UUID!
  $loanInterestReceivableAccountCode: String!
  $loanInterestReceivableAccountName: String!
  $interestAccountId: UUID!
  $interestAccountCode: String!
  $interestAccountName: String!
  $loansPrincipalReceivableControlAccountSetId: UUID!
  $loansInterestReceivableControlAccountSetId: UUID!
  $interestRevenueControlAccountSetId: UUID!
) {
  collateral: accountCreate(
    input: {
      accountId: $loanCollateralAccountId
      code: $loanCollateralAccountCode
      name: $loanCollateralAccountName
      accountSetIds: [$loansCollateralControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  principalReceivable: accountCreate(
    input: {
      accountId: $loanPrincipalReceivableAccountId
      code: $loanPrincipalReceivableAccountCode
      name: $loanPrincipalReceivableAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$loansPrincipalReceivableControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  interestReceivable: accountCreate(
    input: {
      accountId: $loanInterestReceivableAccountId
      code: $loanInterestReceivableAccountCode
      name: $loanInterestReceivableAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$loansInterestReceivableControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  interest: accountCreate(
    input: {
      accountId: $interestAccountId
      code: $interestAccountCode
      name: $interestAccountName
      accountSetIds: [$interestRevenueControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
}
