mutation CreateLoanAccounts(
  $loanCollateralAccountId: UUID!
  $loanCollateralAccountCode: String!
  $loanCollateralAccountName: String!
  $loansCollateralControlAccountSetId: UUID!
  $loanOutstandingAccountId: UUID!
  $loanOutstandingAccountCode: String!
  $loanOutstandingAccountName: String!
  $interestAccountId: UUID!
  $interestAccountCode: String!
  $interestAccountName: String!
  $loansAccountSetId: UUID!
  $loansOutstandingControlAccountSetId: UUID!
  $interestRevenueAccountSetId: UUID!
  $interestRevenueControlAccountSetId: UUID!
) {
  collateral: accountCreate(
    input: {
      accountId: $loanCollateralAccountId
      code: $loanCollateralAccountCode
      name: $loanCollateralAccountName
      accountSetIds: [$loansCollateralControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  outstanding: accountCreate(
    input: {
      accountId: $loanOutstandingAccountId
      code: $loanOutstandingAccountCode
      name: $loanOutstandingAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$loansAccountSetId, $loansOutstandingControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  interest: accountCreate(
    input: {
      accountId: $interestAccountId
      code: $interestAccountCode
      name: $interestAccountName
      accountSetIds: [
        $interestRevenueAccountSetId
        $interestRevenueControlAccountSetId
      ]
    }
  ) {
    account {
      accountId
    }
  }
}
