query UserBalances($journalId: UUID!, $unallocated_collateral_id: UUID!, $checking_id: UUID!) {
  account(id: $id) {
    accountId
    usdBalance: balance(journalId: $journalId, currency: "USD"){
      settled {
        normalBalance {
          units
          currency
        }
      }
    }
    btcBalance: balance(journalId: $journalId, currency: "BTC"){
      settled {
        normalBalance {
          units
          currency
        }
      }
    }
  }
}
