query UserBalance(
  $journalId: UUID!
  $unallocatedCollateralId: UUID!
  $checkingId: UUID!
) {
  unallocated_collateral: balance(
    journalId: $journalId
    accountId: $unallocatedCollateralId
    currency: "BTC"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  checking: balance(
    journalId: $journalId
    accountId: $checkingId
    currency: "USDT"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
    pending {
      normalBalance {
        units
        currency
      }
    }
  }
}
