mutation CreateUserAccounts(
  $onBalanceSheetAccountId: UUID!
  $onBalanceSheetAccountCode: String!
  $userDepositAccountSetId: UUID!
  $tronAccountId: UUID!
  $tronAccountCode: String!
  $offBalanceSheetAccountId: UUID!
  $offBalanceSheetAccountCode: String!
  $btcAccountId: UUID!
  $btcAccountCode: String!
) {
  onBalanceSheet: accountCreate(input: {
    accountId: $onBalanceSheetAccountId
    code: $onBalanceSheetAccountCode
    name: "User deposit"
    accountSetIds: [$userDepositAccountSetId]
  }) {
    account {
      accountId
    }
  }
  tron_address: bitfinex {
    addressBackedAccountCreate(input: {
      integrationId:  "00000000-0000-0000-0000-200000000000"
      accountId: $tronAccountId
      code: $tronAccountCode
      type: "TRX"
      name: "User tron income"
      depositCreditAccountId: $onBalanceSheetAccountId
    }) {
      account {
        address
        account {
          accountId
        }
      }
    }
  }
  offBalanceSheet: accountCreate(input: {
    accountId: $offBalanceSheetAccountId
    code: $offBalanceSheetAccountCode
    name: "User deposit off balance sheet"
  }) {
    account {
      accountId
    }
  }
  btc_address: bitfinex {
    addressBackedAccountCreate(input: {
      integrationId:  "10000000-0000-0000-0000-200000000000"
      accountId: $btcAccountId
      code: $btcAccountCode
      type: "BTC"
      name: "User btc income"
      depositCreditAccountId: $offBalanceSheetAccountId
    }) {
      account {
        address
        account {
          accountId
        }
      }
    }
  }
}
