config {
  type: "operations",
  hasOutput: true,
  description: "Ready for export Regulatory Report 'referencia.xml' of norm 'NPB4-17'"
}

CREATE OR REPLACE TABLE FUNCTION ${self()} (asof TIMESTAMP) AS (

SELECT
    LEFT(REPLACE(nit_deudor, '-', ''), 14) AS `nit_deudor`
  , LEFT(`cod_cartera`, 2) AS `cod_cartera`
  , LEFT(`cod_activo`, 2) AS `cod_activo`
  , LEFT(`num_referencia`, 20) AS `num_referencia`
  , FORMAT('%.2f', ROUND(`monto_referencia`, 2)) AS `monto_referencia`
  , FORMAT('%.2f', ROUND(`saldo_referencia`, 2)) AS `saldo_referencia`
  , FORMAT('%.2f', ROUND(`saldo_vigente_k`, 2)) AS `saldo_vigente_k`
  , FORMAT('%.2f', ROUND(`saldo_vencido_k`, 2)) AS `saldo_vencido_k`
  , FORMAT('%.2f', ROUND(`saldo_vigente_i`, 2)) AS `saldo_vigente_i`
  , FORMAT('%.2f', ROUND(`saldo_vencido_i`, 2)) AS `saldo_vencido_i`
  , FORMAT('%.2f', ROUND(`abono_deposito`, 2)) AS `abono_deposito`
  , FORMAT_DATE('%Y-%m-%d', CAST(`fecha_otorgamiento` AS DATE)) AS `fecha_otorgamiento`
  , FORMAT_DATE('%Y-%m-%d', CAST(`fecha_vencimiento` AS DATE)) AS `fecha_vencimiento`
  , FORMAT_DATE('%Y-%m-%d', CAST(`fecha_castigo` AS DATE)) AS `fecha_castigo`
  , LEFT(`estado_credito`, 1) AS `estado_credito`
  , FORMAT('%.2f', ROUND(`saldo_mora_k`, 2)) AS `saldo_mora_k`
  , FORMAT('%.2f', ROUND(`saldo_mora_i`, 2)) AS `saldo_mora_i`
  , CAST(`dias_mora_k` AS STRING) AS `dias_mora_k`
  , CAST(`dias_mora_i` AS STRING) AS `dias_mora_i`
  , FORMAT_DATE('%Y-%m-%d', CAST(`fecha_inicio_mora_k` AS DATE)) AS `fecha_inicio_mora_k`
  , FORMAT_DATE('%Y-%m-%d', CAST(`fecha_inicio_mora_i` AS DATE)) AS `fecha_inicio_mora_i`
  , LEFT(`pago_capital`, 1) AS `pago_capital`
  , LEFT(`pago_interes`, 1) AS `pago_interes`
  , CAST(`periodo_gracia_k` AS STRING) AS `periodo_gracia_k`
  , CAST(`periodo_gracia_i` AS STRING) AS `periodo_gracia_i`
  , LEFT(`garante`, 10) AS `garante`
  , LEFT(`emisión`, 15) AS `emisión`
  , CAST(`pais_destino_credito` AS STRING) AS `pais_destino_credito`
  , LEFT(`destino`, 6) AS `destino`
  , LEFT(`codigo_moneda`, 1) AS `codigo_moneda`
  , FORMAT('%.2f', ROUND(`tasa_interes`, 2)) AS `tasa_interes`
  , FORMAT('%.2f', ROUND(`tasa_contractual`, 2)) AS `tasa_contractual`
  , FORMAT('%.2f', ROUND(`tasa_referencia`, 2)) AS `tasa_referencia`
  , FORMAT('%.2f', ROUND(`tasa_efectiva`, 2)) AS `tasa_efectiva`
  , LEFT(`tipo_tasa_interes`, 1) AS `tipo_tasa_interes`
  , LEFT(`tipo_prestamo`, 2) AS `tipo_prestamo`
  , LEFT(`codigo_recurso`, 2) AS `codigo_recurso`
  , FORMAT_DATE('%Y-%m-%d', CAST(`ultima_fecha_venc` AS DATE)) AS `ultima_fecha_venc`
  , CAST(`dias_prorroga` AS STRING) AS `dias_prorroga`
  , FORMAT('%.2f', ROUND(`monto_desembolsado`, 2)) AS `monto_desembolsado`
  , LEFT(`tipo_credito`, 2) AS `tipo_credito`
  , FORMAT_DATE('%Y-%m-%d', CAST(`fecha_ultimo_pago_k` AS DATE)) AS `fecha_ultimo_pago_k`
  , FORMAT_DATE('%Y-%m-%d', CAST(`fecha_ultimo_pago_i` AS DATE)) AS `fecha_ultimo_pago_i`
  , CAST(`dia_pago_k` AS STRING) AS `dia_pago_k`
  , CAST(`dia_pago_i` AS STRING) AS `dia_pago_i`
  , CAST(`cuota_mora_k` AS STRING) AS `cuota_mora_k`
  , CAST(`cuota_mora_i` AS STRING) AS `cuota_mora_i`
  , FORMAT('%.2f', ROUND(`monto_cuota`, 2)) AS `monto_cuota`
  , LEFT(`cuenta_contable_k`, 12) AS `cuenta_contable_k`
  , LEFT(`cuenta_contable_i`, 12) AS `cuenta_contable_i`
  , FORMAT_DATE('%Y-%m-%d', CAST(`fecha_cancelacion` AS DATE)) AS `fecha_cancelacion`
  , FORMAT('%.2f', ROUND(`adelanto_capital`, 2)) AS `adelanto_capital`
  , FORMAT('%.2f', ROUND(`riesgo_neto`, 2)) AS `riesgo_neto`
  , FORMAT('%.2f', ROUND(`saldo_seguro`, 2)) AS `saldo_seguro`
  , FORMAT('%.2f', ROUND(`saldo_costas_procesales`, 2)) AS `saldo_costas_procesales`
  , LEFT(`tipo_tarjeta_credito`, 1) AS `tipo_tarjeta_credito`
  , LEFT(`clase_tarjeta_credito`, 1) AS `clase_tarjeta_credito`
  , LEFT(`producto_tarjeta_credito`, 20) AS `producto_tarjeta_credito`
  , FORMAT('%.2f', ROUND(`valor_garantia_cons`, 2)) AS `valor_garantia_cons`
  , LEFT(`municipio_otorgamiento`, 4) AS `municipio_otorgamiento`
  , FORMAT('%.2f', ROUND(`reserva_referencia`, 2)) AS `reserva_referencia`
  , LEFT(`etapa_judicial`, 1) AS `etapa_judicial`
  , FORMAT_DATE('%Y-%m-%d', CAST(`fecha_demanda` AS DATE)) AS `fecha_demanda`
  , CAST(`plazo_credito` AS STRING) AS `plazo_credito`
  , LEFT(`orden_descuento`, 2) AS `orden_descuento`
  , LEFT(`categoria_riesgo_ref`, 2) AS `categoria_riesgo_ref`
  , FORMAT('%.2f', ROUND(`reserva_constituir`, 2)) AS `reserva_constituir`
  , FORMAT('%.2f', ROUND(`porcentaje_reserva`, 2)) AS `porcentaje_reserva`
  , FORMAT('%.2f', ROUND(`pago_cuota`, 2)) AS `pago_cuota`
  , FORMAT_DATE('%Y-%m-%d', CAST(`fecha_pago` AS DATE)) AS `fecha_pago`
  , FORMAT('%.2f', ROUND(`porcenta_reserva_descon`, 2)) AS `porcenta_reserva_descon`
  , FORMAT('%.2f', ROUND(`porcenta_adiciona_descon`, 2)) AS `porcenta_adiciona_descon`
  , LEFT(`depto_destino_credito`, 2) AS `depto_destino_credito`
  , FORMAT('%.2f', ROUND(`porc_reserva_referencia`, 2)) AS `porc_reserva_referencia`
  , FORMAT('%.2f', ROUND(`calculo_brecha`, 2)) AS `calculo_brecha`
  , FORMAT('%.2f', ROUND(`ajuste_brecha`, 2)) AS `ajuste_brecha`
  , LEFT(`programa_asist_cafe`, 2) AS `programa_asist_cafe`
  , FORMAT_DATE('%Y-%m-%d', CAST(`fecha_cump_cafe` AS DATE)) AS `fecha_cump_cafe`
  , CURRENT_TIMESTAMP() AS created_at
FROM
  ${ref("stg_02_npb4_17_referencia_xml_raw")}(asof)

)
