mutation AddCollateralTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
  $bankCollateralAccountId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "ADD_COLLATERAL"
      description: "Add collateral to a lending product."
      params: [
        {
          name: "collateralAccount"
          type: UUID
          description: "Lending Product Collateral account ID."
        }
        {
          name: "collateralAmount"
          type: DECIMAL
          description: "Amount of BTC being put into the lending product."
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: $bankCollateralAccountId
          units: "params.collateralAmount"
          currency: "'BTC'"
          entryType: "'ADD_COLLATERAL_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.collateralAccount"
          units: "params.collateralAmount"
          currency: "'BTC'"
          entryType: "'ADD_COLLATERAL_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation RemoveCollateralTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
  $bankCollateralAccountId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "REMOVE_COLLATERAL"
      description: "Remove collateral from the lending product."
      params: [
        {
          name: "collateralAccount"
          type: UUID
          description: "Lending Product Collateral account ID."
        }
        {
          name: "collateralAmount"
          type: DECIMAL
          description: "Amount of BTC being removed from the lending product."
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: "params.collateralAccount"
          units: "params.collateralAmount"
          currency: "'BTC'"
          entryType: "'REMOVE_COLLATERAL_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: $bankCollateralAccountId
          units: "params.collateralAmount"
          currency: "'BTC'"
          entryType: "'REMOVE_COLLATERAL_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostAddCollateralTransaction(
  $transactionId: UUID!
  $collateralAccount: UUID!
  $collateralAmount: Decimal!
  $externalId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "ADD_COLLATERAL"
      params: {
        collateralAccount: $collateralAccount
        collateralAmount: $collateralAmount
        externalId: $externalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
      createdAt
    }
  }
}

mutation PostRemoveCollateralTransaction(
  $transactionId: UUID!
  $collateralAccount: UUID!
  $collateralAmount: Decimal!
  $externalId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "REMOVE_COLLATERAL"
      params: {
        collateralAccount: $collateralAccount
        collateralAmount: $collateralAmount
        externalId: $externalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
      createdAt
    }
  }
}
