mutation CreditFacilityDisbursalTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
  $omnibusCreditFacilityAccount: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "CREDIT_FACILITY_DISBURSAL"
      description: "Payout disursal."
      params: [
        {
          name: "facilityAccount"
          type: UUID
          description: "Credit facility account ID."
        }
        {
          name: "facilityDisbursedReceivableAccount"
          type: UUID
          description: "Credit facility amount-outstanding account ID."
        }
        {
          name: "checkingAccount"
          type: UUID
          description: "User Checking account ID."
        }
        {
          name: "disbursedAmount"
          type: DECIMAL
          description: "Amount of USD being issued for the disursal."
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: $omnibusCreditFacilityAccount
          units: "params.disbursedAmount"
          currency: "'USD'"
          entryType: "'CREDIT_FACILITY_DISBURSAL_DRAWDOWN_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.facilityAccount"
          units: "params.disbursedAmount"
          currency: "'USD'"
          entryType: "'CREDIT_FACILITY_DISBURSAL_DRAWDOWN_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.facilityDisbursedReceivableAccount"
          units: "params.disbursedAmount"
          currency: "'USD'"
          entryType: "'CREDIT_FACILITY_DISBURSAL_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.checkingAccount"
          units: "params.disbursedAmount"
          currency: "'USD'"
          entryType: "'CREDIT_FACILITY_DISBURSAL_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostCreditFacilityDisbursalTransaction(
  $transactionId: UUID!
  $facilityAccount: UUID!
  $facilityDisbursedReceivableAccount: UUID!
  $checkingAccount: UUID!
  $disbursedAmount: Decimal!
  $externalId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "CREDIT_FACILITY_DISBURSAL"
      params: {
        facilityAccount: $facilityAccount
        facilityDisbursedReceivableAccount: $facilityDisbursedReceivableAccount
        checkingAccount: $checkingAccount
        disbursedAmount: $disbursedAmount
        externalId: $externalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
      createdAt
    }
  }
}
