union Transaction = Deposit | Withdrawal

extend type Loan {
  collateralToMatchInitialCvl: Satoshis
}

extend type CreditFacility {
  collateralToMatchInitialCvl: Satoshis
}

extend type Customer {
  transactions: [Transaction!]!
}
