query AuditLogs($first: Int!, $after: String) {
  audit(first: $first, after: $after) {
    edges {
      cursor
      node {
        id
        subject {
          ... on User {
            userId
            email
            roles
          }
          ... on Customer {
            customerId
            email
            status
            level
            applicantId
          }
          ... on System {
            name
          }
        }
        object
        action
        authorized
        recordedAt
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
