query BalanceSheetConfig {
  balanceSheetConfig {
    chartOfAccountsAssetsCode
    chartOfAccountsLiabilitiesCode
    chartOfAccountsEquityCode
    chartOfAccountsRevenueCode
    chartOfAccountsCostOfRevenueCode
    chartOfAccountsExpensesCode
  }
}
