query BalanceSheet($from: Timestamp!) {
  balanceSheet(from: $from) {
    name
    balance {
      ...amountsByCurrency
    }
    categories {
      name
      amounts {
        ...amountsByCurrency
      }
      accounts {
        ... on Account {
          id
          name
          amounts {
            ...amountsByCurrency
          }
        }
        ... on AccountSet {
          id
          name
          amounts {
            ...amountsByCurrency
          }
        }
      }
    }
  }
}

fragment amountsByCurrency on AccountAmountsByCurrency {
  usd: usd {
    ...usdAmountsInPeriod
  }
}

fragment usdAmountsInPeriod on UsdAccountAmountsInPeriod {
  balancesByLayer: closingBalance {
    ...usdAmounts
  }
}

fragment usdAmounts on LayeredUsdAccountBalanceAmounts {
  all {
    ...usdLayers
  }
  settled {
    ...usdLayers
  }
  pending {
    ...usdLayers
  }
  encumbrance {
    ...usdLayers
  }
}

fragment usdLayers on UsdAccountBalanceAmounts {
  netDebit
  debit
  credit
}
