query ChartOfAccounts {
  chartOfAccounts {
    name
    categories {
      assets {
        ...category
      }
      liabilities {
        ...category
      }
      equity {
        ...category
      }
      revenues {
        ...category
      }
      expenses {
        ...category
      }
    }
  }
}

fragment category on ChartCategory {
  name
  accountCode
  controlAccounts {
    name
    accountCode
    controlSubAccounts {
      name
      accountCode
    }
  }
}