query ChartOfAccounts {
  chartOfAccounts {
    name
    categories {
      name
      accounts {
        __typename
        ... on AccountSet {
          queryableId: id
          name
          hasSubAccounts
        }
        ... on Account {
          id
          name
        }
      }
    }
  }
}
