query ChartOfAccount {
  chartOfAccounts {
    name
    categories {
      name
      accounts {
        __typename
        ... on AccountSetWithBalance {
          queryableId: id
          name
          hasSubAccounts
        }
        ... on AccountWithBalance {
          id
          name
        }
      }
    }
  }
}
