query ChartOfAccountsAccountSet($accountSetId: UUID!) {
  chartOfAccountsAccountSet(accountSetId: $accountSetId) {
    name
    subAccounts(first: 10) {
      __typename
      ... on AccountDetails {
        id
        name
      }
      ... on AccountSetDetails {
        id
        name
        hasSubAccounts
      }
    }
  }
}
