mutation CollateralizationStateUpdate(
  $input: CollateralizationStateUpdateInput!
) {
  collateralizationStateUpdate(input: $input) {
    loan {
      loanId
      collateralizationState
    }
  }
}
