mutation LoanCollateralizationStateTriggerRefresh(
  $input: LoanCollateralizationStateTriggerRefreshInput!
) {
  loanCollateralizationStateTriggerRefresh(input: $input) {
    loan {
      loanId
      collateralizationState
    }
  }
}
