mutation WithdrawalConfirm($input: WithdrawalConfirmInput!) {
  withdrawalConfirm(input: $input) {
    withdrawal {
      withdrawalId
      status
      customer {
        customerId
        balance {
          checking {
            settled {
              usdBalance
            }
            pending {
              usdBalance
            }
          }
        }
      }
    }
  }
}
