mutation CreditFacilityComplete($input: CreditFacilityCompleteInput!) {
  creditFacilityComplete(input: $input) {
    creditFacility {
      creditFacilityId
      balance {
        collateral {
          btcBalance
        }
      }
    }
  }
}
