query creditConfig {
  creditConfig {
    chartOfAccountFacilityOmnibusParentCode
    chartOfAccountCollateralOmnibusParentCode
    chartOfAccountFacilityParentCode
    chartOfAccountCollateralParentCode
    chartOfAccountInterestIncomeParentCode
    chartOfAccountFeeIncomeParentCode
    chartOfAccountShortTermIndividualDisbursedReceivableParentCode
    chartOfAccountShortTermGovernmentEntityDisbursedReceivableParentCode
    chartOfAccountShortTermPrivateCompanyDisbursedReceivableParentCode
    chartOfAccountShortTermBankDisbursedReceivableParentCode
    chartOfAccountShortTermFinancialInstitutionDisbursedReceivableParentCode
    chartOfAccountShortTermForeignAgencyOrSubsidiaryDisbursedReceivableParentCode
    chartOfAccountShortTermNonDomiciledCompanyDisbursedReceivableParentCode
    chartOfAccountLongTermIndividualDisbursedReceivableParentCode
    chartOfAccountLongTermGovernmentEntityDisbursedReceivableParentCode
    chartOfAccountLongTermPrivateCompanyDisbursedReceivableParentCode
    chartOfAccountLongTermBankDisbursedReceivableParentCode
    chartOfAccountLongTermFinancialInstitutionDisbursedReceivableParentCode
    chartOfAccountLongTermForeignAgencyOrSubsidiaryDisbursedReceivableParentCode
    chartOfAccountLongTermNonDomiciledCompanyDisbursedReceivableParentCode
    chartOfAccountShortTermIndividualInterestReceivableParentCode
    chartOfAccountShortTermGovernmentEntityInterestReceivableParentCode
    chartOfAccountShortTermPrivateCompanyInterestReceivableParentCode
    chartOfAccountShortTermBankInterestReceivableParentCode
    chartOfAccountShortTermFinancialInstitutionInterestReceivableParentCode
    chartOfAccountShortTermForeignAgencyOrSubsidiaryInterestReceivableParentCode
    chartOfAccountShortTermNonDomiciledCompanyInterestReceivableParentCode
    chartOfAccountLongTermIndividualInterestReceivableParentCode
    chartOfAccountLongTermGovernmentEntityInterestReceivableParentCode
    chartOfAccountLongTermPrivateCompanyInterestReceivableParentCode
    chartOfAccountLongTermBankInterestReceivableParentCode
    chartOfAccountLongTermFinancialInstitutionInterestReceivableParentCode
    chartOfAccountLongTermForeignAgencyOrSubsidiaryInterestReceivableParentCode
    chartOfAccountLongTermNonDomiciledCompanyInterestReceivableParentCode
    chartOfAccountOverdueIndividualDisbursedReceivableParentCode
    chartOfAccountOverdueGovernmentEntityDisbursedReceivableParentCode
    chartOfAccountOverduePrivateCompanyDisbursedReceivableParentCode
    chartOfAccountOverdueBankDisbursedReceivableParentCode
    chartOfAccountOverdueFinancialInstitutionDisbursedReceivableParentCode
    chartOfAccountOverdueForeignAgencyOrSubsidiaryDisbursedReceivableParentCode
    chartOfAccountOverdueNonDomiciledCompanyDisbursedReceivableParentCode
  }
}
