mutation CreditFacilityCollateralUpdate(
  $input: CreditFacilityCollateralUpdateInput!
) {
  creditFacilityCollateralUpdate(input: $input) {
    creditFacility {
      creditFacilityId
      status
    }
  }
}
