mutation CreditFacilityDisbursementConfirm(
  $input: CreditFacilityDisbursementConfirmInput!
) {
  creditFacilityDisbursementConfirm(input: $input) {
    disbursement {
      id
      status
    }
  }
}
