mutation CreditFacilityDisbursalInitiate(
  $input: CreditFacilityDisbursalInitiateInput!
) {
  creditFacilityDisbursalInitiate(input: $input) {
    disbursal {
      id
      index
      status
    }
  }
}
