mutation creditFacilityPartialPayment(
  $input: CreditFacilityPartialPaymentInput!
) {
  creditFacilityPartialPayment(input: $input) {
    creditFacility {
      creditFacilityId
      balance {
        outstanding {
          usdBalance
        }
      }
    }
  }
}
