mutation CreditFacilityDisbursementInitiate(
  $input: CreditFacilityDisbursementInitiateInput!
) {
  creditFacilityDisbursementInitiate(input: $input) {
    disbursement {
      id
      index
      status
    }
  }
}
