mutation {
  currentTermsUpdate(
    input: {
      annualRate: "12"
      accrualCycleInterval: END_OF_MONTH
      duration: { period: MONTHS, units: 3 }
      liquidationCvl: "105"
      marginCallCvl: "125"
      initialCvl: "140"
    }
  ) {
    terms {
      termsId
    }
  }
}
