query depositConfig {
  depositConfig {
    chartOfAccountsOmnibusParentCode
    chartOfAccountsIndividualDepositAccountsParentCode
    chartOfAccountsGovernmentEntityDepositAccountsParentCode
    chartOfAccountPrivateCompanyDepositAccountsParentCode
    chartOfAccountBankDepositAccountsParentCode
    chartOfAccountFinancialInstitutionDepositAccountsParentCode
    chartOfAccountNonDomiciledCompanyDepositAccountsParentCode
  }
}
