query loan($id: UUID!) {
  loan(id: $id) {
    loanId
    collateralizationState
    balance {
      collateral {
        btcBalance
      }
      outstanding {
        usdBalance
      }
      interestIncurred {
        usdBalance
      }
    }
    transactions {
      ... on IncrementalPayment {
        cents
        recordedAt
      }
      ... on InterestAccrued {
        cents
        recordedAt
      }
      ... on CollateralUpdated {
        satoshis
        recordedAt
        action
      }
      ... on LoanOrigination {
        cents
        recordedAt
      }
    }
    repaymentPlan {
      repaymentType
      status
      initial
      outstanding
      accrualAt
      dueAt
    }
  }
}
