query creditFacility($id: UUID!) {
  creditFacility(id: $id) {
    creditFacilityId
    status
    maturesAt
    collateralizationState
    facilityAmount
    disbursals {
      id
      status
    }
    transactions {
      ... on CreditFacilityInterestAccrued {
        __typename
        cents
        recordedAt
        txId
        days
      }
    }
    balance {
      facilityRemaining {
        usdBalance
      }
      outstanding {
        usdBalance
      }
      collateral {
        btcBalance
      }
      disbursed {
        total {
          usdBalance
        }
        outstanding {
          usdBalance
        }
      }
      interest {
        total {
          usdBalance
        }
        outstanding {
          usdBalance
        }
      }
    }
  }
}
