mutation WithdrawalInitiate($input: WithdrawalInitiateInput!) {
  withdrawalInitiate(input: $input) {
    withdrawal {
      withdrawalId
      customer {
        customerId
        balance {
          checking {
            settled {
              usdBalance
            }
            pending {
              usdBalance
            }
          }
        }
      }
    }
  }
}
