mutation WithdrawalInitiate($input: WithdrawalInitiateInput!) {
  withdrawalInitiate(input: $input) {
    withdrawal {
      withdrawalId
      status
      customer {
        customerId
        balance {
          checking {
            settled
            pending
          }
        }
      }
    }
  }
}
