mutation UserPledgeCollateral($input: UserPledgeCollateralInput!) {
  userPledgeCollateral(input: $input) {
    user {
      userId
      balance {
        unallocatedCollateral {
          settled {
            btcBalance
          }
        }
      }
    }
  }
}
