query TermsTemplateGet($id: UUID!) {
  termsTemplate(id: $id) {
    termsId
    name
    values {
      annualRate
      accrualCycleInterval
      duration {
        period
        units
      }
      liquidationCvl
      marginCallCvl
      initialCvl
    }
  }
}
