mutation TermsTemplateUpdate($input: TermsTemplateUpdateInput!) {
  termsTemplateUpdate(input: $input) {
    termsTemplate {
      termsId
      name
      values {
        annualRate
        accrualInterval
        duration {
          period
          units
        }
        liquidationCvl
        marginCallCvl
        initialCvl
      }
    }
  }
}
