query TrialBalance($from: Timestamp!) {
  trialBalance(from: $from) {
    name
    total {
      ...amountsByCurrency
    }
    subAccounts {
      ... on Account {
        name
        amounts {
          ...amountsByCurrency
        }
      }
      ... on AccountSet {
        name
        amounts {
          ...amountsByCurrency
        }
      }
    }
  }
}

fragment amountsByCurrency on AccountAmountsByCurrency {
  btc: btc {
    ...btcAmountsInPeriod
  }
  usd: usd {
    ...usdAmountsInPeriod
  }
}

fragment btcAmountsInPeriod on BtcAccountAmountsInPeriod {
  balancesByLayer: closingBalance {
    ...btcAmounts
  }
}

fragment usdAmountsInPeriod on UsdAccountAmountsInPeriod {
  balancesByLayer: closingBalance {
    ...usdAmounts
  }
}

fragment btcAmounts on LayeredBtcAccountBalanceAmounts {
  all {
    ...btcLayers
  }
  settled {
    ...btcLayers
  }
  pending {
    ...btcLayers
  }
  encumbrance {
    ...btcLayers
  }
}

fragment usdAmounts on LayeredUsdAccountBalanceAmounts {
  all {
    ...usdLayers
  }
  settled {
    ...usdLayers
  }
  pending {
    ...usdLayers
  }
  encumbrance {
    ...usdLayers
  }
}

fragment usdLayers on UsdAccountBalanceAmounts {
  netDebit
  debit
  credit
}

fragment btcLayers on BtcAccountBalanceAmounts {
  netDebit
  debit
  credit
}
